### ISSUE TITLE
Readme 里 示例无法生成证书

### ISSUE THREAD

**Issue by yangg** [alibaba/anyproxy#102]
#### Which platform are you running AnyProxy
Windows
3.10.3

#### Your expected behavior of AnyProxy
readme 里代码，`!proxy.isRootCAFileExists() && proxy.generateRootCA(); `能够生成证书

#### The actual behavior of AnyProxy
生成失败，因为证书生成是异步的，在proxyServer 里直接退出了
```js
function startServer() {
  new proxy.proxyServer(...);
}

//create cert when you want to use https features
//please manually trust this rootCA when it is the first time you run it
if(proxy.isRootCAFileExists()) {
  startServer();
} else {
  proxy.generateRootCA(startServer);
}
```

**Comment by codingfishman** [comment]
Hi @yangg 
   抱歉在Readme中的文档还未更新，generateRootCA()是一个异步函数，且可以传入回调，因此你可以在回调中来启动AnyProxy。
  generateRootCA()函数的文档可查看： [这里](https://www.npmjs.com/package/node-easy-cert#generaterootcaoptions-callbackerror-keypath-crtpath)
