### ISSUE TITLE
Delimiter _underscore is being changed to -hyphen in request headers

### ISSUE THREAD

**Issue by kvijaya** [alibaba/anyproxy#103]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
Windows

#### The version of the AnyProxy
3.10.3

#### Your expected behavior of AnyProxy
Request headers like 'CSRF_TOKEN' should not get converted to 'CSRF-TOKEN'. i.e. Underscores should not be changed to Hyphens.

#### The actual behavior of AnyProxy
Since 3.10.3, requestHandler.js does a util.upper_keys which is messing up strings with underscores.
```javascript
reqData = userRule.replaceRequestData(req,reqData) || reqData;
options.headers = util.lower_keys(options.headers);
options.headers["content-length"] = reqData.length; //rewrite content length info
/*Troublemaker*/
options.headers = util.upper_keys(options.headers);
```

#### The log of the error
The request fails if header gets modified unintentionally. In our case, the CSRF token was not accepted and the request failed with a 401.

**Comment by darahak** [comment]
Looks like the problem actually comes from [header-case](https://github.com/blakeembrey/header-case/blob/master/header-case.js) which was introduced by this [commit](https://github.com/alibaba/anyproxy/commit/e489e188f4224625fb1c6bab89ab1b6a09799add) with [change-case](https://github.com/blakeembrey/change-case).

According to [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2), underscores (ASCII code **95**) should be allowed in header field names.

    header-field   = field-name ":" OWS field-value OWS

    field-name     = token
    field-value    = *( field-content / obs-fold )
    field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
    field-vchar    = VCHAR / obs-text

    obs-fold       = CRLF 1*( SP / HTAB )
                    ; obsolete line folding
                    ; see Section 3.2.4

    tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
            "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
    token = 1*tchar

**Comment by codingfishman** [comment]
Hi @kvijaya 
   Thanks to @darahak , yes, the issue was introduced by the commit.   
    We made it because the header letters will be `lowercased` by nodejs when we received them and forward them to the real server, while for certain websites they only recoginize the `uppercased` headers, which is not a standard way either. We did this for compability.   
But it handles wrongly with the *_underscore*, we'll try some other ways.

**Comment by darahak** [comment]
Yes, the `headers` field is lower-cased by Node.js `http` module, but you're also supposed to get a [rawHeaders](https://nodejs.org/api/http.html#http_message_rawheaders) field with the original headers.

**Comment by codingfishman** [comment]
Thanks for pointing out, @darahak !
By converting the `rawHeaders` to headers, we can get the real headers now, and there is no need to `upper_case` the headers.
