### ISSUE TITLE
在 --file,输出的日志中，能打印出 响应报文的，报文体，并且支持中文显示！

### ISSUE THREAD

**Issue by mengde0077** [alibaba/anyproxy#104]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

MAC
#### The version of the AnyProxy

3.10.3

#### Your expected behavior of AnyProxy

我期待，在 --file,输出的日志中，能打印出 响应报文的，报文体，并且支持中文显示！
#### The actual behavior of AnyProxy

我在
function normalizeInfo(id,info){
   中加上 

        singleRecord.resBody    = info.resBody;

#### The log of the error

但日志中打印的 resBody 的内容不是我想要的！

{"_id":4,"id":4,"url":"http://static2.8dol.com/cloudstore/goods/20161024_40956.png@180w_1o.webp","host":"static2.8dol.com","path":"    /cloudstore/goods/20161024_40956.png@180w_1o.webp","method":"GET","reqHeader":{"user-agent":"Dalvik/2.1.0 (Linux; U; Android 5.1.1;     vivo X7 Build/LMY47V)","host":"static2.8dol.com","connection":"Keep-Alive","content-length":0},"startTime":1478653685641,"reqBody"    :"","protocol":"http","statusCode":200,"endTime":1478653685739,"resHeader":{"server":"Tengine","content-type":"image/webp","connect    ion":"keep-alive","date":"Tue, 08 Nov 2016 04:50:16 GMT","x-oss-request-id":"58215988EAE4ABEE052B37BA","etag":"\"959C7F17C61227419B    B055A3D87AA091\"","last-modified":"Mon, 24 Oct 2016 04:32:26 GMT","x-oss-object-type":"Normal","x-oss-hash-crc64ecma":"548741460944    1398751","cache-control":"max-age=86400","via":"cache17.l2cm12[0,200-0,H], cache17.l2cm12[0,0], kunlun6.cn135[64,200-0,M], kunlun4.    cn135[66,0]","age":"73061","x-cache":"MISS TCP_MISS dirn:3:171257504","x-swift-savetime":"Wed, 09 Nov 2016 01:07:57 GMT","x-swift-c    achetime":"13339","timing-allow-origin":"*","eagleid":"3d9376c414786536771733231e"},"length":2268,"resBody":{"0":82,"1":73,"2":70,"    3":70,"4":212,"5":8,"6":0,"7":0,"8":87,"9":69,"10":66,"11":80,"12":86,"13":80,"14":56,"15":32,"16":200,"17":8,"18":0,"19":0,"20":17    6,"21":43,"22":0,"23":157,"24":1,"25":42,"26":180,"27":0,"28":180,"29":0,"30":62,"31":109,"32":54,"33":151,"34":72,"35":166,"36":36    ,"37":163,"38":33,"39":165,"40":55,"41":168,"42":240,"43":192,"44":13,"45":137,"46":77,"47":220,"48":46,"49":125,"50":127,"51":128,    "52":40,"53":127,"54":170,"55":243,"56":64,"57":171,"58":255,"59":101,"60":252,"61":37,"62":253,"63":19,"64":140,"65":160,"66":174,    "67":118,"68":57,"69":253,"70":79,"71":186,"72":175,"73":131,"74":222,"75":169,"76":63,"77":41,"78":251,"79":2,"80":126,"81":181,"8    2":244,"83":200,"84":243,"85":7,"86":251,"87":31,"88":251,"89":59,"90":239,"91":13,"92":232,"93":79,"94":252,"95":39,"96":168,"97":    7,"98":246,"99":238,"100":163,"101":191,"102":67,"103":15,"104":45,"105":207,"106":101,"107":95,"108":221,"109":95,"110":75,"111":2    6,"112":202,"113":29,"114":28,"115":137,"116":44,"117":233,"118":60,"119":221,"120":240,"121":30,"122":97,"123":192,"124":200,"125"    :228,"126":190,"127":176,"128":142,"129":235,"130":95,"131":100,"132":52,"133":141,"134":101,"135":17,"136":85,"137":95,"138":217,"    139":7,"140":146,"141":208,"142":169,"143":119,"144":206,"145":40,"146":138,"147":170,"148":254,"149":200,"150":60,"151":150,"152":    96,"153":57,"154":144,"155":139,"156":218,"157":218,"158":132,"159":85,"160":253,"161":144,"162":48,"163":143,"164":159,"165":15,"1    66":224,"167":217,"168":55,"169":254,"170":107,"171":8,"172":217,"173":160,"174":214,"175":210,"176":41,"177":248,"178":237,"179":2    34,"180":236,"181":24,"182":132,"183":38,"184":71,"185":182,"186":163,"187":50,"188":42,"189":17,"190":82,"191":30,"192":8,"193":42    ,"194":198,"195":229,"196":179,"197":125,"198":159,"199":180,"200":39,"201":156,"202":97,"203":237,"204":129,"205":151,"206":223,"2    07":254,"208":102,"209":113,"210":236,"211":24,"212":79,"213":32,"214":157,"215":189,"216":186,"217":217,"218":135,"219":187,"220":    167,"221":197,"222":60,"223":130,"224":81,"225":1,"226":123,"227":126,"228":57,"229":150,"230":111,"231":147,"232":10,"233":44,"234    ":109,"235":28,"236":32,"

**Comment by codingfishman** [comment]
Hi @mengde0077 
  你是不是说recorder.js中的`normalizeInfo`？
   `resBody`放置的是[Buffer](https://nodejs.org/api/buffer.html)对象，因此直接打印出来的话就不是期待中的字符串。 
    resbody不只有字符串的返回，也包括图片、音频等其他的返回，因此直接显示字符串是不合适的，需要进行区分。 你可以参考*recorder.js*中的[getDecodeBody](https://github.com/alibaba/anyproxy/blob/master/lib/recorder.js#L121), 来看一下如何处理。

  另外，可否也帮我们描述一下你将日志输入到file的场景是什么? 方便我们后续完善：）

 谢谢

**Comment by mengde0077** [comment]
感谢！ 是 recorder.js中的normalizeInfo ，那我如何进行区分呢，我只需要判断将原本是字符串的内容打印出来，请问改怎么改造呢 ？  我看在web页面上显示的 正常的，我想参考一下，打印到输出文件中！

我尝试过：
console.info(String.fromCharCode.apply(null,c));
但打印的数据不稳定！ 

Caught exception: RangeError: Maximum call stack size exceeded
    at normalizeInfo (/usr/local/lib/node_modules/.3.10.3@anyproxy/lib/recorder.js:198:35)

**Comment by mengde0077** [comment]
感谢，已经在 在  recorder.js中的getDecodeBody  中改造 打印出来了；  至于输出到 --file 中的 还不会！ 后面再学学nodejs,非常感谢！

**Comment by mengde0077** [comment]
你好！  已经按照 getDecodeBody   进行改造 ，可以输出到  --file 定义的文件中了！ 非常感谢！

**Comment by mengde0077** [comment]
recorder.js中增加 如下：
        if(singleRecord.mime='application/json'){
            singleRecord.resBody = info.resBody.toString();
        }else{
            singleRecord.resBody = "";
        }
