### ISSUE TITLE
手机端设置了代理，页面中有图片时，图片都不显示，WEB GUI也没有response

### ISSUE THREAD

**Issue by azdbaaaaaa** [alibaba/anyproxy#106]
#### Which platform are you running AnyProxy
**Windows**

#### The version of the AnyProxy
3.10.3

#### Your expected behavior of AnyProxy
手机端设置了代理，如果页面中有http的静态资源图片，能正常显示；web gui界面中也有response 图片预览

#### The actual behavior of AnyProxy
手机端设置了代理，如果页面中有http的静态资源图片，不能正常显示；web gui界面中也没有response 

#### The log of the error
received request to : img02.thumb.mmbang.info/0iyaya_group6_M02_02_E6_CggaDVgur1
WADVjeAAC8XNt1fUQ36.jpeg=220x220.jpeg
==>will forward to real server by proxy

request

GET /2iyaya_group6_M04_CB_3B_CggaDVb-KYmAVUc5AAAGLkEolxY002.jpg HTTP/1.1
host : img01.mmbang.info
mmbang-native-image-request : 1
accept-encoding : gzip, deflate
accept : image/webp,image/*;q=0.8
accept-language : zh-cn
connection : keep-alive
proxy-connection : keep-alive
user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17 mmbang/4.1.6
request body

**Comment by azdbaaaaaa** [comment]
调用replaceServerResDataAsync时，图片的情况下没有callback(serverResData)，close

**Comment by ottomao** [comment]
什么原因？

**Comment by azdbaaaaaa** [comment]
我上面写了，就是因为我调用了rule，其中replaceServerResDataAsync这个方法，在返回报文是图片的时候我没有把serverResData callback，或者toString()了
