### ISSUE TITLE
response header missing

### ISSUE THREAD

**Issue by Preetam007** [alibaba/anyproxy#108]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

  mac os x
#### The version of the AnyProxy

3.10.3

#### Your expected behavior of AnyProxy

response header are missing when request proxy through anyproxy ,
but when i am making a request through **request node module** then response headers are coming

**Comment by codingfishman** [comment]
Hi @Preetam007 
    Did all the headers are missing from AnyProxy or part of the headers? 
    If we can reproduce your case please let me know, thanks!
