### ISSUE TITLE
在 Mac 下安装 CA 证书的流程现在已不再适用

### ISSUE THREAD

**Issue by wellcheng** [alibaba/anyproxy#110]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac

#### The version of the AnyProxy

3.10.3

#### The actual behavior of AnyProxy

你们的文档中，关于 Mac 端安装证书的部分已经不再适用，请更新

**Comment by ottomao** [comment]
感谢指正。
4.x版本的文档已经做了部分更新： https://github.com/alibaba/anyproxy/tree/4.x
