### ISSUE TITLE
replaceRequestData 如何修改 data 的值？

### ISSUE THREAD

**Issue by wangyunshuai** [alibaba/anyproxy#111]
想要修改 request body 的值，但是不知道该用什么方法处理。
```
    replaceRequestData: function(req,data){
        console.log(data)
        return data;
    },

输出：
<Buffer 73 3d 6f 55 30 4d 79 36 78 50 37 6d 6a 68 4f 36 48 55 64 63 53 42 30 39 59 31 48 7a 7a 71 75 31 64 4a 26 66 3d 61 6e 64 72 6f 69 64 26 74 6f 6b 65 6e ... >
```
如何修改 data 的值呢？

### 解决方法：
通过看源码，理解实现方法，data 传入的就是转为 string 的 request body。

直接在里面对 data 进行重新赋值，格式：
```
    replaceRequestData: function(req,data){
        data = "limit=2&offset=0&get_total=1&type=wiki";
        return data;
    },
```
## 疑问：但是 console.log(data) 输出为什么是 Buffer 呢？
Mac： 10.12.1
Anyproxy：3.10.3

**Comment by codingfishman** [comment]
Hi @wangyunshuai 
   `replaceRequestData`接收的参数是没有经过toString的一个buffer对象，所以console.log打印出来的仍然是buffer。
    如果你需要对其进行更改，且确定他实际上是string的时候，可以通过 `data.toString()`,来获取string对象，返回时将其再次转换为Buffer。
