### ISSUE TITLE
没有自动设置全局代理

### ISSUE THREAD

**Issue by enml** [alibaba/anyproxy#112]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

windows 7
#### The version of the AnyProxy

anyproxy@3.10.3

#### Your expected behavior of AnyProxy

启动anyproxy后，自动设置全局代理。
#### The actual behavior of AnyProxy

需要手动设置IE代理

**Comment by codingfishman** [comment]
@enml 
   如果需要作为全局代理启动，可以指定参数 `-o`， 即 `anyproxy -o`
