### ISSUE TITLE
Map Local Rule 如何匹配

### ISSUE THREAD

**Issue by xyyjk** [alibaba/anyproxy#115]
是否支持正则或glob匹配

**Comment by codingfishman** [comment]
@xyyjk 
   目前只是`indexOf`的字符串匹配，如果需要更多的控制，可以通过定制rule：`shouldUseLocalResponse`来实现, 参考：[这里](https://github.com/alibaba/anyproxy/blob/master/rule_sample/rule_use_local_data.js)
