### ISSUE TITLE
AnyProxy不能在同一台机器开启多个实例模拟不同弱网络环境？

### ISSUE THREAD

**Issue by lixinkun** [alibaba/anyproxy#118]
首先以命令anyproxy开启一个anyproxy实例，成功之后，再次输入命令anyproxy -w 2222 -p 1111打开另外一个anyproxy实例，有以下错误提示：

![1](https://cloud.githubusercontent.com/assets/17489980/21299717/41dc9286-c5d9-11e6-9344-bc2f10fea3e3.png)

考虑可能是socket端口冲突，然后尝试以第三方模块的方式接入，并自定义socket端口，代码如下：
![2](https://cloud.githubusercontent.com/assets/17489980/21299756/95116f76-c5d9-11e6-8bef-b8fb7064bca5.png)

anyproxy开启没有报错，但是第二个开启的实例网络无法连接，求问如何能在同一台机器开启多个实例呢？

**Comment by codingfishman** [comment]
Hi @lixinkun 
   请帮忙确认第二个实例*网络无法连接”的情形，如果关闭throttle是否现象依旧？第二个实例的AnyProxy自己在接收到请求的时候，有无日志被打印出来，比如接收到的请求和返回信息有没有日志信息呢？

**Comment by lixinkun** [comment]
1、关闭throttle现象依旧
2、anyproxy开启没有报错，但是GUI web页面无法打开，显示网络无法连接，代理也无法接收请求，终端没有日志打印

**Comment by codingfishman** [comment]
Hi @lixinkun 

我不能重现你的问题，如下代码可以启动两个示例，且localhost:2222和localhost:8002均可访问：

```js
const AnyProxy = require('anyproxy');

const DEFAULT_OPTIONS = {
    type: "http",
    port: 8001,
    hostname: "localhost",
    dbFile: null,  
    webPort: 8002,  
    socketPort: 8003,  
    throttle: 10000,    
    disableWebInterface: false, 
    setAsGlobalProxy: false, 
    interceptHttps: true, 
    silent: false 
};


const DEFAULT_OPTIONS2 = {
    type: "http",
    port: 1111,
    hostname: "localhost",
    dbFile: null, 
    webPort: 2222, 
    socketPort: 3333,  
    throttle: 10000,   
    disableWebInterface: false, 
    setAsGlobalProxy: false, 
    interceptHttps: true, 
    silent: false
};

new AnyProxy.proxyServer(DEFAULT_OPTIONS);
new AnyProxy.proxyServer(DEFAULT_OPTIONS2);
```

这段代码在你的机器上可否运行？

**Comment by ottomao** [comment]
命令行启动时，是AnyProxy内部的websocket端口冲突了。

升级到v3.10.4，使用 -e 参数指定一个websocket端口就行。
