### ISSUE TITLE
Websockets not working❗️

### ISSUE THREAD

**Issue by k1tzu** [alibaba/anyproxy#119]
Logs just saying:
```
received https CONNECT request echo.websocket.org
==>will bypass the man-in-the-middle proxy
```

Try it for yourself http://www.websocket.org/echo.html or http://emojitracker.com/

Linux
anyproxy v3.10.3

**Comment by codingfishman** [comment]
Hi @k1tzu ,
   Did you turn on the HTTPS interception flag with `anyproxy -i` ?

**Comment by k1tzu** [comment]
No of cause not. HTTPS interception warns users of untrusted connection which is not ok for my needs. So https interception is turned off for sure.

**Comment by k1tzu** [comment]
Fixed by replacing in lib/requestHandler.js 
```339	                proxyPort = (targetPort == 80)? 443 : targetPort;```
with
```339	                proxyPort = targetPort;```
