### ISSUE TITLE
请问anyproxy能不能跑在ios上

### ISSUE THREAD

**Issue by nb1988** [alibaba/anyproxy#122]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

想在iOS上安装anyproxy,请问这个有没有可行性，如果可以需要安装哪些东西 谢谢

**Comment by codingfishman** [comment]
@nb1988 
   你是指在iOS上挂代理到AnyProxy，还是说AnyProxy本身以一个app的形式安装到iOS？

   AnyProxy支持将iOS的请求代理到电脑上，你可以在iOS的网络中配置电脑端AnyProxy的端口（默认8001），如果你是要代理HTTPS请求，可从AnyProxy的web端扫码安装证书并信任即可。

**Comment by nb1988** [comment]
我是想把anyproxy以插件的形式装到iphone上，但是目前支持iphone的node版本太低  请问有别的替代方式么？

**Comment by ottomao** [comment]
短期内没准备支持这种玩儿法 :(
