### ISSUE TITLE
我启动的时候报错

### ISSUE THREAD

**Issue by zhn3431223** [alibaba/anyproxy#129]
Plese fill the template when you reporting a new issue, thanks!

![image](https://cloud.githubusercontent.com/assets/25398776/22394665/4166aeb6-e561-11e6-8a8a-d529b92d7d64.png)

#### Which platform are you running AnyProxy

我用的是 Windows
#### The version of the AnyProxy

我用的是master版本的

#### The log of the error

![image](https://cloud.githubusercontent.com/assets/25398776/22394673/58e33fc8-e561-11e6-9f9b-ce8b34b7bff5.png)

**Comment by codingfishman** [comment]
Hi @zhn3431223 
   本机的Nodejs版本是不是在4.3.2以下？ 4.3.2以下的nodejs版本不支持箭头函数，可以参考http://node.green/。
   后面我们也在进行代码编译的ES5化，不过在此之前，只好先升级nodejs的版本，抱歉

**Comment by ottomao** [comment]
麻烦升级一下nodejs的版本吧。
