### ISSUE TITLE
一系列需求和api问题

### ISSUE THREAD

**Issue by hktalent** [alibaba/anyproxy#134]
1、我要在哪儿修改user-agent，达到伪装的效果
2、我需要将所有的请求存储到数据库，接口api是哪个啊？
3、我需要对输出进行注入自己的js代码，或者<script src...></script>这样的代码，怎么处理啊？或者api是什么
4、我需要全套的接口api，方便定制开发渗透测试，或者web测试系统
谢谢

**Comment by ottomao** [comment]
当前版本的rule文档： https://github.com/alibaba/anyproxy/wiki/What-is-rule-file-and-how-to-write-one

4.x版正在beta中，有中文文档和样例：https://github.com/alibaba/anyproxy/tree/4.x
