### ISSUE TITLE
代理的时候，如何处理 err with request :Error: read ECONNRESET

### ISSUE THREAD

**Issue by lijinma** [alibaba/anyproxy#136]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

3.10.3

#### Your expected behavior of AnyProxy

遇到请求出错，我想做一些操作，怎么抓取上面的错误？

#### The actual behavior of AnyProxy

报错：err with request :Error: read ECONNRESET
我无能为力，做不了什么。

**Comment by codingfishman** [comment]
Hi @lijinma 
   目前确实没有把错误直接抛到外面的接口方法，抱歉。
   你提到想做一些操作，可否分享一下是哪些操作？我们可以一起改进！

**Comment by lijinma** [comment]
@codingfishman 谢谢你的回复，我的意思是：我本来打算遇到这样的错误做一个刷新操作之类的。

那我在哪里可以抓住这样的错误吗？多谢

**Comment by ottomao** [comment]
暂时没有接口可以抓。让我们想想怎么搞，这确实是个需求，得放在4.x的版本里。

**Comment by lijinma** [comment]
@ottomao 多谢，期待解决，我的项目很依赖这个功能。

**Comment by ottomao** [comment]
准备在rule里开一个onError方法。

不过要注意，这个错误捕获发生在代理服务器里，你期望的“刷新操作”在浏览器，这两端的连通性得你自己想办法。

**Comment by lijinma** [comment]
@ottomao 恩，明白，我想办法通知浏览器。

**Comment by ottomao** [comment]
4.x beta版已经开放这个监听了，文档： http://anyproxy.io/4.x/#onconnecterror

**Comment by lijinma** [comment]
@ottomao 特别感谢。
