### ISSUE TITLE
使用rule文件返回的时候 中文乱码

### ISSUE THREAD

**Issue by zlulan** [alibaba/anyproxy#140]
在Ubuntu14.04上运行
#### The version of the AnyProxy
anyproxy 3.1.0

#### Your expected behavior of AnyProxy
返回正确的响应信息

#### The actual behavior of AnyProxy
响应信息中文乱码

#### The log of the error
rulue文件：

module.exports = {

    summary:function(){
        return "replace response data by local response now";
    },

    //mark if use local response
    shouldUseLocalResponse : function(req,reqBody){
        //if(/mock/.test(req.url)){   //被mock接口判断选择
            req.replaceLocalFile = 0;
            return true;
        //}

      //  return false;
    },

    dealLocalResponse : function(req,reqBody,callback){
        if(req.replaceLocalFile==0){
            var url=req.url.replace('/','');

            var post_data = {  
                   'mockUrl':url,
                   'mockHeaders':JSON.stringify(req.headers),
                   'mockMethod':req.method,
                   'mockParam':reqBody.toString()
                           };//这是需要提交的数据  
            var content = JSON.stringify(post_data);  
            var options = {  
                 hostname: 'tcservice.17usoft.com', 
                 port: 80,  
                 path: '/zebra/getResponse',  
                 method: 'POST',  
                 headers: {  
                       "content-Type": "application/json;charset=utf-8" 
                                }  
                         };  
           var http = require('http');
           var Mock = require('mockjs')
           var requ = http.request(options, function (response) { 
              response.setEncoding('utf-8');  
             //res.pipe(response); 
             response.on('data', function (chunk) { 
                    //var body_data=Mock.mock(JSON.parse(chunk));    
                   console.log(JSON.stringify(chunk,null,2));
                    callback(response.statusCode,options.headers,JSON.stringify(body_data,null,2));
                   }); 
              });  
             // write data to request body  
            requ.write(content);  
            requ.end(); 
        }
    }
};

**Comment by ottomao** [comment]
我这里貌似请求不到tcservice.17usoft.com的服务器。

检查下 body_data 的编码，是不是Utf8，你的返回头里写着是 charset=utf-8 的

**Comment by zlulan** [comment]
我试试 不过用console.log打印信息中文也是乱码 在windows里面运行是正常的

**Comment by codingfishman** [comment]
Hi @zlulan 
   `response.on('data')`还不是一个完整的response，而且还是buffer类型的数据，不是直接的string，你可以尝试一下这种：
   
```js
   var bodyDataChunks=[];
    response.on('data', function (chunk) {
       bodyDataChunks.push(chunk);
    });

    response.on('end', function () {
       var bodyData = Buffer.concat(bodyDataChunks).toString();
       // 其他逻辑
    }
  ```

**Comment by zlulan** [comment]
问题解决了是springmvc ajax请求乱码导致
