### ISSUE TITLE
Change the request URL?

### ISSUE THREAD

**Issue by Jonovono** [alibaba/anyproxy#142]
Hi. I am trying to change the request URL but I am not sure how.

This is what I have tried so far: 

    replaceRequestOption: function(req, option) {
      var newoption = option
      newoption.path = option.path + '?testing=this'
        return newoption

    },

It seems it affects the page that loads, but the added path does not show up in the URL. Any ideas?

**Comment by codingfishman** [comment]
Hi @Jonovono 
    So you want to change the URL in Browser location as well?
    AnyProxy will request the new URL, and return its' content to browser, but will not modify the original URL in Browser. If you do want to change the URL ,you may return a 302 with the target URl.

**Comment by Jonovono** [comment]
Thanks @codingfishman, makes sense!
