### ISSUE TITLE
Firefox showing "insecure connection"

### ISSUE THREAD

**Issue by Jonovono** [alibaba/anyproxy#144]
Hi. I have the cert generated by anyproxy trusted in keychain. I am intercepting requests sucessfully on Chrome and Safari. However, in Firefox I get the error.  Any idea?
```

Your connection is not secure

The owner of reddit.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

reddit.com uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. Error code: SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by ottomao** [comment]
Maybe Firefox does not use the cert config in your system. I got this document from google , about how to install root certificate : https://wiki.wmtransfer.com/projects/webmoney/wiki/Installing_root_certificate_in_Mozilla_Firefox

hope that may help you.
