### ISSUE TITLE
匹配路由规则后判断是否走代理服务

### ISSUE THREAD

**Issue by plusor** [alibaba/anyproxy#145]
这个功能目前有吗?

- 在下载的时候, 代理服务器需要先下载完后才发送给客户端.  如果文件比较大的话会很慢

**Comment by liontree** [comment]
@plusor   https://github.com/alibaba/anyproxy/blob/master/rule_sample/rule_replace_response_data.js
这个API能满足你的要求么

**Comment by plusor** [comment]
@liontree 谢谢回复。 这不还是代理服务器去发起数据请求然后给客户端吗？
我的意思是有没有一种办法客户端发起一个请求，代理服务器直接让该请求从请求的目标端直接返回数据到客户端。

**Comment by ottomao** [comment]
这个不是在Proxy层控制的，到了代理的请求就一定会走代理。
看下Pac文件：https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file
