### ISSUE TITLE
代理https请求出错

### ISSUE THREAD

**Issue by gooyie** [alibaba/anyproxy#147]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

window 10
#### The version of the AnyProxy

4.0

#### Your expected behavior of AnyProxy

生成的证书生成可用于最新的浏览器

#### 在最新的Chrome开发版或Chromium浏览器代理https请求出现：

> #### 您的连接不是私密连接
>
> 攻击者可能会试图从github.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

xx-net也出现了类似问题 XX-net/XX-Net#5106，已确定是证书问题。

**Comment by codingfishman** [comment]
Hi @gooyie 
   看报错提示确实是证书没有被信任，请问AnyProxy生成的根证书，是否已经被安装在了“root根证书”这一个证书栏目下面？

**Comment by gooyie** [comment]
@codingfishman 
证书在“受信任的根证书颁分机构”下

**Comment by ottomao** [comment]
看Issue和这个PR（https://github.com/XX-net/XX-Net/pull/5120），似乎是证书的 `subjectAltName` 字段有要求，但google一下好像又没太多讨论....?

我们看看，如果成本不高，就配合加一个。

**Comment by ottomao** [comment]
搞定了，[node-easy-cert](https://github.com/ottomao/node-easy-cert) 发了个新版本，加上了 `subjectAltName `

重装一下AnyProxy，删了原来的证书重启，就OK了。

**Comment by gooyie** [comment]
重装4.0.0-beta5版生成的证书没问题了。
