### ISSUE TITLE
能否增加支持存储一次请求的request response的body和Header的内容到文件中

### ISSUE THREAD

**Issue by liontree** [alibaba/anyproxy#15]
Hi, @ottomao  anyproxy目前只支持存储request的内容到文件中（希望我的理解是正确的），能否增加个可选项，支持可以存储某次请求的request和response的body内容&Header内容到文件中呢？因为有时候仅看打印出来的结果是不够的，可能还会写些脚本来分析一次请求，所以提出了这个提议：-）您看下实现这个功能ok么

Many thanks~

**Comment by ottomao** [comment]
这个功能已经有实现了，是基于anyproxy二次开发完成的。
Ref : https://github.com/ottomao/TrafficRecorder

**Comment by liontree** [comment]
@ottomao  在readme里面看到这个工具了，以为也是录制request的，实在抱歉:-(  刚试了下TrafficRecorder，nice~ 是我要的功能
