### ISSUE TITLE
打开web页面的时候总是提示error happened when setup websocket

### ISSUE THREAD

**Issue by wjrebornd** [alibaba/anyproxy#150]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

windows
#### The version of the AnyProxy

4.0
#### Your expected behavior of AnyProxy

正常打开web页面，不会报错
#### The actual behavior of AnyProxy

每次打开http://127.0.0.1:8002 这个web页面，都会在顶部提示error happened when setup websocket 这个报错

**Comment by codingfishman** [comment]
Hi @wjrebornd 
    我们已发行这个问题并在处理，抱歉。
    目前，请问你是直接用系统的代理，还是用swtichOmega这种工具？ 你可以在设置中去除对”localhost"的代理，应该就可以使用了。

**Comment by ottomao** [comment]
感谢反馈，这个bug已经在beta6版本发布解决了，麻烦重新安装下
```
npm i -g anyproxy@beta
```

**Comment by umbrellax** [comment]
> 感谢反馈，这个bug已经在beta6版本发布解决了，麻烦重新安装下
> 
> ```
> npm i -g anyproxy@beta
> ```

你好 我也出现了同样的问题  https://github.com/elecV2/elecV2P-dei/issues/28
