### ISSUE TITLE
打开gui界面一直在loading，request没反应

### ISSUE THREAD

**Issue by gwl002** [alibaba/anyproxy#151]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

mac

#### The version of the AnyProxy

4.x

#### Your expected behavior of AnyProxy

显示浏览器发送的请求和返回response

#### The actual behavior of AnyProxy

界面没有任何反应

**Comment by codingfishman** [comment]
HI @gwl002 
   是否设置了浏览器的代理插件(例如[SwitchOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif))，使其代理到AnyProxy？

**Comment by gwl002** [comment]
@Nick 原来是我没把代理设成127.0.0.1:8001，我以为anyproxy会自动监控全局网络请求的。readme.md中应该详细说明的，至少我前面并没有看懂那句话。
