### ISSUE TITLE
Async call to shouldUseLocalResponse() ?

### ISSUE THREAD

**Issue by a4i** [alibaba/anyproxy#153]
#### Which platform are you running AnyProxy
Linux
#### The version of the AnyProxy
3.10.4

#### Your expected behavior of AnyProxy
I need to fetch cache data from Redis if present. To do so I need to asyncronously call Redis to check if data is present, then return true or false from shouldUseLocalResponse.

For now I added a step in requestHandler, that set a req.header if Redis is to be fetched, and use this flag in shouldUseLocalResponse.

    async.series([
        fetchReqData,
        PREPARE_SHOULD_USE_LOCAL
        routeReq
    ],function(){

Any way to support this behaviour ? 

#### The actual behavior of AnyProxy
Only sync calls are allowed in shouldUseLocalResponse

Regards

**Comment by ottomao** [comment]
Promise will be supported in the coming AnyProxy 4.x.

Here is a preview doc in Chinese : http://anyproxy.io/4.x/#beforesendrequest . We will release an English version soon, maybe a week or two.

**Comment by ottomao** [comment]
Hi, AnyProxy 4.x document in English is released http://anyproxy.io/4.x/

**Comment by a4i** [comment]
thanks for this job !
