### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by zaaack** [alibaba/anyproxy#154]
1. export request & response  to  gist 
2. export curl command

**Comment by ottomao** [comment]
Hi,
What's the *curl command* for ? To replay a request ?

**Comment by zaaack** [comment]
@ottomao Yes, communicate with work mates, easy to replay the request with same environment.

**Comment by zaaack** [comment]
And  I think No.2 is more valuable than No.1.

**Comment by zaaack** [comment]
Some code might help: https://github.com/swagger-api/swagger-ui/blob/3ed8efe7360d62745c256d2f68fd30bbad7a58a2/src/core/curlify.js

**Comment by zaaack** [comment]
@ottomao Here is my PR: https://github.com/alibaba/anyproxy/issues/155 Plz review, thx

**Comment by ottomao** [comment]
Great feature ! Just get merged and released to 4.0@beta9.

**Comment by ottomao** [comment]
I meant the *curl feature* has been merged. The *export request & response to gist* is not a high-priority feature.

**Comment by zaaack** [comment]
@oboolean Totally agree.
