### ISSUE TITLE
4.0 beta8 在局域网中其他机器访问web出现error happened when setup websocket

### ISSUE THREAD

**Issue by fjnphsq** [alibaba/anyproxy#156]
#### 我在ubuntu16.10上安装，启动后使用了另一台机器访问anyproxy的web页面，浏览器提示error happened when setup websocket，本机访问并不会出错，控制台的错误为：

`WebSocket connection to 'ws://localhost:19437/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

看了下源码，自己把这里改成了我安装anyproxy的主机的地址，这里是否可以考虑加个设置？还是说在设计的时候就没有打算让其他机器访问web界面？

**Comment by ottomao** [comment]
@codingfishman

**Comment by ottomao** [comment]
Fixed in AnyProxy 4.0@beta9.
