### ISSUE TITLE
百度的https CONNECT无法访问

### ISSUE THREAD

**Issue by hktalent** [alibaba/anyproxy#157]
使用代理后
百度的https CONNECT无法访问
访问的页面：
https://www.baidu.com
received https CONNECT request www.baidu.com
==>will forward to local https server

启动参数
anyproxy --port 8001 --intercept --rule ./rule_sample/rule_replace_request_option.js

**Comment by zhulinpinyu** [comment]
遇到同样的问题，凡是https的请求均无法访问。(anyproxy 3 或 4 均测试过， 测试设备：iOS 10.3)

**Comment by hktalent** [comment]
@zhulinpinyu 我建立了分支，自己发展去了，哈哈哈

**Comment by ottomao** [comment]
我们查下

**Comment by ottomao** [comment]
http://anyproxy.io/4.x/cn.html#ios->=-10.3信任ca证书

检查下是不是iOS 10.3的设置没做对，10.3开始多了一步。

**Comment by hktalent** [comment]
@ottomao 
@zhulinpinyu 
http代理和https要启动两个进程、不同的端口
才可以
也就是使用参数
anyproxy --port 8001 --intercept -t https
才能正常访问https

**Comment by ottomao** [comment]
是不是原来没配https over http的代理？应该不用配置 -t https
