### ISSUE TITLE
Stuck when open response panel of woff request

### ISSUE THREAD

**Issue by zaaack** [alibaba/anyproxy#159]
Open a big binary file would take a lot of time and anyproxy 4.0 treat it like strings, could just show a linked placeholder?

**Comment by ottomao** [comment]
What's your version of AnyProxy ? How to reproduce this issue ?

In the recent beta release, AnyProxy would skip dealing response >= 20MB and flush to client directly.

**Comment by zaaack** [comment]
@ottomao beta release, click on an woff file request, not big as >= 20MB, but still could be stuck.

The request: https://at.alicdn.com/t/font_0qcp222wvwijm7vi.woff

And I don't think treating binary file like string and show on html is a good idea, you can just put some placeholder with link.

**Comment by ottomao** [comment]
Has been optimized in beta10.
