### ISSUE TITLE
 it supposes page cache？thx ~

### ISSUE THREAD

**Issue by skyhiter** [alibaba/anyproxy#16]

**Comment by ottomao** [comment]
What do you mean by page cache ? Cache http response ?
AnyProxy does not suppoort that natively. You may implement this feature by writing your own rule file.
Ref: https://github.com/alibaba/anyproxy/wiki/What-is-rule-file-and-how-to-write-one

**Comment by codingfishman** [comment]
closed, will be reopen if further discussion needed
