### ISSUE TITLE
iOS 10.3之后信任证书需要多一步操作，建议更新文档。

### ISSUE THREAD

**Issue by pandazki** [alibaba/anyproxy#160]
General -> About -> Certificate Trust Settings 需要允许完全信任证书，建议添加到文档中。

**Comment by ottomao** [comment]
恩 正在更新 感谢提醒！

**Comment by ottomao** [comment]
http://anyproxy.io/4.x/cn.html#ios->=-10.3信任ca证书

4.x文档已经添加。
