### ISSUE TITLE
文档中拼写错误

### ISSUE THREAD

**Issue by pandazki** [alibaba/anyproxy#161]
4.x 文档中有两处 responseDetail.reponse ，应为 responseDetail.response。

**Comment by ottomao** [comment]
感谢反馈，已经修复并发布了。

**Comment by PhilipDing** [comment]
貌似还存在吧。。。今天就被这个坑了....
url: http://anyproxy.io/cn.html#beforesendresponse

![spelling_error](https://user-images.githubusercontent.com/4457568/27769132-c22a5a34-5f55-11e7-92fb-879879fc0ec3.jpg)

**Comment by ottomao** [comment]
万分抱歉，改了文档源之后没推送到站点上来。
这下是真修复了....
