### ISSUE TITLE
请求方法显示的不是get和post而是connect的，是不是就是https啊。

### ISSUE THREAD

**Issue by gwl002** [alibaba/anyproxy#162]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

mac

#### The version of the AnyProxy

3.10.4

#### Your expected behavior of AnyProxy

明明有某些请求我没有找到的，显示的都是connect，请求内容什么的都找不到，是不是要用https

**Comment by ottomao** [comment]
https请求经过http proxy的时候，就是CONNECT，通过connect建立一个连接通路，然后继续通信。

如果要解析请求内容，得打开 --intercept 参数，然后安装证书，再访问，AnyProxy会做解析处理。
