### ISSUE TITLE
如何写反向代理规则?

### ISSUE THREAD

**Issue by dishuostec** [alibaba/anyproxy#17]
我想让所有访问foo.com的请求转向访问指定的ip，但是hostname不变。
在fiddler中可以用下面的设置
···
oSession.bypassGateway = true;
oSession["x-overrideHost"] = x.x.x.x;
```

**Comment by ottomao** [comment]
https://github.com/alibaba/anyproxy/blob/master/rule_sample/rule_reverse_proxy.js
新增加的rule，可以参考下。

**Comment by dishuostec** [comment]
能用了，非常感谢！！
