### ISSUE TITLE
anyproxy下载类链接的response字段的conten-length返回为0

### ISSUE THREAD

**Issue by Solomo-vip** [alibaba/anyproxy#172]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

mac

#### The version of the AnyProxy

3.10.3

#### Your expected behavior of AnyProxy

遇到下载类的请求，返回的response的header中能够携带content-length

#### The actual behavior of AnyProxy

返回的content-length为0

**Comment by ottomao** [comment]
试下 AnyProxy 4.0 beta版，看下问题是不是还有

`npm i -g anyproxy@beta`

**Comment by Solomo-vip** [comment]
您好，升级到4.0版本，发现
![image](https://cloud.githubusercontent.com/assets/12445430/25260813/278bc2ae-2681-11e7-8df2-5c84e81ce07c.png)
这里去取文件的大小还是为-1的

**Comment by codingfishman** [comment]
@Solomo-vip 
  我们正在完善这字段返回，目前的response都是`transfer-encoding:chunked`,是不是会使得你取得的值不对？
  不过针对下载类的请求，很多种情形下都会是chunked的response，AnyProxy默认也会保留chunked的返回，除非在自定义的rule中手动设置了`content-length` header字段。

**Comment by codingfishman** [comment]
@Solomo-vip   https://github.com/alibaba/anyproxy/issues/238  你看看可否使用
