### ISSUE TITLE
4.0版本对原来的--file参数移除了？

### ISSUE THREAD

**Issue by Solomo-vip** [alibaba/anyproxy#173]
Plese fill the template when you reporting a new issue, thanks!

升级到4.0版本之后发现原有的--file参数不可用了，请问4.0版本是移除了这个功能吗？
#### Which platform are you running AnyProxy

mac
#### The version of the AnyProxy

4.0 beta

#### Your expected behavior of AnyProxy

能够支持--file的功能

**Comment by Solomo-vip** [comment]
4.0.0-beta12

**Comment by ottomao** [comment]
原先的 --file 不过是nedb的磁盘文件，很难解析，这块正在重构， 上线前会回来的，不过文件格式肯定全都变了。
