### ISSUE TITLE
拦截不到https的请求

### ISSUE THREAD

**Issue by lishufen** [alibaba/anyproxy#174]
通过代理https的页面可以进去了，但是在web端看不到拦截的请求，http是可以看到的

**Comment by ottomao** [comment]
AnyProxy的版本 、 用什么东西配的代理、配置截图，都附上。

**Comment by lishufen** [comment]
发现是ios10.3以上的版本不行，证书不被信任

**Comment by codingfishman** [comment]
@lishufen 
  升级到iOS 10.3以后，请检查 “设置 -> 通用 -> 关于本机 -> 证书信任设置” 中的AnyProxy证书是否已信任
