### ISSUE TITLE
https 接口不能请求，CONNECT方法返回200，不发送get请求

### ISSUE THREAD

**Issue by doudoufei** [alibaba/anyproxy#175]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

mac
#### The version of the AnyProxy

3.10.3

#### Your expected behavior of AnyProxy

正常抓取https的请求
#### The actual behavior of AnyProxy

发送请求之后，CONNECT方法返回200之后，不再继续发送get请求。一部分app可以正常使用，一部分app的https请求有此问题。

![image](https://cloud.githubusercontent.com/assets/13443827/25519436/60ee491e-2c2a-11e7-8630-0ea386ff1be2.png)
#### The log of
 the error

**Comment by doudoufei** [comment]
已解决，非anyproxy问题。

**Comment by stormtea123** [comment]
@doudoufei  什么原因导致的？我也遇到了同样的问题
