### ISSUE TITLE
[v4] chrome 60 下WebGUI白屏

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/anyproxy#177]
OSX Chrome dev latest 60

![image](https://cloud.githubusercontent.com/assets/3922719/25752909/4bfb9882-31ec-11e7-9a84-3ca9df6007eb.png)

白屏，v4 beta11

**Comment by tcrct** [comment]
同样的问题，请问解决了吗？

**Comment by wssgcg1213** [comment]
not yet..

**Comment by codingfishman** [comment]
@tcrct @wssgcg1213  请升级到最新beta版试试

**Comment by codingfishman** [comment]
关闭issue，已在beta16里修复
