### ISSUE TITLE
post请求.gif图片时，抓取不到图片

### ISSUE THREAD

**Issue by yejingda** [alibaba/anyproxy#179]
Plese fill the template when you reporting a new issue, thanks!
 请在提交Issue的同时，附带如下信息，方便我们定位，谢谢

#### Which platform are you running AnyProxy
 Mac，Windows

#### The version of the AnyProxy
 4.X 

#### Your expected behavior of AnyProxy
能够在response body 看到

#### The actual behavior of AnyProxy
一个断裂的图片

#### The log of the error
request

GET /tmpstats.gif?cardrctp=1&rank=4&pu=2209732859&mkey=8e48946f144759d86a50075555fd5862&position=1&cardbatch=1&block=504091_0&usract=1&cardid=R:206085512&ppuid=2209732859&bkt=m_seal30_main&rtype=1,1,2,2,0,0&from_type=1&p0pstn=0,1&tag=&v=8.4&u=ABD48A75-6BA5-4360-948F-2AC1B5D9FBC4&type=showlizard20130613&albumlist=1000000000408&cid=2,6,2,6,0,0&platform=32&event_id=8505d20a0a0a0a8fecf713027a44fbcc&uid=ABD48A75-6BA5-4360-948F-2AC1B5D9FBC4&mod=cn_s&spid=&area=m_seal&vidlist=204759601,673571900,206264101,674282300,1000000000408,1000000000409 HTTP/1.1
host : msg.71.am
proxy-connection : keep-alive
t : 455805668
user-agent : QIYIVideo/8.4 (iOS;com.qiyi.iphone;iOS10.3.1;iPhone8,1) Corejar
sign : 5fd2909ca80a66aefd2e7326ef740430
connection : keep-alive
content-length : 0
request body

response header

HTTP/1.1 200
server : nginx/1.8.0
date : Mon, 08 May 2017 08:12:17 GMT
content-type : image/gif
connection : keep-alive
response body

**Comment by codingfishman** [comment]
@yejingda 
   还请帮忙提供，当图片断裂时，其地址是怎么样的？

**Comment by yejingda** [comment]
@codingfishman 
下面是我随便的一个.gif请求的详细信息。麻烦看一下咯，谢谢了～
 我抓包测试用的是《爱奇艺》，也许你用一下爱奇艺就知道了。
request
POST /scp2.gif HTTP/1.1
host : msga.cupid.iqiyi.com
content-type : application/x-www-form-urlencoded
proxy-connection : close
cookie : QC005=61ce9ee33f1c6052f625a44bbcb5af18; P00002=%7B%22uid%22%3A%222209732859%22%2C%22user_name%22%3A%2215018422231%22%2C%22email%22%3A%22%22%2C%22nickname%22%3A%22dada_qq1478%22%2C%22pru%22%3A2209732859%2C%22type%22%3A11%2C%22pnickname%22%3A%22dada_qq1478%22%7D; P111114=1493992917; P00004=2030602315.1493992899.4680bdee11
user-agent : ç±å¥èº 8.4 rv:20170504220800 (iPhone; iOS 10.3.1; zh_CN)
content-length : 818
connection : close
request body

scp2.gif=%7B%22av%22:%223.9.008%22,%22c%22:%2230001%22,%22d%22:%2254000%22,%22qxt%22:%5B%7B%22rid%22:%22ab8f6cbedddadf15997f7bb1578203bb%22,%22ec%22:%22%22,%22rd%22:%2288%22,%22ai%22:%220%7C%7C71000028%7C%7C81000019%7C%7C54000689878%7C%7Cmobile_flow%22,%22rc%22:%22-1%22,%22t%22:%5B%22s%22%5D%7D%5D,%22vv%22:%228.4%22,%22s%22:%221494815536095%22,%22e%22:%22ab8f6cbedddadf15997f7bb1578203bb%22,%22g%22:%221%22,%22u%22:%22ABD48A75-6BA5-4360-948F-2AC1B5D9FBC4%22,%22h%22:%220%22,%22v%22:%22%22,%22i%22:%22ABD48A75-6BA5-4360-948F-2AC1B5D9FBC4%22,%22nw%22:1,%22qxlc%22:%2286440113%22,%22ol%22:%220%22,%22y%22:%22qc_100001_100070%22,%22l%22:%22NTguMjU0LjE3Mi40OQ==%22,%22mk%22:%228e48946f144759d86a50075555fd5862%22,%22a%22:%22ABD48A75-6BA5-4360-948F-2AC1B5D9FBC4%22,%22o%22:%22edd8b50c5b369de139cb3b8c749ff8f3a9d89a7d%22%7D

response header

HTTP/1.1 200
server : nginx/1.8.0
date : Mon, 15 May 2017 02:32:21 GMT
content-type : image/gif
transfer-encoding : chunked
connection : close
response body


￼

**Comment by codingfishman** [comment]
@yejingda 
  我试了一下爱奇艺，发现部分gif图片断裂，但是这些图片链接本身直接访问的话，也确实是没有图片的。
  - http://www.qiyipic.com/common/fix/common/loading-kiwi.gif ， 正常抓取正常显示
  - http://msg.iqiyi.com/vpb.gif?flag=rptusr&newusr=0&suid=eb1c478defac274cc0e20f920501979b&tn=0.5524441571906209 ， 图片断裂，但是直接访问也确实不是一个完整的gif。这个请求可能只是做消息同步等作用，并不是真的gif返回，因此请再确认断裂图片的url，直接访问是否正常。

**Comment by codingfishman** [comment]
关闭issue，如果有更新请再重新打开

**Comment by ccOnTheWay** [comment]
Hi， 
我们在基于anyproxy二次开发，自定义解析一些抓包数据，
 一些埋点数据通过 post 请求一个gif图，请求body携带 埋点信息，然而 anyproxy未抓取到该埋点访问
你可以尝试下抓改网站：https://www.sensorsdata.cn/
这个埋点上报请求未被抓取到 https://sensorswww.datasink.sensorsdata.cn/sa.gif?token=6b551cb59b1c1973
