### ISSUE TITLE
4.0版本不能截获https请求的内容

### ISSUE THREAD

**Issue by chengwz** [alibaba/anyproxy#180]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
windows7.0
Node7.10

#### The version of the AnyProxy
Version 4.0.0-beta12

#### Your expected behavior of AnyProxy
命令行中指定 -i 参数时，能够在代理https请求时，在Anyproxy Web UI上查看到https的内容。

#### The actual behavior of AnyProxy
象下面mp.weixin.qq.com/mp/getmasssendmsg请求是https请求，在Anyproxy Web UI上看到的是乱码。而且method这一列也不显示 “锁” 的标记。似乎命令行中的 -i 参数没有起作用，运行时的表现与文档的说明不一致。

如果换用anyproxy 3.10的版本，是正常的，表现与文档中的说明一致。

#### The log of the error
[AnyProxy Log][2017-05-13 16:47:45]: will forward to local https server
[AnyProxy Log][2017-05-13 16:47:45]: [internal https]proxy server for mp.weixin.qq.com established
[AnyProxy Log][2017-05-13 16:47:45]: received request to: GET mp.weixin.qq.com/mp/getmasssendmsg?__biz=MTk4ODA2MDE2MQ==&
uin=OTY0OTIzMjYx&key=18d6081517924f1457ecbef4420e3d62cb48d3d0689f2e19a500683306339435fd4cf8bea7c0c25f02c8e1a29321a2be7cf
410fed4ba8d3226443aa7273aa52612b46a763bd675e963898c51d6c3bcd4&devicetype=Windows+7&version=6204014f&lang=zh_CN&ascene=7&
pass_ticket=wD6haxixpkMCUvCTzB3v%2BgPal8%2B%2Ff7ZbW9n33aYb%2BD5tAXHQUpcW9w7HhlrvIEG1
[AnyProxy Log][2017-05-13 16:47:45]: received request to: GET mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MTk4ODA2
MDE2MQ==&scene=124&uin=OTY0OTIzMjYx&key=5e09fc53966839de0dbd000e2f1c2c12364f7e947bb472433b3f03f7a6ca2f3223b1b299d2e55a48
887bc01880bf21e8d846b318fdcef24b41e5b29ecd2d0b4e7d0a38740c516c7c91eed765952d6589&devicetype=Windows+7&version=6204014f&l
ang=zh_CN&a8scene=7&pass_ticket=wD6haxixpkMCUvCTzB3v%2BgPal8%2B%2Ff7ZbW9n33aYb%2BD5tAXHQUpcW9w7HhlrvIEG1&winzoom=1
[AnyProxy Log][2017-05-13 16:47:45]: received https CONNECT request mp.weixin.qq.com
[AnyProxy Log][2017-05-13 16:47:45]: will forward to local https server
[AnyProxy Log][2017-05-13 16:47:45]: received request to: GET mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MTk4ODA2
MDE2MQ==&scene=124&uin=OTY0OTIzMjYx&key=ee0f1bea0fdc644343fd879375f5f460a873dec718f1850969ad0c0d6e6adb4341173306f6d432ba
11116d59a79239fa4df378d04dec5720b105ca79c9a75c56eadeb7716bff3999b2a5d9907dd2f966&devicetype=Windows+7&version=6204014f&l
ang=zh_CN&a8scene=7&pass_ticket=wD6haxixpkMCUvCTzB3v%2BgPal8%2B%2Ff7ZbW9n33aYb%2BD5tAXHQUpcW9w7HhlrvIEG1&winzoom=1
[AnyProxy Log][2017-05-13 16:47:45]: received request to: POST mp.weixin.qq.com/mp/profile_ext?action=urlcheck&uin=OTY0O
TIzMjYx&key=ee0f1bea0fdc644343fd879375f5f460a873dec718f1850969ad0c0d6e6adb4341173306f6d432ba11116d59a79239fa4df378d04dec
5720b105ca79c9a75c56eadeb7716bff3999b2a5d9907dd2f966&pass_ticket=wD6haxixpkMCUvCTzB3v+gPal8+/f7ZbW9n33aYb+D5tAXHQUpcW9w7
HhlrvIEG1
[AnyProxy Log][2017-05-13 16:47:46]: received https CONNECT request badjs.weixinbridge.com
[AnyProxy Log][2017-05-13 16:47:46]: will forward to local https server

**Comment by chengwz** [comment]
找到解决办法了。
只需要在*beforeSendRequest(requestDetail) 里，执行一下
delete newRequestOptions.headers['Accept-Encoding'];
就可以了。
原来用3.10时没有这个问题，因为请求里没有Accept-Encoding:gzip, deflate，而4.0-beta12时，莫名妙的加入了这个head信息。

**Comment by imwaco** [comment]
@chengwz 遇到同样的问题。
但我按你的方法操作了，问题并没有得到解决。

**Comment by codingfishman** [comment]
@imwaco 
   经重现，mp.weixin.qq.com/mp/getmasssendmsg 的压缩格式为deflate，目前没有被正确处理，因此这个请求的body，在AnyProxy查看的时候变成乱码，我们将尽快合并deflate的解压缩。
   AnyProxy将会在在请求时尽量保留原始的请求属性，因此如果浏览器支持那么AnyProxy也会尝试支持，而不去默认删除相应的header信息，后面我们也会完善相应的解压缩逻辑，谢谢反馈！

**Comment by codingfishman** [comment]
@chengwz 
   AnyProxy将会尽量保留浏览器原始的请求header，因此`Accept-Encoding`头部现在被保留了。
   针对这个issue的重现，我们发现是deflate的解析不够完善，导致deflate的返回被乱码，将会在代码合并后再发版本。
   谢谢你详细的反馈！

**Comment by ihoment-zhilong-lin** [comment]
@codingfishman 现在修复了嘛？
