### ISSUE TITLE
安装代理后无法访问微信公众号文章

### ISSUE THREAD

**Issue by yangxiaozhe13** [alibaba/anyproxy#183]
看到的是200的请求，但是页面报错无法打开
request
CONNECT HTTP/1.1
host : mp.weixin.qq.com
user-agent : Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304 MicroMessenger/6.5.7 NetType/WIFI Language/zh_CN
connection : keep-alive
proxy-connection : keep-alive
request body

response header

HTTP/1.1 200
response body

**Comment by codingfishman** [comment]
@yangxiaozhe13 
   可否提供一下地址，我试了一下微信公众号的文章，但是没有遇到异常，如： https://mp.weixin.qq.com/s/-VVuC7bCx8J9hQOV0WlWOw 。
   另，你所使用的AnyProxy版本是多少？

**Comment by yangxiaozhe13** [comment]
我用的是3.10.6的好像，我直接打开微信文章是没问题，但是在微信APP里面点开的就会报错，发送到浏览器都是看的到的

**Comment by yangxiaozhe13** [comment]
非常感谢，我觉得应该是微信APP那边的原因
