### ISSUE TITLE
Body的内容在anyproxy的WebUI上去掉了空格，与原始内容格式不一致。

### ISSUE THREAD

**Issue by chengwz** [alibaba/anyproxy#193]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Windows 7

#### The version of the AnyProxy

4.0.0-beta12

#### Your expected behavior of AnyProxy

希望在WebUI上，点击一条text/html的记录，弹出显示详细信息，Response中的Body内容，能够以原始格式显示：保留空格、缩进的格式。

#### The actual behavior of AnyProxy

WebUI上Body内容把空格都去掉了，与原始的返回内容不一致。不只是显示，复制出来的内容与原始格式也不一致。

**Comment by ottomao** [comment]
举个例子？比如哪个请求，样式变化了?

**Comment by chengwz** [comment]
哪个请求都是这样吧，这里面贴不了图啊。
同样请求，在 3.x 的WebUI里查看response的body，显示的格式跟在浏览器里查看源文件格式是一样的。但在4.x的WebUI里显示的都是去掉空格的：没有缩进，整个靠左侧堆积在一起。
不过，换行是保留了。

**Comment by codingfishman** [comment]
@chengwz 
   感谢反馈！我们会加上相应语法格式

**Comment by codingfishman** [comment]
![image](https://user-images.githubusercontent.com/5292705/29712367-107fdbb4-89cc-11e7-8391-7fd6f8fb0265.png)

已格式化，如图
