### ISSUE TITLE
如何将抓取到的包POST到另一台服务器上？

### ISSUE THREAD

**Issue by blackangeldsf** [alibaba/anyproxy#199]
有没有办法把服务器上抓取到返回的json数据post到另一台服务器上？
例如：
我用anyproxy抓到了一个ajax异步post请求，那么我如何把这个请求返回的json数据再post到另一台服务器上？

**Comment by blackangeldsf** [comment]
有知道的吗？

**Comment by codingfishman** [comment]
@blackangeldsf 
   如这个[例子](https://github.com/alibaba/anyproxy/blob/4.x/rule_sample/sample_modify_response_data.js)类似，你可以在拿到返回后，再将其转发到另一台服务器，只需要实现 `beforeSendResponse` 接口方法即可。

**Comment by blackangeldsf** [comment]
谢谢解答。我在rule文件里面 创建xmlhttp对象，提示没有这个对象。我对javascript不熟悉，不知下一步再如何做了。请问，能否详细指导下？谢谢。

**Comment by blackangeldsf** [comment]
@codingfishman 
谢谢解答。我在rule文件里面 创建xmlhttp对象，提示没有这个对象。我对javascript不熟悉，不知下一步再如何做了。请问，能否详细指导下？谢谢。

**Comment by codingfishman** [comment]
@blackangeldsf 
   不需要自己实现xmlhttp来做异步请求，你可以用 https://www.npmjs.com/package/node-fetch, 或者如果node版本够的话，直接使用node原生的请求类，来转发json ：）

**Comment by blackangeldsf** [comment]
@codingfishman 非常感谢您的热心指导。我按您的方案建议学习下相关知识。
