### ISSUE TITLE
有一种情况是，https 不走443端口，走其他端口就会报错

### ISSUE THREAD

**Issue by ijackwu** [alibaba/anyproxy#203]
Plese fill the template when you reporting a new issue, thanks!

#### The version of the AnyProxy

$ anyproxy -V
3.10.4

#### The log of the error

---
err with request :Error: connect ECONNREFUSED 127.0.0.1:443  /all/api.php?mod=main&ac=start&user_role=0&isnew_user=2&activity=MainActivity&client=2&uuid=3a281e72213004cf41464a114a42d086&device=ZTE+C2016-Android%3A4.4.2&channel=app&ver1497762719565&hash=df61e24d7d8c4deb2f63164fbeeab5b3

--- 正常是使用的10443端口

**Comment by codingfishman** [comment]
@ijackwu 
   请问代理的原始请求地址是多少，`127.0.0.1:10443`吗？

**Comment by ijackwu** [comment]
是的，走的是10443端口，没有走默认的443 @codingfishman
