### ISSUE TITLE
invalid distance too far back 

### ISSUE THREAD

**Issue by mm333444** [alibaba/anyproxy#204]
mac系统, 抓取数据库时提示 invalid distance too far back 
at Zlib_handle.onerror(zlib.js:355:17)

**Comment by codingfishman** [comment]
@mm333444 
   是具体到这个“抓取数据库”时才出的错误吗，请求有没有什么特殊的地方，是否方便列出？
   AnyProxy的版本是否为4.0@beta

**Comment by mm333444** [comment]
@codingfishman 抱歉没有描述清楚, 版本是4.0@beta.. 
通过注入echo '<script>setTimeout(function(){window.location.href="' . $url . '";},2000);</script>';代码实现跳转不断抓取, 偶发性的。如果再发现了，提供给您更具体的信息

**Comment by mm333444** [comment]
@codingfishman  抱歉, 非anyproxy问题, http返回500错误，就会提示这个..
