### ISSUE TITLE
Error: invalid distance code

### ISSUE THREAD

**Issue by mm333444** [alibaba/anyproxy#209]
系统:MAC 10.10
AnyProxy版本:4.0beta
抓取链接:https://mp.weixin.qq.com/s?__biz=MjM5NTA5NzYyMA==&mid=2654013358&idx=5&sn=6889b8cb2a8f5223533f3a250c7e05ff&chksm=bd381ad58a4f93c30161ece62e80d99c1450dac2b9a0c25c88dc4191186877e4a13f6059fa8f&scene=27&ascene=3&devicetype=android-19&version=26050735&nettype=WIFI&abtest_cookie=AgABAAgADAACAJ6GHgCvhh4AAAA%3D&pass_ticket=Ugop2JugiuVCTJMji6NM0LAIbBDkoiXeJaH5rzSsplg%3D&wx_header=1
情况: http 500错误的时候提示这个
General
Status Code:
500
Header
Host :
mp.weixin.qq.com
Connection :
keep-alive
Accept :
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent :
Mozilla/5.0 (Linux; Android 4.4.4; Mix Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN
x-wechat-key :
234667141a04714657af7014a60bbcc3c729f76e5c9c2a27492b8707be0a726e72ffa71c5b2c66c8c138f9f872400aca067fe61fe7e56069c4759e4976cf44f1847b1cfb60ad92d8577ee34f310be960
x-wechat-uin :
MTc4ODI4OTg0
Accept-Encoding :
gzip,deflate
Accept-Language :
zh-CN,en-US;q=0.8
Cookie :
rewardsn=1785a611e9f23c24f79b; wxtokenkey=98b596360f8d5f33d998fa5601c064eca767806cceb4f0407b55a8bbcbb1db5e; wxticket=2085781419; wxticketkey=8e64fe814f898a0a058670aeb2a9303ba767806cceb4f0407b55a8bbcbb1db5e; wxuin=178828984; pass_ticket=Ugop2JugiuVCTJMji6NM0LAIbBDkoiXeJaH5rzSsplg=; wap_sid2=CLjtolUSiAFNYVdpcHctSVpVMV9sS09Wczh2Nk0xQkFaQ3Y1Mk81dHpyUmlvMFdrLUxfd184Yl9BMENoakFUN0hsdWNWSExPdnJIWDJNNjU4UW5vbE02ODhnbDR3OTZ1eVd1aHh2WEtDdUhVQXl3N25mZkJaaHd3THBxR1FfRS1WMER1d3FNZmpRTUFBQX5+MOLJp8oFOA1AAQ==
X-Requested-With :
com.tencent.mm
Cookies
Name	Value
rewardsn	1785a611e9f23c24f79b
wxtokenkey	98b596360f8d5f33d998fa5601c064eca767806cceb4f0407b55a8bbcbb1db5e
wxticket	2085781419
wxticketkey	8e64fe814f898a0a058670aeb2a9303ba767806cceb4f0407b55a8bbcbb1db5e
wxuin	178828984
pass_ticket	Ugop2JugiuVCTJMji6NM0LAIbBDkoiXeJaH5rzSsplg=
wap_sid2	CLjtolUSiAFNYVdpcHctSVpVMV9sS09Wczh2Nk0xQkFaQ3Y1Mk81dHpyUmlvMFdrLUxfd184Yl9BMENoakFUN0hsdWNWSExPdnJIWDJNNjU4UW5vbE02ODhnbDR3OTZ1eVd1aHh2WEtDdUhVQXl3N25mZkJaaHd3THBxR1FfRS1WMER1d3FNZmpRTUFBQX5+MOLJp8oFOA1AAQ==

{ Error: invalid distance code
    at Zlib._handle.onerror (zlib.js:355:17) errno: -3, code: 'Z_DATA_ERROR' }

**Comment by codingfishman** [comment]
@mm333444 
 已修复，请尝试最新的beta版
