### ISSUE TITLE
iOS https代理mp.weixin.qq.com safari可以访问但微信内部无法访问

### ISSUE THREAD

**Issue by 9zdata** [alibaba/anyproxy#211]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac

Ca证书在ios已经安装，且已信任

#### The version of the AnyProxy

4.0 beta

#### Your expected behavior of AnyProxy

在微信内部访问文章可以正常打开

#### The actual behavior of AnyProxy

提示“网络出错，轻触屏幕重新加载:-1001”

#### The log of the error

[AnyProxy Log][2017-06-22 11:06:38]: received https CONNECT request mp.weixin.qq.com
[AnyProxy Log][2017-06-22 11:06:38]: will forward to local https server

各位大拿有碰到类似的事情吗？还是说ios肯定搞不了？

**Comment by mm333444** [comment]
@9zdata 我也在做微信, 可以打开。并且可以抓到, 你看你启动是否加 -i

**Comment by xtetym** [comment]
我的也是这样。win10加iphone5s,anyproxy3 ，电脑跟手机都添加了证书，手机进公众号一点进消息历史，就提示"提示“网络出错，轻触屏幕重新加载:-1002”"，手机百度都访问不了百度官网。
received https CONNECT request www.baidu.com
==>will forward to local https server
[internal https]proxy server for www.baidu.com established

不知道你解决了没有？

**Comment by codingfishman** [comment]
@9zdata @xtetym 
 iOS的系统版本是不是10.3？ 如果是的话请[单独配置证书](http://anyproxy.io/cn.html#ios->=-10.3信任ca证书)，我本地用4.0 beta目前没有重现，请试试

**Comment by Lost-In-Study** [comment]
同win10+anyproxy+ios,    `anyproxy -i` 启动，遇到公众号无法打开问题。
解决方法：在iPhone中  设置->通用->关于本机->证书信任设置->打开anyproxy

**Comment by codingfishman** [comment]
@Lost-In-Study  谢谢一并反馈。

**Comment by codingfishman** [comment]
关闭issue，有更新时再次打开。
