### ISSUE TITLE
打开http://localhost:8002/，浏览器Network里报404：Cannot GET /getMapConfig

### ISSUE THREAD

**Issue by lilongsy** [alibaba/anyproxy#212]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
Windows

#### The version of the AnyProxy
3.10.4

#### Your expected behavior of AnyProxy
不报404

#### The actual behavior of AnyProxy
在page.js:20324里报404错误。

**Comment by ottomao** [comment]
最新4.0版已经fix
