### ISSUE TITLE
Windows 7 安装完毕，执行anyproxy启动报错

### ISSUE THREAD

**Issue by firmlybelieve** [alibaba/anyproxy#213]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
系统:Windows7

#### The version of the AnyProxy

AnyProxy 4.0

#### Your expected behavior of AnyProxy
期望：能够正常使用

#### The log of the error

PS C:\Users\002715> anyproxy
F:\nodejs\node_modules\anyproxy\proxy.js:252
        for (const [key, conn] of this.requestHandler.conns) {
                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (F:\nodejs\node_modules\anyproxy\bin\anyproxy:34:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

重装一次，仍然报错。

**Comment by codingfishman** [comment]
@firmlybelieve 
   可否贴一下nodejs的版本

**Comment by jiucai** [comment]
我在win10下安装成功后，执行也报错：

D:\app\nodejs-v4.2.4\node_modules\anyproxy\proxy.js:252
        for (const [key, conn] of this.requestHandler.conns) {
                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\app\nodejs-v4.2.4\node_modules\anyproxy\bin\anyproxy-ca:11:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

D:\app\nodejs-v4.2.4>node --version
v4.2.4

**Comment by jiucai** [comment]
我新安装了一个 x64 版本的 node  v6.11.2 ，这个可以了。

npm install -g anyproxy@beta

`-- anyproxy@4.0.0-beta15
  +-- async@0.9.2
  +-- async-task-mgr@1.1.0
  +-- body-parser@1.17.2
  | +-- bytes@2.4.0
  | +-- content-type@1.0.2
  | +-- debug@2.6.7
  | | `-- ms@2.0.0
  | +-- depd@1.1.1
  | +-- http-errors@1.6.2
  | | `-- inherits@2.0.3
  | +-- iconv-lite@0.4.15
  | +-- on-finished@2.3.0
  | | `-- ee-first@1.1.1
  | +-- qs@6.4.0
  | +-- raw-body@2.2.0
  | | +-- iconv-lite@0.4.15
  | | `-- unpipe@1.0.0
  | `-- type-is@1.6.15
  |   +-- media-typer@0.3.0
  |   `-- mime-types@2.1.16
  +-- classnames@2.2.5
  +-- clipboard-js@0.3.5
  +-- co@4.6.0
  +-- colorful@2.1.0
  +-- commander@2.3.0
  +-- compression@1.7.0
  | +-- accepts@1.3.3
  | | `-- negotiator@0.6.1
  | +-- bytes@2.5.0
  | +-- compressible@2.0.11
  | | `-- mime-db@1.29.0
  | +-- debug@2.6.8
  | +-- on-headers@1.0.1
  | +-- safe-buffer@5.1.1
  | `-- vary@1.1.1
  +-- es6-promise@3.3.1
  +-- express@4.15.4
  | +-- array-flatten@1.1.1
  | +-- content-disposition@0.5.2
  | +-- cookie@0.3.1
  | +-- cookie-signature@1.0.6
  | +-- debug@2.6.8
  | +-- encodeurl@1.0.1
  | +-- escape-html@1.0.3
  | +-- etag@1.8.0
  | +-- finalhandler@1.0.4
  | | `-- debug@2.6.8
  | +-- fresh@0.5.0
  | +-- merge-descriptors@1.0.1
  | +-- methods@1.1.2
  | +-- parseurl@1.3.1
  | +-- path-to-regexp@0.1.7
  | +-- proxy-addr@1.1.5
  | | +-- forwarded@0.1.0
  | | `-- ipaddr.js@1.4.0
  | +-- qs@6.5.0
  | +-- range-parser@1.2.0
  | +-- send@0.15.4
  | | +-- debug@2.6.8
  | | +-- destroy@1.0.4
  | | `-- mime@1.3.4
  | +-- serve-static@1.12.4
  | +-- setprototypeof@1.0.3
  | +-- statuses@1.3.1
  | `-- utils-merge@1.0.0
  +-- iconv-lite@0.4.18
  +-- inquirer@3.2.1
  | +-- ansi-escapes@2.0.0
  | +-- chalk@2.1.0
  | | +-- ansi-styles@3.2.0
  | | | `-- color-convert@1.9.0
  | | |   `-- color-name@1.1.3
  | | +-- escape-string-regexp@1.0.5
  | | `-- supports-color@4.2.1
  | |   `-- has-flag@2.0.0
  | +-- cli-cursor@2.1.0
  | | `-- restore-cursor@2.0.0
  | |   +-- onetime@2.0.1
  | |   | `-- mimic-fn@1.1.0
  | |   `-- signal-exit@3.0.2
  | +-- cli-width@2.1.0
  | +-- external-editor@2.0.4
  | | +-- jschardet@1.5.1
  | | `-- tmp@0.0.31
  | |   `-- os-tmpdir@1.0.2
  | +-- figures@2.0.0
  | +-- lodash@4.17.4
  | +-- mute-stream@0.0.7
  | +-- run-async@2.3.0
  | | `-- is-promise@2.1.0
  | +-- rx-lite@4.0.8
  | +-- rx-lite-aggregates@4.0.8
  | +-- string-width@2.1.1
  | | `-- is-fullwidth-code-point@2.0.0
  | +-- strip-ansi@4.0.0
  | | `-- ansi-regex@3.0.0
  | `-- through@2.3.8
  +-- ip@0.3.3
  +-- juicer@0.6.15
  | +-- optimist@0.3.7
  | | `-- wordwrap@0.0.3
  | `-- uglify-js@1.2.6
  +-- mime-types@2.1.11
  | `-- mime-db@1.23.0
  +-- moment@2.18.1
  +-- nedb@1.8.0
  | +-- async@0.2.10
  | +-- binary-search-tree@0.2.5
  | +-- localforage@1.5.0
  | | `-- lie@3.0.2
  | |   +-- es3ify@0.1.4
  | |   | +-- esprima-fb@3001.1.0-dev-harmony-fb
  | |   | `-- jstransform@3.0.0
  | |   |   +-- base62@0.1.1
  | |   |   `-- source-map@0.1.31
  | |   +-- immediate@3.0.6
  | |   +-- inline-process-browser@1.0.0
  | |   | +-- falafel@1.2.0
  | |   | | +-- acorn@1.2.2
  | |   | | +-- foreach@2.0.5
  | |   | | +-- isarray@0.0.1
  | |   | | `-- object-keys@1.0.11
  | |   | `-- through2@0.6.5
  | |   |   +-- readable-stream@1.0.34
  | |   |   | `-- string_decoder@0.10.31
  | |   |   `-- xtend@4.0.1
  | |   `-- unreachable-branch-transform@0.3.0
  | |     +-- esmangle-evaluator@1.0.1
  | |     `-- recast@0.10.43
  | |       +-- ast-types@0.8.15
  | |       +-- esprima-fb@15001.1001.0-dev-harmony-fb
  | |       +-- private@0.1.7
  | |       `-- source-map@0.5.6
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | `-- underscore@1.4.4
  +-- node-easy-cert@1.1.3
  | `-- commander@2.11.0
  +-- node-forge@0.6.49
  +-- npm@2.15.12
  | +-- abbrev@1.0.9
  | +-- ansi@0.3.1
  | +-- ansi-regex@2.0.0
  | +-- ansicolors@0.3.2
  | +-- ansistyles@0.1.3
  | +-- archy@1.0.0
  | +-- async-some@1.0.2
  | +-- block-stream@0.0.9
  | +-- char-spinner@1.0.1
  | +-- chmodr@1.0.2
  | +-- chownr@1.0.1
  | +-- cmd-shim@2.0.2
  | +-- columnify@1.5.4
  | | `-- wcwidth@1.0.0
  | |   `-- defaults@1.0.3
  | |     `-- clone@1.0.2
  | +-- config-chain@1.1.10
  | | `-- proto-list@1.2.4
  | +-- dezalgo@1.0.3
  | | `-- asap@2.0.3
  | +-- editor@1.0.0
  | +-- fs-vacuum@1.2.9
  | +-- fs-write-stream-atomic@1.0.8
  | | `-- iferr@0.1.5
  | +-- fstream@1.0.10
  | +-- fstream-npm@1.1.1
  | | `-- fstream-ignore@1.0.5
  | +-- github-url-from-git@1.4.0
  | +-- github-url-from-username-repo@1.0.2
  | +-- glob@7.0.6
  | | +-- fs.realpath@1.0.0
  | | `-- path-is-absolute@1.0.0
  | +-- graceful-fs@4.1.6
  | +-- hosted-git-info@2.1.5
  | +-- imurmurhash@0.1.4
  | +-- inflight@1.0.5
  | +-- inherits@2.0.3
  | +-- ini@1.3.4
  | +-- init-package-json@1.9.4
  | | +-- glob@6.0.4
  | | | `-- path-is-absolute@1.0.0
  | | `-- promzard@0.3.0
  | +-- lockfile@1.0.1
  | +-- lru-cache@4.0.1
  | | +-- pseudomap@1.0.2
  | | `-- yallist@2.0.0
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | +-- node-gyp@3.6.0
  | | `-- semver@5.3.0
  | +-- nopt@3.0.6
  | +-- normalize-git-url@3.0.2
  | +-- normalize-package-data@2.3.5
  | | `-- is-builtin-module@1.0.0
  | |   `-- builtin-modules@1.1.0
  | +-- npm-cache-filename@1.0.2
  | +-- npm-install-checks@1.0.7
  | +-- npm-package-arg@4.1.0
  | +-- npm-registry-client@7.2.1
  | | +-- concat-stream@1.5.2
  | | | +-- readable-stream@2.0.6
  | | | | +-- core-util-is@1.0.2
  | | | | +-- isarray@1.0.0
  | | | | +-- process-nextick-args@1.0.7
  | | | | +-- string_decoder@0.10.31
  | | | | `-- util-deprecate@1.0.2
  | | | `-- typedarray@0.0.6
  | | `-- retry@0.10.0
  | +-- npm-user-validate@0.1.5
  | +-- npmlog@2.0.4
  | | +-- are-we-there-yet@1.1.2
  | | | `-- delegates@1.0.0
  | | `-- gauge@1.2.7
  | |   +-- has-unicode@2.0.0
  | |   +-- lodash.pad@4.4.0
  | |   | +-- lodash._baseslice@4.0.0
  | |   | +-- lodash._basetostring@4.12.0
  | |   | `-- lodash.tostring@4.1.4
  | |   +-- lodash.padend@4.5.0
  | |   `-- lodash.padstart@4.5.0
  | +-- once@1.4.0
  | +-- opener@1.4.1
  | +-- osenv@0.1.3
  | | +-- os-homedir@1.0.0
  | | `-- os-tmpdir@1.0.1
  | +-- path-is-inside@1.0.1
  | +-- read@1.0.7
  | | `-- mute-stream@0.0.5
  | +-- read-installed@4.0.3
  | | +-- debuglog@1.0.1
  | | +-- readdir-scoped-modules@1.0.2
  | | `-- util-extend@1.0.1
  | +-- read-package-json@2.0.4
  | | +-- glob@6.0.4
  | | | `-- path-is-absolute@1.0.0
  | | `-- json-parse-helpfulerror@1.0.3
  | |   `-- jju@1.3.0
  | +-- readable-stream@2.1.5
  | | +-- buffer-shims@1.0.0
  | | +-- core-util-is@1.0.2
  | | +-- isarray@1.0.0
  | | +-- process-nextick-args@1.0.7
  | | +-- string_decoder@0.10.31
  | | `-- util-deprecate@1.0.2
  | +-- realize-package-specifier@3.0.1
  | +-- request@2.74.0
  | | +-- aws-sign2@0.6.0
  | | +-- aws4@1.4.1
  | | +-- bl@1.1.2
  | | | `-- readable-stream@2.0.6
  | | |   +-- core-util-is@1.0.2
  | | |   +-- isarray@1.0.0
  | | |   +-- process-nextick-args@1.0.7
  | | |   +-- string_decoder@0.10.31
  | | |   `-- util-deprecate@1.0.2
  | | +-- caseless@0.11.0
  | | +-- combined-stream@1.0.5
  | | | `-- delayed-stream@1.0.0
  | | +-- extend@3.0.0
  | | +-- forever-agent@0.6.1
  | | +-- form-data@1.0.0-rc4
  | | | `-- async@1.5.2
  | | +-- har-validator@2.0.6
  | | | +-- chalk@1.1.3
  | | | | +-- ansi-styles@2.2.1
  | | | | +-- escape-string-regexp@1.0.5
  | | | | +-- has-ansi@2.0.0
  | | | | `-- supports-color@2.0.0
  | | | +-- commander@2.9.0
  | | | | `-- graceful-readlink@1.0.1
  | | | +-- is-my-json-valid@2.13.1
  | | | | +-- generate-function@2.0.0
  | | | | +-- generate-object-property@1.2.0
  | | | | | `-- is-property@1.0.2
  | | | | +-- jsonpointer@2.0.0
  | | | | `-- xtend@4.0.1
  | | | `-- pinkie-promise@2.0.1
  | | |   `-- pinkie@2.0.4
  | | +-- hawk@3.1.3
  | | | +-- boom@2.10.1
  | | | +-- cryptiles@2.0.5
  | | | +-- hoek@2.16.3
  | | | `-- sntp@1.0.9
  | | +-- http-signature@1.1.1
  | | | +-- assert-plus@0.2.0
  | | | +-- jsprim@1.3.0
  | | | | +-- extsprintf@1.0.2
  | | | | +-- json-schema@0.2.2
  | | | | `-- verror@1.3.6
  | | | `-- sshpk@1.9.2
  | | |   +-- asn1@0.2.3
  | | |   +-- assert-plus@1.0.0
  | | |   +-- dashdash@1.14.0
  | | |   +-- ecc-jsbn@0.1.1
  | | |   +-- getpass@0.1.6
  | | |   +-- jodid25519@1.0.2
  | | |   +-- jsbn@0.1.0
  | | |   `-- tweetnacl@0.13.3
  | | +-- is-typedarray@1.0.0
  | | +-- isstream@0.1.2
  | | +-- json-stringify-safe@5.0.1
  | | +-- mime-types@2.1.11
  | | | `-- mime-db@1.23.0
  | | +-- node-uuid@1.4.7
  | | +-- oauth-sign@0.8.2
  | | +-- qs@6.2.1
  | | +-- stringstream@0.0.5
  | | +-- tough-cookie@2.3.1
  | | `-- tunnel-agent@0.4.3
  | +-- retry@0.10.0
  | +-- rimraf@2.5.4
  | +-- semver@5.1.0
  | +-- sha@2.0.1
  | | `-- readable-stream@2.0.2
  | |   +-- core-util-is@1.0.1
  | |   +-- isarray@0.0.1
  | |   +-- process-nextick-args@1.0.3
  | |   +-- string_decoder@0.10.31
  | |   `-- util-deprecate@1.0.1
  | +-- slide@1.1.6
  | +-- sorted-object@2.0.0
  | +-- spdx-license-ids@1.2.2
  | +-- strip-ansi@3.0.1
  | +-- tar@2.2.1
  | +-- text-table@0.2.0
  | +-- uid-number@0.0.6
  | +-- umask@1.1.0
  | +-- validate-npm-package-license@3.0.1
  | | +-- spdx-correct@1.0.2
  | | `-- spdx-expression-parse@1.0.2
  | |   `-- spdx-exceptions@1.0.4
  | +-- validate-npm-package-name@2.2.2
  | | `-- builtins@0.0.7
  | +-- which@1.2.11
  | | `-- isexe@1.1.2
  | +-- wrappy@1.0.2
  | `-- write-file-atomic@1.1.4
  +-- pug@2.0.0-rc.3
  | +-- pug-code-gen@1.1.1
  | | +-- constantinople@3.1.0
  | | | +-- acorn@3.3.0
  | | | `-- is-expression@2.1.0
  | | |   `-- acorn@3.3.0
  | | +-- doctypes@1.1.0
  | | +-- js-stringify@1.0.2
  | | +-- pug-attrs@2.0.2
  | | +-- pug-error@1.3.2
  | | +-- void-elements@2.0.1
  | | `-- with@5.1.1
  | |   +-- acorn@3.3.0
  | |   `-- acorn-globals@3.1.0
  | |     `-- acorn@4.0.13
  | +-- pug-filters@2.1.4
  | | +-- clean-css@3.4.28
  | | | +-- commander@2.8.1
  | | | | `-- graceful-readlink@1.0.1
  | | | `-- source-map@0.4.4
  | | |   `-- amdefine@1.0.1
  | | +-- jstransformer@1.0.0
  | | | `-- promise@7.3.1
  | | |   `-- asap@2.0.6
  | | +-- pug-walk@1.1.4
  | | +-- resolve@1.4.0
  | | | `-- path-parse@1.0.5
  | | `-- uglify-js@2.8.29
  | |   +-- source-map@0.5.6
  | |   +-- uglify-to-browserify@1.0.2
  | |   `-- yargs@3.10.0
  | |     +-- camelcase@1.2.1
  | |     +-- cliui@2.1.0
  | |     | +-- center-align@0.1.3
  | |     | | +-- align-text@0.1.4
  | |     | | | +-- kind-of@3.2.2
  | |     | | | | `-- is-buffer@1.1.5
  | |     | | | +-- longest@1.0.1
  | |     | | | `-- repeat-string@1.6.1
  | |     | | `-- lazy-cache@1.0.4
  | |     | +-- right-align@0.1.3
  | |     | `-- wordwrap@0.0.2
  | |     +-- decamelize@1.2.0
  | |     `-- window-size@0.1.0
  | +-- pug-lexer@3.1.0
  | | +-- character-parser@2.2.0
  | | | `-- is-regex@1.0.4
  | | |   `-- has@1.0.1
  | | |     `-- function-bind@1.1.0
  | | `-- is-expression@3.0.0
  | |   `-- acorn@4.0.13
  | +-- pug-linker@3.0.2
  | +-- pug-load@2.0.8
  | | `-- object-assign@4.1.1
  | +-- pug-parser@3.0.1
  | | `-- token-stream@0.0.1
  | +-- pug-runtime@2.0.3
  | `-- pug-strip-comments@1.0.2
  +-- q@1.5.0
  +-- qrcode-npm@0.0.3
  +-- request@2.81.0
  | +-- aws-sign2@0.6.0
  | +-- aws4@1.6.0
  | +-- caseless@0.12.0
  | +-- combined-stream@1.0.5
  | | `-- delayed-stream@1.0.0
  | +-- extend@3.0.1
  | +-- forever-agent@0.6.1
  | +-- form-data@2.1.4
  | | +-- asynckit@0.4.0
  | | `-- mime-types@2.1.16
  | +-- har-validator@4.2.1
  | | +-- ajv@4.11.8
  | | | `-- json-stable-stringify@1.0.1
  | | |   `-- jsonify@0.0.0
  | | `-- har-schema@1.0.5
  | +-- hawk@3.1.3
  | | +-- boom@2.10.1
  | | +-- cryptiles@2.0.5
  | | +-- hoek@2.16.3
  | | `-- sntp@1.0.9
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.4.1
  | | | +-- assert-plus@1.0.0
  | | | +-- extsprintf@1.3.0
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.10.0
  | | |   +-- assert-plus@1.0.0
  | | |   `-- core-util-is@1.0.2
  | | `-- sshpk@1.13.1
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.1
  | |   +-- dashdash@1.14.1
  | |   | `-- assert-plus@1.0.0
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.7
  | |   | `-- assert-plus@1.0.0
  | |   +-- jsbn@0.1.1
  | |   `-- tweetnacl@0.14.5
  | +-- is-typedarray@1.0.0
  | +-- isstream@0.1.2
  | +-- json-stringify-safe@5.0.1
  | +-- oauth-sign@0.8.2
  | +-- performance-now@0.2.0
  | +-- stringstream@0.0.5
  | +-- tough-cookie@2.3.2
  | | `-- punycode@1.4.1
  | +-- tunnel-agent@0.6.0
  | `-- uuid@3.1.0
  +-- stream-throttle@0.1.3
  | `-- limiter@1.1.2
  +-- whatwg-fetch@1.1.1
  `-- ws@2.3.1
    +-- safe-buffer@5.0.1
    `-- ultron@1.1.0

**Comment by codingfishman** [comment]
@jiucai 应该是node版本的原因，建议使用node 5及以上的版本
