### ISSUE TITLE
在response的header内加上原始请求响应的content-length

### ISSUE THREAD

**Issue by alexyan** [alibaba/anyproxy#216]
在beforSendResponse接口处理response的时候， response的body已经是经过了proxy的处理，所以想要读取body的原始体积大小(gzipped)， 是不准确的，所以需求是在header内追加一个字段，保留原始体积

**Comment by codingfishman** [comment]
@alexyan 
  我们计划将原始的header信息单独放置一个字段中，`response.originHeader`, 意义纯粹一些，也可以方便使用其他的字段
