### ISSUE TITLE
询问将https记录存入recorder的代码注释掉的原因

### ISSUE THREAD

**Issue by PhilipDing** [alibaba/anyproxy#218]
我想请问下帮下述代码注释掉的原因。
requestHandler.js

![lalo5fnpps0dps0foa_1440_830 png_620x10000q90g](https://user-images.githubusercontent.com/4457568/27891927-402544a4-622f-11e7-84cc-d3ff9d7d73e8.jpg)

代码注释掉后，recorder里不会有HTTPS连接记录（forceProxyHttps=false的情况），当然web界面也不会显示，会让人觉得proxy是不是断掉了。

个人觉得对于HTTPS请求，计算是没办法读取body的的内容，但是帮这条消息记录下来是有必要的，至少让别人觉得这条请求确实是发送出去了。

像charles, fiddler之类的工具对于HTTPS之类的请求，也是会有记录的。

**Comment by ottomao** [comment]
是bug，4.x版本已经修了

**Comment by ottomao** [comment]
我的错，这块还没修掉，先reopen....

**Comment by codingfishman** [comment]
已修复
