### ISSUE TITLE
Fix for Chrome 58 issue which require SAN field in certificates

### ISSUE THREAD

**Issue by JulienBeaudeau** [alibaba/anyproxy#219]
#### Which platform are you running AnyProxy
Windows 7.

#### The version of the AnyProxy
3.10.2

#### Your expected behavior of AnyProxy
Works  with Chrome 58 version with https protocol

#### The actual behavior of AnyProxy
Doesn't work properly because certificates generated by anyproxy are not recognized by the browser as valid.  The SAN  field is missing in certificates

#### The log of the error
'ERR_CERT_COMMON_NAME_INVALID'

**Comment by JulienBeaudeau** [comment]
[certGeneratorFinal.zip](https://github.com/alibaba/anyproxy/files/1128296/certGeneratorFinal.zip)

**Comment by JulienBeaudeau** [comment]
Here is as attachment the fix
[certGeneratorFinal.zip](https://github.com/alibaba/anyproxy/files/1128303/certGeneratorFinal.zip)

**Comment by codingfishman** [comment]
Hi @JulienBeaudeau 
   Thanks so much for your fix, the issue should have been fixed in 4.x@beta, you can take a try:)
