### ISSUE TITLE
怎么获取报文的body部分

### ISSUE THREAD

**Issue by shifop** [alibaba/anyproxy#220]
问题描述:
在beforeSendResponse中,使用"console.log(responseDetail.response.body)"输出数据

平台:windows
版本:4.0.0-beta13
期望结果:输出报文body全部信息
实际输出:body: <Buffer > }

**Comment by wishchen** [comment]
这样试试:
`const newResponse = responseDetail.response.body;`
`console.log(newResponse);`

**Comment by codingfishman** [comment]
@shifop 
 实际的body是有内容的吗，是不是所有的body都是空？

**Comment by codingfishman** [comment]
关闭issue，有更新可再次打开。
