### ISSUE TITLE
如何保存抓到所有的请求和返回数据保存

### ISSUE THREAD

**Issue by wishchen** [alibaba/anyproxy#222]
开启anyproxy后，在http://localhost:8002/看到的数据 如何保存？  是需要通过顾虑规则手动将所有数据写入文件保存吗？

**Comment by shifop** [comment]
我的做法是自己写个后台处理数据,然后写个get或者post请求,在anproxy中,将拦截到的内容转发到自己写的后台的url.

**Comment by codingfishman** [comment]
@wishchen 
   目前只能借助rule文件来实现，我们正在添加log功能，后面可以通过一个参数，开启AnyProxy的文件log记录

**Comment by wishchen** [comment]
@codingfishman  @shifop  多谢  我尝试用rule写文件试试
