### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by hktalent** [alibaba/anyproxy#225]
# 1、界面接口呢？
想添加更多功能到界面，因为没有设计文档，部分代码注释不全，无从下手啊

# 2、建议添加如下功能
a、静态资源缓存 开关
b、资源替换 示例
c、文本替换 示例

# 界面中数据的修改 与锁定
例如
a、设置user-agent 随机变化，则全局自动应用
b、修改host、cookie、其他参数 等后 提供 redo 按钮，像安全测试工具一样，便于进行伪造host测试

# 3、能否提供架构、设计文档、图示，便于扩展?

# 4、能否架构、设计支持编写插件，便于大家共同实现不同的插件?

**Comment by codingfishman** [comment]
hi @hktalent 
  谢谢反馈，可访问 http://anyproxy.io/cn.html 来获取一些更详细的信息。
  插件支持我们一直在做，AnyProxy的初衷也在这里，借助rule（插件）和社区的力量来实现不同功能，目前rule还只是一个单一的js，我们正在计划和实现可发布和共享的rule，方便大家插件的编写

**Comment by hktalent** [comment]
@codingfishman

**Comment by hktalent** [comment]
@codingfishman ok
