### ISSUE TITLE
beta15 webInterface is blank

### ISSUE THREAD

**Issue by Nowforpasserby** [alibaba/anyproxy#226]
I use the Mac 10.12.6, the anyproxy version is 4.0.0 beta15 
 I use it by npm module, i write it as the demo is .
but the http://localhost:8002/  is not valid,neither the error log

open the localhost:8002 console, it's appear

main.js:11819 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ main.js:11819
main.js:11819 Warning: AnimateChild: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ main.js:11819
main.js:153956 Uncaught TypeError: Failed to construct 'Blob': Iterator getter is not callable.
    at Object.<anonymous> (main.js:153956)
    at __webpack_require__ (main.js:20)
    at Object.<anonymous> (main.js:8784)
    at __webpack_require__ (main.js:20)
    at Object.support.searchParams (main.js:49)
    at __webpack_require__ (main.js:20)
    at main.js:40
    at main.js:43

the above

thx

**Comment by Nowforpasserby** [comment]
the other is fine

**Comment by p2227** [comment]
版本 62.0.3173.0（正式版本）canary （64 位） 会报一样的错
版本 59.0.3071.115（正式版本） （64 位） 是好的
