### ISSUE TITLE
web界面在最新版chrome下报错

### ISSUE THREAD

**Issue by lynsun** [alibaba/anyproxy#227]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

4.0beta

#### Your expected behavior of AnyProxy

界面正常展示
#### The actual behavior of AnyProxy

控制台js报错

**Comment by Nowforpasserby** [comment]
the same as #226

**Comment by codingfishman** [comment]
fixed in https://github.com/alibaba/anyproxy/pull/228
