### ISSUE TITLE
ignore unsecure https request

### ISSUE THREAD

**Issue by ottomao** [alibaba/anyproxy#23]
In some cases, we want to ignore the warning about unsecure certificates. Here we should add a config for that.

**Comment by wuchangming** [comment]
添加个option？

当被代理的https证书不安全时也正常转发
`process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0'`

**Comment by codingfishman** [comment]
Already added.
By command line `anyproxy ----ignore-unauthorized-ssl`;
By node module,  `{ dangerouslyIgnoreUnauthorized = false }`
