### ISSUE TITLE
如何在日志中打印一个url的Request的Body信息？

### ISSUE THREAD

**Issue by chenlei-123** [alibaba/anyproxy#230]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

mac OSX
#### The version of the AnyProxy

anyproxy@beta

#### Your expected behavior of AnyProxy

能在日志中打印Request的Body信息
![Uploading image.png…]()

#### The actual behavior of A
<img width="632" alt="wx20170803-220641 2x" src="https://user-images.githubusercontent.com/4646806/28925663-13263eca-7898-11e7-8df2-2db688d80d35.png">
nyProxy

**Comment by Nowforpasserby** [comment]
*beforeSendRequest (req) {
    console.log(req.requestData);
}

**Comment by chenlei-123** [comment]
@Nowforpasserby 为什么同样的一个接口在anyProxy  Web UI上看到的是正常的，
![image](https://user-images.githubusercontent.com/4646806/28950944-69f41148-78fa-11e7-92c2-c69cca400749.png)
但是用console.log(req.requestData)，日志中打印出来的是转码的？
![image](https://user-images.githubusercontent.com/4646806/28950972-8e1f2134-78fa-11e7-936f-34655d2273b2.png)
请教，谢谢！

**Comment by Nowforpasserby** [comment]
console.log(req.requestData.toString());

**Comment by chenlei-123** [comment]
@Nowforpasserby 受教了，非常感谢！

**Comment by codingfishman** [comment]
@Nowforpasserby  谢谢！
