### ISSUE TITLE
添加rule运行的时候提示错误 

### ISSUE THREAD

**Issue by chenmolm** [alibaba/anyproxy#232]
(node:2464) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): TypeError: You may only yield a function, promise, generator, array
, or object, but the following object was passed: "thisruleanyproxy"
安装在win2008的服务器上报的错 但是同样的规则 在我本地服务器上没有问题

**Comment by codingfishman** [comment]
@chenmolm  是否方便将rule文件提供一下？

**Comment by chenmolm** [comment]
已经解决了
