### ISSUE TITLE
ios 10.3以上系统无法使用https的问题

### ISSUE THREAD

**Issue by river-lee** [alibaba/anyproxy#234]
这个是一个建议，我看很多人在代理https的时候无法使用，ios 10.3以上的系统除了安装CA以为还需要设置证书信任设置（设置 -> 通用 -> 关于本机 -> 证书信任设置 信任你需要的证书就可以正常的使用啦）。

**Comment by codingfishman** [comment]
@river-lee   谢谢留言！

**Comment by river-lee** [comment]
麻烦加到文档中，我有几个同事也来问这个问题。

**Comment by codingfishman** [comment]
@river-lee  
  已经在文档里面：  http://anyproxy.io/cn.html#ios->=-10.3信任ca证书
