### ISSUE TITLE
安装之后 启动，浏览器查看有报错

### ISSUE THREAD

**Issue by ctocto** [alibaba/anyproxy#236]
Plese fill the template when you reporting a new issue, thanks!

![image](https://user-images.githubusercontent.com/16641120/29159636-d8adc1ce-7de1-11e7-9bc4-1f4b0c003db7.png)
安装后，anyproxy  启动服务。然后在浏览器 127.0.0.1:8002 浏览没有任何内容，控制台报错。
#### Which platform are you running AnyProxy

windows10
#### The version of the AnyProxy

anyproxy@4.0.0-beta15

#### Your expected behavior of AnyProxy

昨天运行还是正常的。今天运行就报错了，重新安装也不行
#### The actual behavior of AnyProxy

服务运行正常
#### The log of the error

服务运行正常

**Comment by towry** [comment]
```bash
npm uninstall -g anyproxy
npm install -g anyproxy
```

**Comment by ctocto** [comment]
这样的话就是老版本了。api 也是老的。我针对新版本写了一些rule，对新的更熟悉一点。

**Comment by ctocto** [comment]
#228

**Comment by ctocto** [comment]
#227

**Comment by codingfishman** [comment]
Hi @ctocto   
  可参见： https://github.com/alibaba/anyproxy/pull/228
