### ISSUE TITLE
localhost:8002 works unnormally, show nothing

### ISSUE THREAD

**Issue by grantonzhuang** [alibaba/anyproxy#237]
#### The log of the error

error in `main.js`

TypeError: Argument 1 of Blob.constructor can't be converted to a sequence.[详细了解]  main.js:153956:68
	<匿名> http://10.10.1.163:8002/dist/main.js:153956:68
	__webpack_require__ http://10.10.1.163:8002/dist/main.js:20:12
	<匿名> http://10.10.1.163:8002/dist/main.js:8784:20
	__webpack_require__ http://10.10.1.163:8002/dist/main.js:20:12
	<匿名> http://10.10.1.163:8002/dist/main.js:49:19
	__webpack_require__ http://10.10.1.163:8002/dist/main.js:20:12
	<匿名> http://10.10.1.163:8002/dist/main.js:40:18
	<匿名>

#### error log:
Uncaught TypeError: Failed to construct 'Blob': Iterator getter is not callable.
    at Object.<anonymous> (main.js:153956)
    at __webpack_require__ (main.js:20)
    at Object.<anonymous> (main.js:8784)
    at __webpack_require__ (main.js:20)
    at Object.support.searchParams (main.js:49)
    at __webpack_require__ (main.js:20)
    at main.js:40
    at main.js:43

**Comment by chaozhangpower** [comment]
Please Uninstall Chrome ,reset install

**Comment by Nowforpasserby** [comment]
fixed in #228
