### ISSUE TITLE
需求：对于配置了Transfer-Encoding:chunked支持的响应体返回原始body的Content-Length

### ISSUE THREAD

**Issue by alexyan** [alibaba/anyproxy#238]
@codingfishman 需求是在beforeSendResponse取response header内的content-length
但是服务器若设置响应体支持Transfer-Encoding:chunked，那么就不会返回content-length
所以希望支持一下，谢谢

#### The version of the AnyProxy
4.x

**Comment by codingfishman** [comment]
已修复，现在`x-anyproxy-origin-content-length`将作为实际的content length, 且在 `beforeSendReponse`中可以使用
