### ISSUE TITLE
How can I decode the base64 content of the request body

### ISSUE THREAD

**Issue by Echolei321** [alibaba/anyproxy#239]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Windows
#### The version of the AnyProxy

3.10.4
#### Your expected behavior of AnyProxy

The content of request body are decode

**Comment by codingfishman** [comment]
@Echolei321 
 The body of is not base64, they are [Buffer](https://nodejs.org/api/buffer.html), 因此你可以用相关的api来操作
