### ISSUE TITLE
请问anyproxy是否可以通过代理访问后端服务器，如何配置。从而达到伪装真实ip的目的？

### ISSUE THREAD

**Issue by zaitaxiang123** [alibaba/anyproxy#241]
Plese fill the template when you reporting a new issue, thanks!

**Comment by Nowforpasserby** [comment]
http://anyproxy.io/cn.html#修改请求的目标地址

**Comment by codingfishman** [comment]
Thanks @Nowforpasserby 

@zaitaxiang123  请按文档尝试一下，能否达到需求
