### ISSUE TITLE
无法将response写到本地文件

### ISSUE THREAD

**Issue by lmlucky** [alibaba/anyproxy#244]
var fs = require('fs');
var logger = fs.createWriteStream(__dirname + '/resLog.txt', {
  flags: 'a' // 'a' means appending (old data will be preserved)
})

module.exports = {

    replaceServerResDataAsync: function(req,res,serverResData,callback){
        //append "hello world" to all web pages

        //for those non-unicode response , serverResData.toString() should not be your first choice.
        //this issue may help you understanding how to modify an non-unicode response: https://github.com/alibaba/anyproxy/issues/20
        if(/html/i.test(res.headers['Content-Type'])){
            var newDataStr = serverResData.toString();
            // newDataStr += "hello world!";
            logger.write(newDataStr);
            callback(newDataStr);
        }else{
            var newDataStr = serverResData.toString();
            logger.write(newDataStr);
            callback(serverResData);
        }
    }
};
#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

anyproxy@beta

#### Your expected behavior of AnyProxy

/resLog.txt大小不为0；
#### The actual behavior of AnyProxy

/resLog.txt 大小为0

**Comment by codingfishman** [comment]
Hi @lmlucky 
  AnyProxy 4.0 beta重新设计了rule的结构，处理response的方法现在为`beforesendresponse`,并且是一个generator函数，你可以[在这里](http://anyproxy.io/cn.html#beforesendresponse)来看到调用示例，谢谢
