### ISSUE TITLE
https代理：Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by SylviaLan** [alibaba/anyproxy#246]
Please fill the template when you reporting a new issue, thanks!

平台：mac

版本：4.0.0-beta16

问题详细描述：
手机端https接口，部分接口通过ip而不是域名访问，通过域名访问的接口正常无误，ip访问的接口报错，通过网页可以看到请求已经正常发送，response内容也正常，但status code显示为500，该响应最后没有返回到手机端

错误日志：
[AnyProxy ERROR][2017-08-26 00:10:20]: Error: Hostname/IP doesn't match certificate's altnames: "IP: 121.**.**.1** is not in the cert's list: "
Error: Hostname/IP doesn't match certificate's altnames: "IP: 121.**.**.1**  is not in the cert's list: "
    at Object.checkServerIdentity (tls.js:199:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:29)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

备注：用mitmproxy尝试该类接口也无法正常代理，charles可以，fiddler可以

**Comment by SylviaLan** [comment]
更正一下，截取到的request正常，但是response里内容不正常，response的cookie及body显示的还是request的内容 。还碰到了另一个报错，信息如下，status code也是500

[AnyProxy ERROR][2017-08-27 15:34:14]: Error: certificate has expired

是否是我的配置出了问题，还是我证书没弄好？还请不吝赐教

**Comment by ottomao** [comment]
证书和域名相关，如果证书上没配置关联的IP，肯定是校验不通过的，这是安全特性，不是bug。

如果要关闭这个特性，参照FAQ ：  http://anyproxy.io/cn.html#the-connection-is-not-private

**Comment by plusor** [comment]
@ottomao 你好,  请问 `3.10.4` 版本如何修改.   目前好像都是`4.x`版本的文档

**Comment by codingfishman** [comment]
@plusor 
  你也是遇到了相同的问题吗？如果是的话可否提供请求和代理的方式，谢谢

**Comment by plusor** [comment]
@codingfishman GET 请求, 
![image](https://user-images.githubusercontent.com/659346/32156315-986ed8c4-bd0a-11e7-88af-24953f278634.png)

**Comment by codingfishman** [comment]
@plusor 
  ERR_CERT_COMMON_NAME_INVALID 是新版Chrome所引入的检查机制，AnyProxy已经对其进行过修复，请删除原目录下的证书文件, 并重新生成证书即可在新版Chrome上使用

**Comment by plusor** [comment]
@codingfishman 我有删除过`~/.anyproxy_certs/ ` 下所有的文件, 还是不能用
