### ISSUE TITLE
如何重写 Recorder 记录的内容？

### ISSUE THREAD

**Issue by hokor** [alibaba/anyproxy#251]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

4.0-beta

#### Your expected behavior of AnyProxy

Request Body 使用了自有的压缩算法，测试时需要明文展示请求内容。现在在 rule 中将body解压后只能内容输出到 console ，有没有办法在 web 中查看解压后的内容，而服务端继续获得原始内容？

#### The actual behavior of AnyProxy

如果在 rule 中修改了请求内容，服务端不能正常处理。

**Comment by codingfishman** [comment]
@hokor 
  在rule中拿到的body，是buffer串，如果你知道他具体的格式，可以利用buffer的方法来将其转换，比如`toString()`。只是读取的话不会更改其内容，服务端仍然可以拿到原始的请求。
