### ISSUE TITLE
create的server一直不close

### ISSUE THREAD

**Issue by zizhouwang** [alibaba/anyproxy#253]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac

#### The version of the AnyProxy

3.10.4

#### Your expected behavior of AnyProxy

可以一直开着，每个create的server在工作完后会按时close

#### The actual behavior of AnyProxy

create后就不管了，没有close

#### The log of the error

一段时间后，端口就超过了65535，好像是这个数字吧，反正就是最大端口号，之后就停掉了

**Comment by codingfishman** [comment]
Hi @zizhouwang 
  AnyProxy 3.10 的端口检测是从40000开始的递增，所以端口关闭后仍然不会被再次使用，你可以升级为4.x-beta, 端口随机分配。
 另外，是使用了比较长的时间所以端口不够用了吗？

**Comment by codingfishman** [comment]
先将issue关闭，如有反馈将再打开
