### ISSUE TITLE
新版本的anyproxy 使用localhost:8002无法查看拦截的包

### ISSUE THREAD

**Issue by scrui** [alibaba/anyproxy#254]
#### Which platform are you running AnyProxy

Window7
#### The version of the AnyProxy

4.0.0-beta9

#### Your expected behavior of AnyProxy

本机代理设置为anyprxoy后，
在浏览器中输入 “ http://localhost:8002/ ”
应能够查看anyproxy的拦截内容。

#### The actual behavior of AnyProxy

无法查看拦截内容，浏览器标签显示anyproxy，但没有实际的内容
效果图如下：
![firefox](https://user-images.githubusercontent.com/7711960/30637564-3a72b3e2-9e2b-11e7-8fbc-9569629b9791.PNG)

ps:使用IE/chrome浏览器，也是同样的现象

IE:
![ie](https://user-images.githubusercontent.com/7711960/30728134-7442d1c0-9f88-11e7-8f63-2baf39ddda8e.PNG)

Chrome:

![chrome](https://user-images.githubusercontent.com/7711960/30728156-a162b47c-9f88-11e7-8c8a-f51288cf52fb.PNG)

**Comment by codingfishman** [comment]
@scrui 
  请问是4.x-beta还是3.10.3， 打开chrome的调试工具，是否有报错提示？

**Comment by scrui** [comment]
不好意思，信息错误。
之前使用的版本是 4.0.0-beta12

**Comment by lionel126** [comment]
升级啊  beta9不支持chrome60

**Comment by mdluo** [comment]
同样问题，页面空白，console 报错，anyproxy@4.0.0-beta18，Chrome v61.0

```log
Uncaught TypeError: Failed to construct 'Blob': Iterator getter is not callable.
    at Object.<anonymous> (main.js:152069)
    at __webpack_require__ (main.js:20)
    at Object.<anonymous> (main.js:8782)
    at __webpack_require__ (main.js:20)
    at Object.<anonymous> (main.js:49)
    at __webpack_require__ (main.js:20)
    at main.js:40
    at main.js:43
```

**Comment by lionel126** [comment]
beta18也报错？ 那我就不知道了 
我用的beta16 曾经经历过beta9这个错误

**Comment by scrui** [comment]
@
你好。请问是不是说这个现象存在于beta9版本，
beta16版本就已经正常了？

**Comment by scrui** [comment]
谢谢各位。
我尝试升级了一下，发现之前升级失败。请问下面的ERROR是怎么回事呢？
（估计上面所说使用了新版测试也是错的，实际上安装的仍是beta9）
E:\wxproxy\wxproxy>npm install
wxproxy@1.0.0 E:\wxproxy\wxproxy
`-- anyproxy@4.0.0-beta9

npm WARN wxproxy@1.0.0 No repository field.
