### ISSUE TITLE
支持websocket代理吗？

### ISSUE THREAD

**Issue by cole-dda** [alibaba/anyproxy#255]
Plese fill the template when you reporting a new issue, thanks!

**Comment by codingfishman** [comment]
@cole-dda 
   如果是说websocket可否使用AnyProxy来通信，那是支持的。AnyProxy会直接让其和目标服务器进行通信，本身没有在其中进行干预，因此websocket在AnyProxy下可以用，但是无法进行干预。 
   另外，如果AnyProxy开启了https代理，目前的版本中，wss协议将会失败，ws协议工作正常。

**Comment by codingfishman** [comment]
现将issue关闭，后续有反馈可再打开

**Comment by husterxsp** [comment]
请问，目前的版本，如果 开启了https代理，wss还是失效，请问是还不支持吗？
