### ISSUE TITLE
mac 启动出错

### ISSUE THREAD

**Issue by yuanzx** [alibaba/anyproxy#258]
#### Which platform are you running AnyProxy

mac
#### The version of the AnyProxy

4.0.0-beta18

#### Your expected behavior of AnyProxy

运行anyproxy 能正常显示 http://127.0.0.1:8001/   不显示错误

#### The actual behavior of AnyProxy

出现错误提示
#### The log of the error

# AnyProxy Inner Error

Oops! Error happend when AnyProxy handle the request.

This is an error occurred inside AnyProxy, not from your target website.

Error: connect ECONNREFUSED 127.0.0.1:80
at Object.exports._errnoException (util.js:1024:11)
at exports._exceptionWithHostPort (util.js:1047:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

**Comment by codingfishman** [comment]
@yuanzx 
   是不是要访问界面？AnyProxy的web地址是 localhost:8002, 8001是proxy的端口。

**Comment by jiangtao** [comment]
me, too

**Comment by codingfishman** [comment]
@jiangtao 
也是在访问localhost:8001的时候吗？

**Comment by yuanzx** [comment]
好久没登录了，这个issue先关闭了
