### ISSUE TITLE
频繁报deprecationWarning错误

### ISSUE THREAD

**Issue by LiuHD** [alibaba/anyproxy#262]
Plese fill the template when you reporting a new issue, thanks!

lib/recorder.js 103行使用fs.writeFile函数，没有传入callback参数，这个参数在nodev7.0.0之后已经为必选了，否则会报depreciationWarning错误。
#### Which platform are you running AnyProxy

windows
#### The version of the AnyProxy

v3.10.3

#### Your expected behavior of AnyProxy

不要再报api废弃的提示了，本来cli模式下打印的东西就多，这个废弃的api报错更多
#### The actual behavior of AnyProxy

一直报错
#### The log of the error

每个请求基本上都会报，就不截取了

**Comment by codingfishman** [comment]
Hi @LiuHD 
   这段警告已经在4.0@beta中修复了，欢迎使用。
   同时，可以在启动时加上`-s`命令，将不会打印相关信息，如  `anyproxy -i -s`

**Comment by LiuHD** [comment]
好的，谢谢！

**Comment by LiuHD** [comment]
好的，谢谢！
