### ISSUE TITLE
被测服务器响应时间超过2分钟，客户端无法收到anyproxy的响应

### ISSUE THREAD

**Issue by tonglei100** [alibaba/anyproxy#265]
Windows 

4.0版本

场景如下：
 postman 发送请求到anyproxy  --> anyproxy 处理请求数据 --> 发送给服务端
服务端响应时间2分钟 --> anyproxy 收到响应

期望：anyproxy 把响应发送给 postman
实际：postman 没有收到响应

其他信息：如果响应时间比较快，比如几秒内，是可以返回到 postman的

**Comment by codingfishman** [comment]
Hi @tonglei100 
  从控制面板上看，AnyProxy有没有打印一些链接超时的信息？

**Comment by tonglei100** [comment]
控制面板上，点击这条请求，不会弹出“Request Response” 页面，这条连接就变成灰色的了
没看到有打印超时信息
