### ISSUE TITLE
启动自定义规则失败

### ISSUE THREAD

**Issue by yuehaotian** [alibaba/anyproxy#268]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

windows
#### The version of the AnyProxy

4.0.0-beta18

#### Your expected behavior of AnyProxy

启动自定义规则
#### The actual behavior of AnyProxy

启动失败
#### The log of the error

[AnyProxy ERROR][2017-10-26 14:29:32]: Failed to load rule file
[AnyProxy ERROR][2017-10-26 14:29:32]: ReferenceError: fetch is not defined

**Comment by codingfishman** [comment]
@yuehaotian 
   是不是rule中引用了类似fetch的api？

**Comment by yuehaotian** [comment]
找到原因了，是我在判断语句里多加了一行空行导致的...
