### ISSUE TITLE
请问anyproxy的filter如何设置，可以把post请求中的相关字段给筛选出来

### ISSUE THREAD

**Issue by shichaowei** [alibaba/anyproxy#274]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
windows

#### The version of the AnyProxy
4.0

#### Your expected behavior of AnyProxy
在anyproxy的web界面，filter如何设置，可以把post请求中的某个字段给筛选出来 ；
如一个post请求，上行为json字符串，里面有个值是“abc”，如何筛选出来请求的body里面有abc的请求

**Comment by codingfishman** [comment]
@shichaowei 
   目前filter只支持对url的筛选，不知道对于你的需求，是否粒度仍然过于广泛？
   如果url的粒度过粗，可否通过自定义rule中的[beforeSendResponse](http://anyproxy.io/cn.html#beforesendresponse)方法来将你要的信息进行打印

**Comment by codingfishman** [comment]
长时间未显示，暂时关闭issue

**Comment by learnStop163** [comment]
后续会增加更为细致的筛选吗？
