### ISSUE TITLE
请问怎样把anyproxy打包成类似发布版的可执行文件？

### ISSUE THREAD

**Issue by zhaozhixin** [alibaba/anyproxy#276]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac

请问怎样把anyproxy打包成类似发布版的可执行文件？

**Comment by codingfishman** [comment]
@zhaozhixin 
  “可执行文件”是指dmg这种吗？

**Comment by zhaozhixin** [comment]
就是类似于npm i anyproxy -g
这样直接直接执行anyproxy就能够运行了 这个是啥原理？

**Comment by codingfishman** [comment]
package.json配置自带支持可执行命令行，可以参考npm官方配置： https://docs.npmjs.com/files/package.json#bin
以及一个很好用的类来处理命令参数：https://github.com/tj/commander.js
