### ISSUE TITLE
微信小程序代理设置

### ISSUE THREAD

**Issue by Relsoul** [alibaba/anyproxy#277]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

MAC

#### The version of the AnyProxy

3.10.4

#### Your expected behavior of AnyProxy

POST请求非404

#### The actual behavior of AnyProxy

anyProxy代理微信小程序设置userAgent调试(加了Beta_V3) POST微信返回404

#### The log of the error

POST /wxa-dev-logic/jslogin?_r=0.8851196500887772&appid=wx264b57e307b7096a&platform=0&ext_appid=&os=darwin&clientversion=101171019&newticket=XmX-1mmLL7_QtrryQg2pDRLMzw8at9phjHy-xjYuYjI&os=darwin&clientversion=1.01.171019 HTTP/1.1
host : servicewechat.com
content-length : 25
connection : close
user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36 BETA_V3
request body

{"scope":["snsapi_base"]}

response header

HTTP/1.1 404
connection : close
date : Thu, 09-Nov-2017 09:57:29 GMT
access-control-allow-credentials : true
access-control-allow-origin : -___-||
access-control-allow-methods : GET, POST, PUT
access-control-allow-headers : -___-||
response body

**Comment by codingfishman** [comment]
@Relsoul 
  这个请求在何时会被发出，不经过代理，直接访问的话是一个有效请求吗？
  我直接访问的话，返回也是404，请帮忙确认

**Comment by Relsoul** [comment]
@codingfishman  我这边用charles代理了一下是没问题的。。。 估计问题出在我这边 应该是访问微信的接口有特定的user-agent~是我这边的疏忽提了个issue 抱歉。

**Comment by igsood** [comment]
> @codingfishman 我这边用charles代理了一下是没问题的。。。 估计问题出在我这边 应该是访问微信的接口有特定的user-agent~是我这边的疏忽提了个issue 抱歉。

现在IOS好像抓不到这个包了

**Comment by mojie126** [comment]
请问抓这个包的意义是可以获取其他小程序的登录凭证么...？
