### ISSUE TITLE
修改请求数据的sample文件中的curl命令示例错误，应该用双引号

### ISSUE THREAD

**Issue by tianlanse66** [alibaba/anyproxy#279]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Windows系统使用curl命令
#### The version of the AnyProxy

4.0.0

#### Your expected behavior of AnyProxy

curl -H "Content-Type: text/plain" -X POST -d 'original post data' http://httpbin.org/post
{
          "args": {},
          "data": **"original post data"**,
          "files": {},
          "form": {},
          "headers": {
            "Accept": "*/*",
            "Connection": "close",
            "Content-Length": "18",
            "Content-Type": "text/plain",
            "Host": "httpbin.org",
            "User-Agent": "curl/7.33.0"
          },
          "json": null,
          "origin": "112.7.64.196",
          "url": "http://httpbin.org/post"
        }
#### The actual behavior of AnyProxy

curl: (6) Could not resolve host: post
curl: (6) Could not resolve host: data'
{
  "args": {},
  "data": "'original",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "9",
    "Content-Type": "text/plain",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.33.0"
  },
  "json": null,
  "origin": "112.7.64.196",
  "url": "http://httpbin.org/post"
}
#### The log of the error

示例中是这样：curl -H "Content-Type: text/plain" -X POST -d 'original post data' http://httpbin.org/post
这里-d后单引号应该改为双引号，就没有问题了，sample需要修改一下！

**Comment by codingfishman** [comment]
@tianlanse66 
  谢谢反馈，我们会进行更正
