### ISSUE TITLE
SUGGESTION: add color to the http request which one hits the rule of proxy

### ISSUE THREAD

**Issue by woodsrong** [alibaba/anyproxy#28]
在规则配置中增加一栏颜色选项
* 方便快速知道是否有命中代理规则
* 甚至可以通过颜色来区分命中了哪些规则

**Comment by ottomao** [comment]
这块已经在规划了，当前的想法是在web ui里增加配置，允许修改某条记录的颜色or增加一个icon标识这条记录

**Comment by woodsrong** [comment]
修改某条记录，请问这个filter的规则是如何规划的

**Comment by ottomao** [comment]
通过rule的接口配置，比如开放一个  function markRecord(req,res){ return "#F00" }

**Comment by woodsrong** [comment]
明白了，赞一个，可以满足需求
