### ISSUE TITLE
ip.address函数获取到局域网ip，不能获取真正的外网ip,导致服务外网不可用

### ISSUE THREAD

**Issue by sunguide** [alibaba/anyproxy#280]
请使用127.0.0.1解决

**Comment by codingfishman** [comment]
@sunguide 
   请问使用场景是什么？外网服务是指对外提供的AnyProxy服务吗

**Comment by tianrking** [comment]
您好 我也有这个问题 默认配置文件路径在哪  npm直接装的  我想监听0.0.0.0 然后外网使用

**Comment by codingfishman** [comment]
@tianrking 
   代理虽然监听的是127.0.0.1, 但是如果你在另一台机器，通过本机的外网ip应该是可以访问到的，不知道这是不是你所说的“外网ip”？

**Comment by codingfishman** [comment]
暂时关闭issue，有需要可再次打开
