### ISSUE TITLE
启动anyproxy --host ip时，指定ip不生效

### ISSUE THREAD

**Issue by AbnerPing** [alibaba/anyproxy#281]
指定这个ip，anyproxy --host 10.19.84.46 --intercept --port 8888 --rule ./TestRule.js
但是启动后，仍然显示以下ip
this is a rule for sdk automated testing
Anyproxy rules initialize finished, have fun!
The WebSocket will not work properly in the https intercept mode :(
GUI interface started at : http://10.18.61.92:8002/
Http proxy started at 10.18.61.92:8888

#### 

####

**Comment by codingfishman** [comment]
@AbnerPing 
  启动参数中的`host`是用来在启动https proxy时，生成证书所用，代理仍然会使用当前机器的ip进行服务（包括127.0.0.1和外网ip），可能不符合你的需要。
  你配置host的用途是什么？也许可以通过其他方式实现。

**Comment by AbnerPing** [comment]
@codingfishman 谢谢你的回复。
电脑连接着网线和wifi，代理获取到的当前ip是有线网络的ip，不知道代理如何获得wifi的ip？
想通过电脑和手机都走wifi的网络取抓包。因为手机连接有线网络后，抓取网络数据包有问题。

**Comment by AbnerPing** [comment]
@codingfishman 谢谢你的回复。
目前有有线网卡和无线网卡，我想指定通过无线网卡来进行抓包。
有什么方式可以实现嘛？

**Comment by AbnerPing** [comment]
问题已解决，多谢。
