### ISSUE TITLE
请教一下如何在beforeSendRequest 设置超时

### ISSUE THREAD

**Issue by shichaowei** [alibaba/anyproxy#282]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

windows
#### The version of the AnyProxy

4.0.4

#### Your expected behavior of AnyProxy

beforeSendRequest怎么设置超时
#### The actual behavior of AnyProxy

不太清楚如何设置
#### The log of the error

假设现有规则：
module.exports = {
  *beforeSendRequest(requestDetail) {
    const localResponse = {
      statusCode: 200,
      header: { 'Content-Type': 'application/json' },
      body: '{"hello": "this is local response"}'
    };
    if (requestDetail.url.indexOf('http://httpbin.org') === 0) {
      return {
        response: localResponse
      };
    }
  },
};
如何设置超时？

**Comment by codingfishman** [comment]
@shichaowei 
  你指的超时是？ AnyProxy可以在指定的时间后将返回转发到浏览器，但是不能控制浏览器自身的超时时间。
