### ISSUE TITLE
能否实现 URI 重定向？

### ISSUE THREAD

**Issue by zhangnew** [alibaba/anyproxy#286]
#### Which platform are you running AnyProxy
Windows 10 x64

#### The version of the AnyProxy
4.0.0-beta18

#### Your expected behavior of AnyProxy
能够实现 URI 的重定向，比如一个程序向 `http://aaa.com/admin` 发请求，我给他转到 `http://bbb.com/admin` ,获取 `bbb.com` 的数据返回给程序。目前 AnyProxy  好像没有这个 feature。

然后我自己试图在 `beforeSendRequest` 里面截获 `http://aaa.com/admin`  这个请求，然后用 nodejs 的
 `request` 模块手动去 `http://bbb.com/admin` 获取数据，然后返回给 `http://aaa.com/admin`。但是由于 nodejs 的异步执行，等不到我获取数据，AnyProxy 就先返回结果了。 

后来尝试使用 `request-promise`  和 `then-request` 也没能实现同步执行。

最后一个思路就是改 HOST 或 DNS 劫持了。

**Comment by zhangnew** [comment]
已经用 `Promise` 实现同步，Closed

**Comment by codingfishman** [comment]
Hi @zhangnew 
  AnyProxy的接口方法已经是异步了，因此你可以直接使用*promise*, 同时针这个场景，你也可以不用自己去请求`http://bbb.com/admin`, 而只需要修改请求路径。 可参见[示例](http://anyproxy.io/cn/#修改请求的目标地址)

**Comment by zhangnew** [comment]
@codingfishman 感谢回复，看了好几天文档没注意到有这个示例（捂脸 :joy:
