### ISSUE TITLE
win7信任证书之后，chrome不能访问网页

### ISSUE THREAD

**Issue by popwalker** [alibaba/anyproxy#287]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
windows7

#### The version of the AnyProxy
4.0.0

#### Your expected behavior of AnyProxy
windows信任证书后能够正常访问互联网

#### The actual behavior of AnyProxy
访问互联网失败，提示我的连接不是私密连接

#### The log of the error
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:53]: will forward to local https server
[AnyProxy Log][2017-12-07 17:44:56]: [internal https]proxy server for github.com established
[AnyProxy Log][2017-12-07 17:44:58]: [internal https]proxy server for api.github.com established
[AnyProxy Log][2017-12-07 17:44:58]: [internal https]proxy server for api.github.com established
[AnyProxy Log][2017-12-07 17:44:58]: [internal https]proxy server for api.github.com established
[AnyProxy Log][2017-12-07 17:44:58]: [internal https]proxy server for api.github.com established
[AnyProxy Log][2017-12-07 17:44:59]: [internal https]proxy server for assets-cdn.github.com established
[AnyProxy Log][2017-12-07 17:44:59]: [internal https]proxy server for assets-cdn.github.com established
[AnyProxy Log][2017-12-07 17:44:59]: [internal https]proxy server for assets-cdn.github.com established
[AnyProxy Log][2017-12-07 17:44:59]: [internal https]proxy server for assets-cdn.github.com established
[AnyProxy Log][2017-12-07 17:44:59]: [internal https]proxy server for avatars0.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:09]: [internal https]proxy server for avatars2.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:09]: [internal https]proxy server for avatars2.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:10]: [internal https]proxy server for camo.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:10]: [internal https]proxy server for avatars0.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:10]: [internal https]proxy server for avatars0.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:10]: [internal https]proxy server for camo.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:10]: [internal https]proxy server for camo.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:15]: [internal https]proxy server for cloud.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:15]: [internal https]proxy server for cloud.githubusercontent.com established
[AnyProxy Log][2017-12-07 17:45:23]: [internal https]proxy server for collector.githubapp.com established
[AnyProxy Log][2017-12-07 17:45:23]: [internal https]proxy server for collector.githubapp.com established
[AnyProxy Log][2017-12-07 17:45:26]: [internal https]proxy server for github.algolia.com established
[AnyProxy Log][2017-12-07 17:45:26]: [internal https]proxy server for github.com established
[AnyProxy Log][2017-12-07 17:45:26]: [internal https]proxy server for github.com established
[AnyProxy ERROR][2017-12-07 17:45:26]: Error: connect ETIMEDOUT 106.11.61.114:60688
[AnyProxy Log][2017-12-07 17:45:26]: received request to: GET wiki.i.azoyagroup.com/rest/mywork/latest/status/notification/count?_=1512639897313
[AnyProxy ERROR][2017-12-07 17:45:26]: Error: connect ETIMEDOUT 74.125.204.139:443
[AnyProxy ERROR][2017-12-07 17:45:26]: Error: connect ETIMEDOUT 106.11.61.114:60688
[AnyProxy Log][2017-12-07 17:45:26]: received https CONNECT request 106.11.61.114
[AnyProxy Log][2017-12-07 17:45:26]: received https CONNECT request 106.11.61.114

访问百度的错误截图：
![image](https://user-images.githubusercontent.com/17463763/33709077-37e7effa-db77-11e7-9f87-7de896cccb02.png)

**Comment by codingfishman** [comment]
@popwalker 
   windows环境上，需要将证书安装到“受信任的企业根证书签发机构”这一栏目下，请帮忙确认路径是不是这个。

**Comment by popwalker** [comment]
@codingfishman 不清楚是什么原因，昨天试了两台电脑，都是不行的，今天又可以了。另外Anyproxy的证书确定是安装在“受信任的企业根证书签发机构”栏目下的

**Comment by codingfishman** [comment]
@popwalker  可能是安装后需要重启。。
