### ISSUE TITLE
failed to invoking web socket on this browser

### ISSUE THREAD

**Issue by wq163** [alibaba/anyproxy#29]
filter 的时候出现这个错误，根本不能过滤

**Comment by ottomao** [comment]
什么浏览器？

**Comment by ottomao** [comment]
顺便再看下浏览器本身有没有挂错代理，比如有没有挂到墙外去了？

**Comment by wq163** [comment]
safari 和 chrome 都一样的，mac 下的

**Comment by wq163** [comment]
safari 和 chrome 都一样的，mac 下的

**Comment by wq163** [comment]
safari 和 chrome 都一样的，mac 下的

**Comment by ottomao** [comment]
这种情况多半是没能连接到AnyProxy的ws接口。可以试着看一下网络请求，看websocket到底连接到了哪里，是不是AnyProxy读错ip地址了，或者是浏览器网络环境错误

**Comment by ottomao** [comment]
另外，应该不是filter出错吧？如果ws接口挂了，界面应该静止不动，看不到任何代理的信息。

**Comment by wq163** [comment]
filter出错，就是随便填了个关键字啊，例如 github

**Comment by ottomao** [comment]
![](https://t.alipayobjects.com/images/rmsweb/T16GVhXhNfXXXXXXXX.jpg)
查看页面源码，看下尾部的这两个变量分别被填了什么值

**Comment by wq163** [comment]
<input type="hidden" id="socketPort" value="8003" /> 
<input type="hidden" id="baseUrl" value="127.0.0.53" /> 
我 telnet 了下这个地址是能通的

**Comment by wq163** [comment]
我发现填了 filter 关键字按回车后，浏览器的地址变成了http://myip:8002/?#  （就是后面多了两个符号）。
这时才弹出failed to invoking web socket on this browser对话框，再看页面源码 socketPort 和 baseUrl 已经变成了${wsPort}和${ipAddress}

**Comment by ottomao** [comment]
原来是回车键触发的，我这里也复现了。稍后排查一下。
谢谢反馈！

**Comment by ottomao** [comment]
bug修掉了，已经发布到v3.7.2，用npm更新一下吧。
