### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by tcrct** [alibaba/anyproxy#291]
Error: connect ECONNREFUSED 127.0.0.1:80
#### Which platform are you running AnyProxy
Windows

#### The version of the AnyProxy
4.0.1

#### Your expected behavior of AnyProxy
打开网面

#### The actual behavior of AnyProxy
网页显示异常信息

#### The log of the error
Error: connect ECONNREFUSED 127.0.0.1:80
at Object.exports._errnoException (util.js:1018:11)
at exports._exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by xgz123** [comment]
同样

**Comment by codingfishman** [comment]
@tcrct @xgz123 
 在访问什么地址的时候出现的这个错误， http://127.0.0.1/ ？

**Comment by qiuyudiwutong** [comment]
访问：http://127.0.0.1:8001/
![image](https://user-images.githubusercontent.com/10629796/34662163-9018dccc-f489-11e7-9e67-c4122966e35e.png)

**Comment by xgz123** [comment]
@codingfishman 嗯。具体忘了，好像是端口占用了

**Comment by codingfishman** [comment]
Hi @xgz123 
  好的，看异常是80端口无法访问，也许是被其他应用使用了。

**Comment by ileadall42** [comment]
这个问题是如何解决的？

**Comment by codingfishman** [comment]
@ileadall42 
 你也遇到了？ 也许是80端口直接被其他应用占用，没有被一个http server 监听

**Comment by guoquanyang** [comment]
[AnyProxy Log][2018-09-04 19:07:23]: Http proxy started on port 8001
[AnyProxy Log][2018-09-04 19:07:23]: web interface started on port 8002
[AnyProxy Log][2018-09-04 19:07:43]: received request to: GET 192.168.1.88:8001/
[AnyProxy ERROR][2018-09-04 19:07:44]: Error: connect ECONNREFUSED 127.0.0.1:80
[AnyProxy Log][2018-09-04 19:07:45]: received request to: GET 192.168.1.88:8001/favicon.ico
[AnyProxy ERROR][2018-09-04 19:07:46]: Error: connect ECONNREFUSED 127.0.0.1:80
[AnyProxy Log][2018-09-04 19:07:49]: received request to: GET 192.168.1.88:8001/
[AnyProxy ERROR][2018-09-04 19:07:50]: Error: connect ECONNREFUSED 127.0.0.1:80
[AnyProxy Log][2018-09-04 19:07:50]: received request to: GET 192.168.1.88:8001/favicon.ico
[AnyProxy ERROR][2018-09-04 19:07:51]: Error: connect ECONNREFUSED 127.0.0.1:80
