### ISSUE TITLE
Show image preview

### ISSUE THREAD

**Issue by whuhacker** [alibaba/anyproxy#30]
If the response is an image, the content of response body will show as `(image)`

![image](https://cloud.githubusercontent.com/assets/1249600/9002700/f87e526a-3799-11e5-985e-5c0d1bed09dc.png)

Can we just show the image preview instead of display `(image)`? Just like the Chrome Dev Tool:

![image](https://cloud.githubusercontent.com/assets/1249600/9002792/bd384e58-379a-11e5-9504-60f773e71f0a.png)

**Comment by ottomao** [comment]
The reason why AnyProxy did not show images is that they take too much space. I'll try to find a way to handle these big files.

**Comment by ottomao** [comment]
Image-preview is now supported. You are welcome to have a try.

![](https://zos.alipayobjects.com/rmsportal/zcfJmMvBUJwnzvw.png@200w)
