### ISSUE TITLE
replaceServerResDataAsync 怎么获取请求参数呢(需要这样的业务)?

### ISSUE THREAD

**Issue by llnyxxzj** [alibaba/anyproxy#300]
Plese fill the template when you reporting a new issue, thanks!
replaceServerResDataAsync: function(req,res,serverResData,callback) 怎么获取请求参数呢(需要这样的业务)?
req.requestData
req._req
都没有获取到相应参数,麻烦指导下

**Comment by codingfishman** [comment]
@llnyxxzj 
  你指的参数是说post或get时，所携带的参数吗？
   AnyProxy提供的`req`对象是一个原始的node request请求，你可以拿到完整的url，或者requestBody。假如你post了一个json，那么这个body就是json字符串，可以进行JSON.parse()操作

**Comment by codingfishman** [comment]
暂时关闭issue，可以参考 [官方文档](http://anyproxy.io/cn/#beforesendrequest) , 或将来再打开
