### ISSUE TITLE
怎样代理HTTPS同时使用rule模块的？

### ISSUE THREAD

**Issue by iseacode** [alibaba/anyproxy#304]
anyproxy --intercept --rule test.js

[AnyProxy WARN][2017-12-25 16:59:44]: both "-i(--intercept)" and rule.beforeDeal
HttpsRequest are specified, the "-i" option will be ignored.
[AnyProxy Log][2017-12-25 16:59:44]: Http proxy started on port 8001
[AnyProxy Log][2017-12-25 16:59:44]: web interface started on port 8002
[AnyProxy Log][2017-12-25 16:59:44]: Active rule is: my customized rule for AnyProxy

**Comment by codingfishman** [comment]
@iseacode 
 如果你的rule文件中定义了`beforeDealHttpsRequest`, 那么是否代理https将完全由这个函数的返回来决定。 如果没有定义这个函数，那么会参考启动AnyProxy时，所传入的 `--intercept`将决定是否代理https。
