### ISSUE TITLE
HTTPS Proxy Interception/OpenSSL  is not working.. Please Help!

### ISSUE THREAD

**Issue by titus-shoats** [alibaba/anyproxy#31]
Hi, I've been playing around with any proxy, everything works, but I cant get https proxy interception to work, I've installed openssl properly for windows. But everytime I run the command anyproxy --root I get errors saying "openssl is not recognized as an internal or external command" . I'm not sure what i'm doing wrong, can anyone please help me with this.. Thanks

I also see the directory 'cert', how can i  use these certificates, ??? Thanks

**Comment by ottomao** [comment]
Hi,
The directory 'cert' is created by AnyProxy to save some certificates. Just keep it there, AnyProxy will handle these files.

As the openssl problem, did you install openssl correctly ? Try to use the command `openssl` in cmd, what will you see ?

**Comment by ottomao** [comment]
https://www.openssl.org/related/binaries.html

http://wiki.openssl.org/index.php/Compilation_and_Installation

Hope these posts could help you install openssl on windows.

**Comment by titus-shoats** [comment]
Yes, I have access and installed openssl on my windows 8 machine, and it does work properly. I can access the commands via by command prompt by typing (openssl version -a), this command shows me tons of openssl options, cipher commands etc.. 

I guess my question would be how do I now generate a anyproxy certificate/key .. As im following the directions I followed the first step 
1)which is to install openssl.. (Completed)
2) next is to generate a rootCA,  .. here's where I'm confused, should I do it with openssl, or should I do it with anyproxy server.. 

When I type anyproxy --root as your instructions say,  then I get a error that says "openssl is not recognized as an internal or external command"

It also says root generated at C\Users\Myname\.anyproxy_certs\
but when I check in that directory, no certificate is there :(

And within my GUI when I click on download rootCA.crt link, then I see text saying this
 "can not file rootCA ,plase use anyproxy --root to generate one"

So I know for a for sure I have openssl installed because I can use openssl commands on my cmd, and I also made a test certificate and key earlier. I;m just not sure how to get anyproxy to create one.. I'm not sure what I'm doing wrong..

**Comment by ottomao** [comment]
The way to generate a certificate is using `anyproxy --root` . You have done that correctly.
Actually, AnyProxy generates the certificate by `spawn` a batch file. So I guess there is some problem with the cmd environment. Would you please run the following test code in your cmd and see whether Node.js could start openssl as expected ?

```javascript
//Test spawn
var spawn = require('child_process').spawn,
	fs    = require("fs");

fs.writeFileSync("test.cmd","openssl version -a");
spawn("test.cmd",[],{cwd:process.cwd(),stdio: 'inherit'});
```

**Comment by titus-shoats** [comment]
I'm not sure whats going on but when I type the above code in my node command
var spawn = require('child_process').spawn,
    fs    = require("fs");       

I get an error "undefined".. This is weird being that I thought child_process module is bundled with node.js by default.

**Comment by ottomao** [comment]
Save it to test.js, then run `node test.js`

**Comment by titus-shoats** [comment]
Yea, im getting the same error. 
"openssl is not recognized as an internal or external command"
This is really weird because I can access openssl without any problems via command by itself. But when I try to access it with node.js it gives me errors.

**Comment by ottomao** [comment]
Would there be any problem with your %path% config ? How about run the test scripts in your openSSL  folder ? 

This post on StackOverflow is pretty similar with yours.

**Comment by codingfishman** [comment]
Close the issue for now, will reopen if more discussions are joined.
