### ISSUE TITLE
提示缺少模块  crypto-js

### ISSUE THREAD

**Issue by hqtc123** [alibaba/anyproxy#311]
#### Which platform are you running AnyProxy
Windows

#### The version of the AnyProxy
4.0.4

#### Your expected behavior of AnyProxy
跑起来

#### The actual behavior of AnyProxy
Error: Cannot find module 'crypto-js'

我已经装上了这个模块啊：

cnpm install -g crypto-js
Downloading crypto-js to C:\Program Files\nodejs\node_modules\crypto-js_tmp
Copying C:\Program Files\nodejs\node_modules\crypto-js_tmp\_crypto-js@3.1.9-1@crypto-js to C:\Program Files\nodejs\node_modules\crypto-js
Installing crypto-js's dependencies to C:\Program Files\nodejs\node_modules\crypto-js/node_modules

**Comment by codingfishman** [comment]
Hi @hqtc123 
  是在哪一步提示缺少这个模块，是不是安装node_modules文件有缺失？
  另如果安装模块，需要在当前目录安装， `cnpm install crypto-js`, 不用加 `-g` 参数

**Comment by hqtc123** [comment]
执行 anyproxy -i --rule=xx.js 的时候~
![qq 20180103223406](https://user-images.githubusercontent.com/2255751/34524371-499666b8-f0d6-11e7-81c9-b11e17f76ae9.png)

**Comment by zhuweiyou** [comment]
不要加 -g，当前目录安装

**Comment by hqtc123** [comment]
OK
