### ISSUE TITLE
功能建议：--rule 支持多个rule.js.  Hope  "--rule" parameter can support multiply rule file 

### ISSUE THREAD

**Issue by cdz620** [alibaba/anyproxy#313]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

mac os: 10.12.6 (16G1114)  

#### The version of the AnyProxy

4.0.0-beta18

#### Your expected behavior of AnyProxy

场景是：我希望针对多个不同网站的rule可以放在不同的rule.js, 不想将多个太多的rule写到同一个js文件。
目前的解决方案有如下：
1. 不同网站的rule分开存放，每次需要用到哪个rule.js, 关闭anyproxy 重新指定新的rule.js运行。 痛点是：频繁start/stop anyproxy, 频繁修改--rule 参数 
2. 所有的rule都放到同一个rule.js, 一次启动anyproxy即可。 痛点：太多rule 放在一个rule.js, 管理起来很恶心，无法忍受。

想达到的预期效果：启动option rule 是个Array，能支持多个rule.js
我看了官方文档：`rule {object} 自定义规则模块`, 目前好像只能用一个rule.js

#### The actual behavior of AnyProxy

 启动option rule 是个Array，能支持多个rule.js

**Comment by codingfishman** [comment]
Hi @cdz620 
  谢谢建议，我们也在实现这个功能，希望近期能加上

**Comment by diem98** [comment]
这个还有计划吗
