### ISSUE TITLE
Windows下Rule规则中修改请求的post数据没有起作用

### ISSUE THREAD

**Issue by bigcatpan** [alibaba/anyproxy#316]
您使用的是哪个平台的系统，Mac，Windows，或者Linux 
Windows 7

您使用的是AnyProxy为哪个版本 
4.0.4

**Comment by codingfishman** [comment]
@bigcatpan 
 可否将rule也一起贴出看看

**Comment by bigcatpan** [comment]
不好意思，今天又重试了一下是可以的
