### ISSUE TITLE
When multiple instance of anyproxy are launched 

### ISSUE THREAD

**Issue by JulienBeaudeau** [alibaba/anyproxy#317]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
On Windows  OS 

#### The version of the AnyProxy
Version 3.10.2

#### Your expected behavior of AnyProxy
Crash when multiple instances of any proxy are launched simultaneously

#### The actual behavior of AnyProxy
Multiple instances of any proxy can be  launched simultaneously

#### The log of the error
When one instance of anyproxy is destroyed, all the caches files of anyproxy instances are destroyed. So when another instance is still running, it creates conflicts.
-> fix it by destroying only the cache folder of the destroyed anyproxy instance.

An internal fix number is used by anyproxy to communicate with the server (40000)
-> fix it by generating a random number within a range or using 
    server.address().port that retrieve a port automatically

You will find the fix  attached

  
[lib.zip](https://github.com/alibaba/anyproxy/files/1618117/lib.zip)

**Comment by codingfishman** [comment]
Hi @JulienBeaudeau 
  Thanks for the fix, the port conflict and caches folder conflict shall be fixed in the 4.x version, can you update and take a try?

**Comment by codingfishman** [comment]
close the issue for now
