### ISSUE TITLE
可以支持wss么

### ISSUE THREAD

**Issue by e0v1a** [alibaba/anyproxy#319]
现在不支持wss，也无法通过规则直接放行wss，导致代理的站点请求中包含wss就整体不可用了

**Comment by codingfishman** [comment]
Hi @e0v1a 
  我们正在进行相应支持，包括wss及ws

**Comment by LCJ-MinYa** [comment]
同求支持～

**Comment by liugc** [comment]
同求支持～

**Comment by tangxiadi** [comment]
同求支持～

**Comment by APPLLEJN** [comment]
求

**Comment by codingfishman** [comment]
AnyProxy新增对ws和wss的支持，可通过命令行或npm模块方式启动
```
anyproxy --ws-intercept
```
具体配置可参见[官方文档](http://anyproxy.io/cn/#%E4%BD%9C%E4%B8%BAnpm%E6%A8%A1%E5%9D%97%E4%BD%BF%E7%94%A8)
欢迎使用和反馈
