### ISSUE TITLE
Is there a way to handle all HTTP traffic since proxyServer.start() ?

### ISSUE THREAD

**Issue by sanlengjingvv** [alibaba/anyproxy#320]
For example , When Call `proxyServer.har()`,  returns HAR content representing all the HTTP traffic passed through the proxy.

**Comment by codingfishman** [comment]
Hi @sanlengjingvv 
  So what does the `proxyServer.har()` do since the start, will this break the normal process of all sites? How about accomplish this by the **rule** interface?

**Comment by sanlengjingvv** [comment]
I now do the following
```JavaScript
*beforeSendResponse(requestDetail, responseDetail) {
    if (requestDetail.url.indexOf('https://example.com') === 0) {
        const request = JSON.parse(requestDetail.requestData.toString())
        const responese = JSON.parse(responseDetail.response.body.toString())
        saveToDatabase(request, responese)
        return null
    }
}
```

**Comment by codingfishman** [comment]
@sanlengjingvv 
   Thanks, is this what you want, to control the logic with specified url?

**Comment by sanlengjingvv** [comment]
In event tracking automation test，I need assert app upload correct data.  For example，when an element shown, trigger a request :
```
 POST /tracking

{"element-id": 2233,
 "event": "show"}
```
record these requests for use by other tools

**Comment by codingfishman** [comment]
Thanks, so the rule interface can handle the case, the issue can be closed
