### ISSUE TITLE
Mac安装最新版anyproxy报错

### ISSUE THREAD

**Issue by KilluaChen** [alibaba/anyproxy#322]
<img width="1358" alt="qq20180120-122535 2x" src="https://user-images.githubusercontent.com/12621893/35179941-df64c02a-fddf-11e7-92ca-540865641549.png">

**Comment by tangxiadi** [comment]
Win7报同样的错：
![123](https://user-images.githubusercontent.com/9555093/35181969-08b00fd0-fe07-11e7-860f-69c9be87ac6f.png)

**Comment by tangxiadi** [comment]
我在Win7安装报同样的错，现在解决了，原因是没有操作 %AppData%\npm\node_modules 的权限，不知道是怎么回事。知道原因后，对着这个文件夹用 takeown /r /f 获取权限，然后用npm uninstall anyproxy卸载，再用npm install -g anyproxy安装就好了。
你这个图片我看见你用sudo提权了，就不知道是不是权限的问题了。

**Comment by KilluaChen** [comment]
@tangxiadi 给了777权限还是一样的报错,不知道具体什么问题~

**Comment by codingfishman** [comment]
@KilluaChen 
  你可否尝试先删除这个目录，然后再重新安装看看？

**Comment by KilluaChen** [comment]
node版本升级到`9.4.0`安装成功 :)

**Comment by JinglingZhu** [comment]
我升级到了9.4.0，依然显示相同的错误

**Comment by codingfishman** [comment]
@JinglingZhu , 可否先将现有的版本删除再试试
