### ISSUE TITLE
what can i do about 'Buffer' requestData

### ISSUE THREAD

**Issue by KyleQiao1992** [alibaba/anyproxy#334]
I use post request which is contain requestData(Body),but when I console it ,it likes this  
requestData: <Buffer 5b 7b 22 63 61 74 65 67 6f 72 79 22 3a 22 64 61 74 61 5f 73 64 6b 5f 69 73 6d 61 72 74 22 2c 22 73 64 6b 5f 76 65 72 22 3a 22 33 2e 33 2e 32 22 2c 22 ... >,

I want to return to the original context , what can I do about it

**Comment by codingfishman** [comment]
@KyleQiao1992 
  If you know what the the real data behind the `Buffer` data, you can unzip it back by nodejs Buffer API, such as convert it back to string
