### ISSUE TITLE
请问怎么装3.x版本，直接npm下载的都是4.x版本的

### ISSUE THREAD

**Issue by 1029219814** [alibaba/anyproxy#336]
Plese fill the template when you reporting a new issue, thanks!

**Comment by 1029219814** [comment]
请问，怎么装3.x版本…网上没找到教程

**Comment by 1029219814** [comment]
请问有人嘛

**Comment by 1029219814** [comment]
请问有人嘛。。怎么下载3.x的版本。。

**Comment by codingfishman** [comment]
可以通过npm安装历史版本，`npm install@anyproxy@3.10.3`

**Comment by uscoot** [comment]
npm install -g anyproxy@4.00.0
