### ISSUE TITLE
请问我的anyproxy，注入js代码时，没有反应，是什么原因呢

### ISSUE THREAD

**Issue by 1029219814** [alibaba/anyproxy#337]
try {
                var reg = /var msgList = \'(.*?)\';/;//定义历史消息正则匹配规则（和第一种页面形式的正则不同）
                var ret = reg.exec(serverResData.toString());//转换变量为string
                HttpPost(ret[1],req.url,"/showBiz");//这个函数是后文定义的，将匹配到的历史消息json发送到自己的服务器
                var http = require('http');
                http.get('http://127.0.0.1:8080/getWxHis', function(res) {//这个地址是自己服务器上的一个程序，目的是为了获取到下一个链接地址，将地址放在一个js脚本中，将页面自动跳转到下一页。后文将介绍getWxHis.php的原理。
                        res.on('data', function(chunk){					
							//serverResData = serverResData.toString().replace('</html>', '</html>' + chunk);							
							serverResData = serverResData.toString().replace('</body>', '<script>alert(1);</script></body>');	
							//serverResData = serverResData + chunk;						
							console.log(serverResData);	
							callback(serverResData);//将返回的代码插入到历史消息页面中，并返回显示出来					
                        })
                    });

**Comment by 1029219814** [comment]
版本3.10

**Comment by codingfishman** [comment]
@1029219814 
是不是在`replaceServerResDataAsync`里面进行的操作？ 操作后的页面里有没有你插入的这一段script代码？

这段代码目测是插入到页面的顶部，在html标签之前，如果script正常插入你可能还需要考虑其位置是否会执行

**Comment by jigaowan** [comment]
微信做了处理，这个方法已经失效了

**Comment by 1029219814** [comment]
可以了，已经解决了。。谢谢，是callback的原因

**Comment by codingfishman** [comment]
@jigaowan 
  AnyProxy的4.x版本更新了API，已经没有这个方法了，新的接口可参考[官网-rule接口](http://anyproxy.io/cn/#rule%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)
