### ISSUE TITLE
代理了ws会自动关闭

### ISSUE THREAD

**Issue by godhh** [alibaba/anyproxy#342]
[AnyProxy Log]: original ws closed with code: 1001 and reason: unexpected server response (403)

mac 
"anyproxy": "^4.0.6",
开的系统http代理 127.0.0.1：8001，https没开
作为node模块使用，配置如下
const options = {
    port: 8001,
    webInterface: {
        enable: true,
        webPort: 8002
    },
    forceProxyHttps: false,
    dangerouslyIgnoreUnauthorized: true,
    wsIntercept: true,
    silent: false
}
。
使用http://coolaf.com/tool/chattest测试时， 会自动断开ws链接， 我。。。
是哪里配错了吗？

**Comment by codingfishman** [comment]
@godhh  配置是正常的，是因为这个网站对websocket的origin进行了检查，需要在代理时也将相应字段加上。 我们看看如何还原原始请求的头部比较合理

**Comment by codingfishman** [comment]
已支持透传非websocket协议相关的头部字段
