### ISSUE TITLE
树莓派安装的时候报错

### ISSUE THREAD

**Issue by Sunraych** [alibaba/anyproxy#346]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

树莓派Debain

#### The version of the AnyProxy

最新的

#### Your expected behavior of AnyProxy

安装成功
#### The log of the error

npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
npm ERR! write after end
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/ajv-38b79ff8/dist/ajv.min.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/iconv-lite-89eb13da/encodings/tables/cp949.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/localforage-316828f6/test/test.polyfill.html'
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/localforage-316828f6/test/test.require.html'
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/localforage-316828f6/test/test.browserify.html'
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/localforage-316828f6/test/test.webpack.html'
npm WARN tar ENOENT: no such file or directory, open '/usr/local/node/lib/node_modules/.staging/localforage-316828f6/test/photo2.jpg'
npm WARN npm@2.15.12 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting ajv@^5.1.0:
npm ERR! sha1-c7Xuyj+rZT49P5Qis0GtQiBdyWU= integrity checksum failed when using sha1: wanted sha1-c7Xuyj+rZT49P5Qis0GtQiBdyWU= but got sha512-h7ROysukBZ9xbOEPGhicubRES7VO/XPB2wWxCfuu23rRxyHKitl+MutilpoHDuI48q1TL9sWNTZt6WUR0hRzVw== sha1-5nP7cmXG2vJvREuwx43fbmRQja4=. (356371 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sunruichuan/.npm/_logs/2018-03-16T02_30_45_295Z-debug.log

**Comment by codingfishman** [comment]
要不要做一下 npm cache clean看看？

**Comment by Sunraych** [comment]
已经解决了，没有sudo导致的。npm没有软连
