### ISSUE TITLE
Anyproxy 4.0.6 报错 Could not locate the bindings file. 不能正常启动

### ISSUE THREAD

**Issue by lizwangying** [alibaba/anyproxy#349]
Mac 系统

Anyrpoxy 4.0.6

期待能够正常启动AnyProxy，但是呢，报了个错，很多同事也报了这个错，无解啊

![image](https://user-images.githubusercontent.com/13509775/37769068-c73148f6-2e0a-11e8-8660-0e51bf97c898.png)
没有Log，期待解决，感激不尽

**Comment by codingfishman** [comment]
@lizwangying 
可否提供一个截图？

**Comment by codingfishman** [comment]
@lizwangying 
  我搜了一下类似的日志，似乎和snappy有关，你可以看看[这个issue](https://github.com/dudleycarr/snappystream/issues/4)是否有帮助, 包括在 snappy下面执行“node-gyp rebuild”， 或者整体执行 npm rebuild。

另外也请提供一下node和npm的版本，看看是否必现

**Comment by lizwangying** [comment]
😄  谢谢功夫熊猫指路，炒鸡开心,这个问题解决了。
我试了 npm rebuild , 但是提醒我是python 3.6 ,要切换到 python 2.7 ，我切换回去执行了 npm rebuild 就好了，太开心了，我去救救其他同事们。
再次谢谢。
