### ISSUE TITLE
Q. Can I choose between multiple network adapters?

### ISSUE THREAD

**Issue by myso-kr** [alibaba/anyproxy#357]
Is it possible to select one of many network adapters to communicate?

In the case where two proxy servers are opened in one server composed of Windows 10 and one local network and two public networks are connected, a communication request inbound through the local network is transmitted to one public network of two public networks I want to implement an outbound environment through the IP.

Since the public network IP can be changed from time to time, it is difficult to use it as access information.

**Comment by codingfishman** [comment]
Hi @myso-kr 
  So you use AnyProxy to bridge local network to the public networks, and the public networ IP are changed by time, did I get your point correctly?

  Is that possible to choose the two adapters by System interface instead of the IP directly then..?

**Comment by myso-kr** [comment]
Hi @codingfishman 

i solved. this using below codes.

-----

## idea.

lib/requestHandler.js: 83
```
//send request
const proxyReq = (/https/i.test(protocol) ? https : http).request(options, (res) => { ...
```
-----

## refs.

https://nodejs.org/api/http.html#http_http_request_options_callback
```
localAddress <string> Local interface to bind for network connections.
```
-----

## edit.

lib/requestHandler.js: 290
```
const options = {
  localAddress: userRule.localAddress, // Added localAddress
  hostname: urlPattern.hostname || req.headers.host,
  port: urlPattern.port || req.port || (/https/.test(protocol) ? 443 : 80),
  path,
  method: req.method,
  headers: req.headers
};
```
