### ISSUE TITLE
The npm version in the package.json dependency is too old.

### ISSUE THREAD

**Issue by majorcool** [alibaba/anyproxy#358]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
Mac

#### The version of the AnyProxy

4.0

#### Your expected behavior of AnyProxy

Is it necessary to specify npm's version ("^2.7.0" in the anyproxy repo) in the package.json dependency? This would lock the npm version at 2.X in any project that require anyproxy! Then the old version npm could cause serious problem while almost every modern project may set their engines.npm to >=3.0 in their package.json. 

#### The actual behavior of AnyProxy

AnyProxy dependency specify the npm version to 2.x, this is not a good idea.

**Comment by codingfishman** [comment]
remove the 'npm' from package.json
