### ISSUE TITLE
anyproxy 4.0.8 4.0.9 跑不起来

### ISSUE THREAD

**Issue by ddbbqqpp** [alibaba/anyproxy#364]
估计没有经过纯净的安装测试就发版了？
4.0.8
4.0.9
anyproxy-ca
Error: Cannot find module 'inquirer'
4.0.8
根本就跑不起来

**Comment by looping84** [comment]
npm install inquirer -g

**Comment by codingfishman** [comment]
@ddbbqqpp 
  抱歉，已发布修复版，我们将完善这个证书的测试用例，避免功能错误

**Comment by codingfishman** [comment]
新增cli的单测： https://github.com/alibaba/anyproxy/pull/366
