### ISSUE TITLE
Remote server use https on 80 port

### ISSUE THREAD

**Issue by dishuostec** [alibaba/anyproxy#37]
服务器被设置为在80端口监听https请求，anyproxy会自动把80端口改为443，导致请求超时。

**Comment by wuchangming** [comment]
把80端口明文？

**Comment by codingfishman** [comment]
Hi @dishuostec 
 **抱歉，这条issue过了太久。。**
 请问是否还有遇到这种情形？ 80端口一般用于http，443设置为80端口是基于什么考虑呢？

**Comment by dishuostec** [comment]
记不清当时为什么要用80端口了，这个问题已经通过修改源码解决啦
