### ISSUE TITLE
安卓部分机型抓包ERR_SSL_SERVER_CERT_BAD_FORMAT报错

### ISSUE THREAD

**Issue by ffc518** [alibaba/anyproxy#375]
安卓三星机型在设置anyproxy代理后，访问h5时，报ERR_SSL_SERVER_CERT_BAD_FORMAT，证书已经安装，native可以正常访问

**Comment by codingfishman** [comment]
@ffc518 
  是不是只针对特定的网址？ 另外AnyProxy的版本也请提供一下。
