### ISSUE TITLE
Is there any way to pause the request before sending to server and then forward it or drop it

### ISSUE THREAD

**Issue by impraveensingh** [alibaba/anyproxy#378]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
Windows

#### The version of the AnyProxy
4.0.9

#### Your expected behavior of AnyProxy
Is there any way to pause the request before sending to server and then forward it or drop it. 
For example in burp suit , in that we can turn intercept on and off which lets us pause and forward request.
I am using electron to develop simple intercept project.

**Comment by codingfishman** [comment]
Hi @impraveensingh 
  Maybe the [Rule Interface](http://anyproxy.io/#beforesendrequest) can help you, by rule you can do the program before sending the request.

**Comment by cuixiping** [comment]
Try this

```
* beforeSendRequest(requestDetail) {
  let delay = new Promise(resolve => {
    setTimeout(() => resolve(null), 5000);
  });
   return yield delay;
},
```
