### ISSUE TITLE
Can't start anyproxy as a systemd unit

### ISSUE THREAD

**Issue by kryztoval** [alibaba/anyproxy#385]
Base System: Centos 7.5.1804
AnyProxy Version 4.0.10

Expected Behaviour
I created a simple unit and started it with the command
ExecStart=/usr/local/bin/anyproxy
The expected behaviour was for it to start with no issues

Current behaviour
The service fails with a path error.

Log of the error:
systemd[1]: Starting HTTP(s) proxy server...
anyproxy[26223]: path.js:39
anyproxy[26223]: throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
anyproxy[26223]: ^
anyproxy[26223]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
anyproxy[26223]: at assertPath (path.js:39:11)
anyproxy[26223]: at Object.join (path.js:1157:7)
anyproxy[26223]: at getAnyProxyHome (/usr/local/lib/node_modules/anyproxy/lib/util.js:38:21)
anyproxy[26223]: at Object.module.exports.getAnyProxyPath (/usr/local/lib/node_modules/anyproxy/lib/util.js:47:16)
anyproxy[26223]: at Object.<anonymous> (/usr/local/lib/node_modules/anyproxy/lib/ruleLoader.js:8:29)
anyproxy[26223]: at Module._compile (internal/modules/cjs/loader.js:678:30)
anyproxy[26223]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
anyproxy[26223]: at Module.load (internal/modules/cjs/loader.js:589:32)
anyproxy[26223]: at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
anyproxy[26223]: at Function.Module._load (internal/modules/cjs/loader.js:520:3)
systemd[1]: http-proxy.service: main process exited, code=exited, status=1/FAILURE

I believe it is trying to find out a path from something that is not being initialized, I tried setting up the WorkingDirectory in the service, making a bash file, setting up some environment variables and I could not make it work. I am willing to try specific suggestions even if I already tried them before.

I was wondering if it could be passed as a parameter so the working directory, the cache directory and the certificates can be set specifically instead of trying to figure it out? idk.

**Comment by codingfishman** [comment]
@kryztoval 
  According to the stack, this might relates to the  *HOME* directory locating during startup.

  AnyProxy get the path by `process.env.HOME || process.env.USERPROFILE`, so I guess the value is `undefined` when started in this way.

  Can you set the variable manually before starting AnyProxy for now? We'll need a new way to locate home direcotry.

**Comment by codingfishman** [comment]
`process.env.HOME || process.env.USERPROFILE`,  one of these two, I guess.

**Comment by kryztoval** [comment]
@codingfishman Wow, adding the Environment variable to the systemd unit worked like a charm! Thank you!

```
[Unit]
Description=Anyproxy service

[Service]
Environment=HOME=/opt/anyproxy/
ExecStart=/usr/local/bin/anyproxy

[Install]
WantedBy=multi-user.target

```
