### ISSUE TITLE
明文解析HTTPS没有起作用

### ISSUE THREAD

**Issue by kaizhuQin** [alibaba/anyproxy#40]
已经生成证书，客户端也安装 ，已经信任。
anyproxy --intercept
重新启动之后，并没有达到明文解析https的作用。反而导致了https的请求失败。

不知道，这个是要怎么用？

**Comment by ottomao** [comment]
你的用法是正确的，生成证书-安装-信任-intercept

请求失败是怎么报错的？软硬件环境是?
如果是app里，不妨把页面放到手机端浏览器，看看报错的内容是什么。

**Comment by kaizhuQin** [comment]
![qq 20151116104610](https://cloud.githubusercontent.com/assets/4590307/11173315/984ffc58-8c4f-11e5-9fa5-74b5066569e8.png)
![qq 20151116104747](https://cloud.githubusercontent.com/assets/4590307/11173319/a5785876-8c4f-11e5-9372-14d44f3bd8e8.png)

第一张图 是可以正常获取并解析到https的请求。
第二张图 是不能正确解析到https的请求。因为这个是app的接口，app这边直接就获取不到任何的数据了。这里也看不见请求的具体链接是啥，只看见了域名。

环境：centos 6.3 64位

**Comment by ottomao** [comment]
正常解析和不正常解析的区别在哪里？调整了什么配置？还是不同的环境？
我猜是你的app有特殊的证书校验配置，它不信任被AnyProxy替换的证书。

**Comment by kaizhuQin** [comment]
sudo anyproxy --intercept 可以正常解析出其他https请求。anyproxy --intercept直接跳过了https，这个应该查找证书的时候，权限的问题。
```
app有特殊的证书校验配置，它不信任被AnyProxy替换的证书
```
应该是这个原因，因为目前只发现这个app的https接口是这样子的。其他https的接口都是可以正确解析到。
那么，对于“不信任被AnyProxy替换的证书”的请求还其他方式可以解析到吗？

**Comment by ottomao** [comment]
目测很难，这是https的安全性所在啊.....要不改改app的源码，调整下安全策略？

**Comment by kaizhuQin** [comment]
```
这是https的安全性所在啊
```
只是看见绝大部分的https信任被AnyProxy替换的证书。觉得比较诧异。
谢谢。
