### ISSUE TITLE
copy as curl，body缺少引号

### ISSUE THREAD

**Issue by lionel126** [alibaba/anyproxy#407]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
centos

#### The version of the AnyProxy
4.0.10

#### Your expected behavior of AnyProxy
curl可以正常执行

#### The actual behavior of AnyProxy
由于curl 命令-d后的body字符串里有&，curl执行失败

**Comment by codingfishman** [comment]
@lionel126 也欢迎你来PR哈
