### ISSUE TITLE
anyProxy crash

### ISSUE THREAD

**Issue by tunnyios** [alibaba/anyproxy#408]
系统：Mac OS 10.13.6
版本：anyproxy 4.0.10
nodejs版本：v10.5.0
问题描述：
安装配置好后，设置https代理，刷新网页测试，经常会出现报错，直接导致anyproxy崩溃
日志见图片
<img width="1051" alt="anyproxy 1" src="https://user-images.githubusercontent.com/10787204/43042838-1f12fdf4-8db9-11e8-970a-2c2f494b553b.png">
<img width="887" alt="anyproxy 2" src="https://user-images.githubusercontent.com/10787204/43042840-297d88d6-8db9-11e8-9809-94150a1209d9.png">

**Comment by codingfishman** [comment]
Hi @tunnyios 
当crash时，有针对特别的URL吗，第一张截图的错误类似连接被重置，第二张类似连接被中断，有没有能看到在哪个页面的时候，触发这个crash的概率比较大？

**Comment by tunnyios** [comment]
我觉得很频繁，监听https，监听手机或者PC，然后浏览器随便打开一些网站就会crash。

**Comment by liruige01** [comment]
我也遇到了这个问题 ，不知道触发了哪个链接之后 服务就挂了

**Comment by shiny** [comment]
![image](https://user-images.githubusercontent.com/117487/45692115-95edb800-bb8c-11e8-9d46-2b1ab6108c32.png)
经常崩溃

**Comment by ottomao** [comment]
近期发布版本已经fix。
