### ISSUE TITLE
由于访问某些不能访问的网站而崩溃

### ISSUE THREAD

**Issue by heqyoufree** [alibaba/anyproxy#410]
系统：Windows 10 17134.165

版本：AnyProxy 4.0.5
nodejs 10.7.0

建议：不能处理的url应跳过

描述：访问Google等网站时直接崩溃

[AnyProxy Log][2018-07-31 10:55:18]: Http proxy started on port 8889
[AnyProxy Log][2018-07-31 10:55:18]: web interface started on port 8002
[AnyProxy Log][2018-07-31 10:55:18]: received https CONNECT request play.googleapis.com
[AnyProxy Log][2018-07-31 10:55:18]: will forward to local https server
[AnyProxy Log][2018-07-31 10:55:19]: received https CONNECT request www.google.com
[AnyProxy Log][2018-07-31 10:55:19]: received request to: GET connectivitycheck.gstatic.com/generate_204
[AnyProxy Log][2018-07-31 10:55:19]: will forward to local https server
[AnyProxy Log][2018-07-31 10:55:19]: [internal https]proxy server for www.google.com established
[AnyProxy ERROR][2018-07-31 10:55:19]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: read ECONNRESET
    at TCP.onread (net.js:660:25)
[AnyProxy Log][2018-07-31 10:55:19]: destorying https connection : 127.0.0.1:8051
[AnyProxy Log][2018-07-31 10:55:19]: endding https cltSocket : 127.0.0.1:8051
[AnyProxy Log][2018-07-31 10:55:19]: clearing cache file...
[AnyProxy Log][2018-07-31 10:55:19]: closing webserver...

此问题尤其表现在访问Google服务器上。手机会在后台访问Google来获取当前网络状况且没有选项停止。希望可以指定Anyproxy直接跳过某些网址。

**Comment by EndPoem** [comment]
@codingfishman 访问新链接会创建证书而且会卡顿，但是大部分链接都是手机后台自动发起的并且不需要，但是也会卡顿，所有能不能跳过那些链接，只选择自己需要的链接加载证书。

**Comment by codingfishman** [comment]
@EndPoem 
  AnyProxy新版优化了证书创建环节，可以很大程度上提高https的首次加载速度了，可以试试看；
  但是和请求被reset后进而AnyProxy关闭还不是一样的原因，单纯的reset应该不会导致停止运行。

@liruige01 
在RESET之前，还有其他错误信息吗

**Comment by liruige01** [comment]
[AnyProxy Log][2018-08-29 19:59:39]: [internal https]proxy server for pagead2.googlesyndication.com established
[AnyProxy Log][2018-08-29 19:59:39]: received request to: GET pagead2.googlesyndication.com/pagead/js/r20180822/r20180604/osd.js
[AnyProxy Log][2018-08-29 19:59:41]: received https CONNECT request hm.baidu.com
[AnyProxy Log][2018-08-29 19:59:41]: will forward to local https server
[AnyProxy Log][2018-08-29 19:59:41]: [internal https]proxy server for hm.baidu.com established
[AnyProxy Log][2018-08-29 19:59:41]: received request to: GET hm.baidu.com/hm.gif?cc=0&ck=1&cl=32-bit&ds=414x736&vl=672&ep=%7B%22netAll%22%3A525%2C%22netDns%22%3A0%2C%22netTcp%22%3A516%2C%22srv%22%3A269%2C%22dom%22%3A13729%2C%22loadEvent%22%3A131193%7D&et=87&ja=0&ln=zh-cn&lo=0&rnd=1099844907&si=8f954ee5434eb2c31d06d982f3978708&v=1.2.34&lv=1
[AnyProxy ERROR][2018-08-29 19:59:43]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: read ECONNRESET
    at TCP.onread (net.js:656:25)
[AnyProxy Log][2018-08-29 19:59:43]: destorying https connection : 127.0.0.1:62993
[AnyProxy Log][2018-08-29 19:59:43]: endding https cltSocket : 127.0.0.1:62993
[AnyProxy Log][2018-08-29 19:59:43]: clearing cache file...
[AnyProxy Log][2018-08-29 19:59:43]: ==>>> clearing cache 
[AnyProxy Log][2018-08-29 19:59:43]: closing webserver...

如上，我是通过anyproxy --intercept 命令启动的，没有修改rule_default.js文件，每次启动都能运行一会，不知道点了哪个链接后就会突然断开了 ，这个是什么原因呢

**Comment by xiebl** [comment]
确实会经常莫名其妙抛出异常而导致服务中断

**Comment by ottomao** [comment]
#427 中一起跟进。刚发布的4.0.13应该已经fix。
