### ISSUE TITLE
请问下如何保存抓包信息

### ISSUE THREAD

**Issue by 515783034** [alibaba/anyproxy#417]
### 期望：通过anyproxy实现抓包后，将抓包的信息保存到其他位置(文件等)，方便Python获取抓包的信息

不知道别人有没有这样的需要，我现在希望获取特定接口的Cookie信息，方便python模拟抓包。

看了Document并没有相应的demo，能否告知下？

**Comment by codingfishman** [comment]
@515783034 
可以通过  [beforeSendRequest](http://anyproxy.io/cn/#beforesendrequest  ) 和 [beforeSendReponse](http://anyproxy.io/cn/#beforesendresponse) 接口，来获取到相应的cookie信息，然后你可以进行抓包

**Comment by 515783034** [comment]
@codingfishman 我知道你说的这个接口。现在是这样的，当我检测到特定的url后，获取对应的cookie，这些都没有问题。问题是我如何在获取cookie后触发一些其他的操作？比如保存文件或者打开某个脚本什么的，我希望能做到一个全自动化的操作，有办法处理类似的吗？麻烦了

**Comment by codingfishman** [comment]
@515783034 
 执行这些操作和正常的node编程一样，拿到你要的信心后，可以直接用node的方法将其保存到文件或者其他操作

**Comment by 515783034** [comment]
抱歉之前没接触过node.js，问了这么幼稚的问题，现在已解决
