### ISSUE TITLE
http://anyproxy.io 无法访问

### ISSUE THREAD

**Issue by daydayhappya** [alibaba/anyproxy#426]
http://anyproxy.io 站点无法访问

**Comment by jinweibin** [comment]
http://anyproxy.io timeout

**Comment by xiaguoli** [comment]
GG

**Comment by Antecer** [comment]
经验证，翻墙后可访问： http://anyproxy.io/cn

**Comment by chaozhangpower** [comment]
Cannot Visit

**Comment by codingfishman** [comment]
请暂时访问github源码中的文档链接：https://github.com/alibaba/anyproxy/tree/master/docs-src/cn

**Comment by ottomao** [comment]
已确认anyproxy.io的域名被污染了，需要处理一下国际网络环境...
