### ISSUE TITLE
代理websocket报错

### ISSUE THREAD

**Issue by wishchen** [alibaba/anyproxy#429]
Mac 
启动`anyproxy --intercept --ws-intercept`  websocket报错
anyproxy: 4.0.12
### 报错信息
```
proxy ws closed with code: 1006 and reason:
original ws closed with code: 1000 and reason:
```
并且每次启动的时候提示没有安装证书，可是证书已经安装了
```
➜  log anyproxy --intercept
(node:74648) Warning: N-API is an experimental feature and could change at any time.
[AnyProxy WARN][2018-09-29 17:56:43]: ROOT CA NOT INSTALLED YET
? The rootCA is not trusted yet, install it to the trust store now? (Use arrow keys)
❯ Yes
  No, I'll do it myself
```

**Comment by codingfishman** [comment]
@wishchen 
1. websocket报错时，是一建立就报错了吗，websocket站点是否为公有的，我们也能访问
2. 每次都提示的话，麻烦提供一下系统版本和nodejs版本，我们重现看看

**Comment by wishchen** [comment]
@codingfishman 
1. 是一开始就报错了，是共有站点；
2. 系统版本 Mac OS 10.13.3 , nodejs  v8.11.3  npm v5.6.0

**Comment by wishchen** [comment]
@codingfishman 

这个站点，https://www.mekong.com/zh-cn/exchange/#s=btc_usdt  websocket接口不行报错，
```
[AnyProxy Log]: will forward to local https server
[AnyProxy Log]: will let WebSocket server to handle the upgrade event
[AnyProxy Log]: proxy ws closed with code: 1006 and reason:
[AnyProxy Log]: original ws closed with code: 1001 and reason: Unexpected server response: 404
```
系统版本 Mac OS 10.13.3 , nodejs v8.11.3 npm v5.6.0  anyproxy: 4.0.12

**Comment by silentcloud** [comment]
https://github.com/alibaba/anyproxy/pull/450  这个 PR 解决了这个问题

**Comment by wishchen** [comment]
@silentcloud  很赞  试了下是ok的 感谢
