### ISSUE TITLE
how to use with external proxy?

### ISSUE THREAD

**Issue by egoarka** [alibaba/anyproxy#431]
is there a way to use external proxy along with anyproxy?

**Comment by codingfishman** [comment]
@egoarka 
 Can you detail this a little? If you just mean to setup another proxy behind AnyProxy, it's should be fine.

**Comment by egoarka** [comment]
@codingfishman yes, I meant that. And how I can accomplish that? When I used to use Charles there's was a way to provide external proxy and used it without any efforts. I should configure it by myself?

**Comment by codingfishman** [comment]
@egoarka 
 currently there is no way to config it directly:(, you need to write a rule to achive this, to do something like this:
```js
*beforeSendRequest(requestDetail) {
    if (requestDetail.url.indexOf('https://httpbin.org/user-agent') === 0) {
      const newRequestOptions = requestDetail.requestOptions;

      requestDetail.protocol = 'http';
      newRequestOptions.hostname = 'yourProxyHost'
      newRequestOptions.port = 'yourProxyHost';
      newRequestOptions.path = requestDetail.url; // the original url

      return requestDetail;
    }
  },


```

**Comment by zhuzongzhi** [comment]
@codingfishman 
Does this method work for ‘https’?

**Comment by activeliang** [comment]
It's 2021
My solution:
1. Add a dependency `npm i https-proxy-agent`
2. Modify `rule`
 ```javascript
const HttpsProxyAgent = require('https-proxy-agent')

// some codes
 * beforeSendRequest(requestDetail) {
  requestDetail.requestOptions.agent = new HttpsProxyAgent(`http://${proxyUser}:${proxyPass}@${proxyHost}:${proxyPort}`)
  return requestDetail
}
```
