### ISSUE TITLE
Force Proxy to use own keys.

### ISSUE THREAD

**Issue by jcampbell05** [alibaba/anyproxy#432]
I need to provide my own keys so I can get a device to talk to my proxy as if it's talking to another API I'm trying to mimic.

I've made my own self signed ceritficate with custom hostname, but I can't get proxy to use it so device accepts it. How do I do this ? (Installing the certificate on the device deson't seem to work).

#### Which platform are you running AnyProxy
Mac

#### The version of the AnyProxy
4.0

#### Your expected behavior of AnyProxy
Allow me to provide my won keys

#### The actual behavior of AnyProxy
Uses it's own key

#### The log of the error
Sends the default keys

**Comment by codingfishman** [comment]
@jcampbell05 
Hi, is your key a root certificate format? If the key can be used as the root CA, you can try to replace AnyProxy root CA with it.

The certifates are located in your `~/.anproxy/certificates`, just name your key as `root.key` and `root.ca`, and put them to the folder, and restart AnyPorxy. 

*Before that, you should remove all the certificates in the folder*

**Comment by jcampbell05** [comment]
Cool that helps thank you !
