### ISSUE TITLE
anyproxy支持抓取电脑上的数据包么？怎么抓取呢？

### ISSUE THREAD

**Issue by caixiao-1123** [alibaba/anyproxy#437]
Plese fill the template when you reporting a new issue, thanks!

**Comment by caixiao-1123** [comment]
version 4.0.10

**Comment by codingfishman** [comment]
@caixiao-1123  
通过AnyProxy的rule，你可以获取到所有的返回和请求，如“[beforeSendResponse](https://github.com/alibaba/anyproxy/tree/master/docs-src/cn#beforesendresponse)"
