### ISSUE TITLE
web/wstest.js中的：这段代码是做什么用的？（wss://local.fishman.net:）

### ISSUE THREAD

**Issue by sandheart** [alibaba/anyproxy#444]
web/wstest.js中的：这段代码是做什么用的？（wss://local.fishman.net:）

function initWs(wsPort = 3001, key = '/') {
  if(!WebSocket){
    throw (new Error('WebSocket is not supportted on this browser'));
  }

  const wsClient = new WebSocket(`wss://local.fishman.net:${wsPort}${key}`, 'sub',  {
    headers: {
      'custom-header': 'custom-header'
    }
  });

**Comment by guox191** [comment]
本地测试域名，已经移除
