### ISSUE TITLE
获取了错误的IP导致无法使用

### ISSUE THREAD

**Issue by lihongxun945** [alibaba/anyproxy#45]
我的是Mac电脑，安装了 Virtualbox，启动anyproxy的时候获取了virtualbox的ip而不是本机的ip，导致无法使用。

ifconfig:

`
vboxnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether 0a:00:27:00:00:00
    inet 192.168.56.1 netmask 0xffffff00 broadcast 192.168.56.255
en4: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=4<VLAN_MTU>
    ether 00:0e:c6:c3:c7:69
    inet6 fe80::20e:c6ff:fec3:c769%en4 prefixlen 64 scopeid 0xb
    inet 192.168.6.105 netmask 0xffffff00 broadcast 192.168.6.255
`

anyproxy:

`
GUI interface started at : http://192.168.56.1:8002/
Http proxy started at 192.168.56.1:8001
`

其中 `192.168.6.105` 才是正确的ip

**Comment by ottomao** [comment]
直接用正确的ip访问就行，这里只是提示，没有影响。

**Comment by codingfishman** [comment]
@lihongxun945 
  通过主机ip可否正常访问？

**Comment by codingfishman** [comment]
关闭issue，有需要可再次打开
