### ISSUE TITLE
Mac安装AnyProxy报错

### ISSUE THREAD

**Issue by polarisary** [alibaba/anyproxy#451]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
Mac

#### The version of the AnyProxy

4.0.12

#### Your expected behavior of AnyProxy

期待结果：安装成功

#### The actual behavior of AnyProxy

npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/Users/zengwei/.npm-global/bin/anyproxy -> /Users/zengwei/.npm-global/lib/node_modules/anyproxy/bin/anyproxy
/Users/zengwei/.npm-global/bin/anyproxy-ca -> /Users/zengwei/.npm-global/lib/node_modules/anyproxy/bin/anyproxy-ca
npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

+ anyproxy@4.0.12

**Comment by codingfishman** [comment]
@polarisary 
  这段提示不是最终的失败提示，最后安装是停止在哪一步？

**Comment by polarisary** [comment]
跟node版本有关吧，换成8，就可以了
