### ISSUE TITLE
增强对windows的支持 支持指定ca证书路径

### ISSUE THREAD

**Issue by zhudan** [alibaba/anyproxy#46]
增强对windows的支持
支持指定ca证书路径

**Comment by ottomao** [comment]
证书部分，3.10.0开始全部升级到node-forge，不再依赖openssl，windows用户会方便很多。
现在正在beta版，预计2周后正式发布。
尝鲜： `npm i -g anyproxy@beta`

**Comment by codingfishman** [comment]
@zhudan 
  你在pr中也提到使用了其他的方式，还是想知道一下，使用自定义目录的场景有哪些，如果有需要我们可以一起改进。
  谢谢！

**Comment by codingfishman** [comment]
关闭issue，有需要可再次打开
