### ISSUE TITLE
微信7.0安全警告mp.weixin.qq.com该网站的安全证书存在问题

### ISSUE THREAD

**Issue by lilongsy** [alibaba/anyproxy#462]
使用anyproxy -i来查看微信7.0的数据报，弹出提示框：

安全警告mp.weixin.qq.com该网站的安全证书存在问题（可能由于设备系统时间不正确导致），可尝试校准设备系统时间，或选择“继续”在浏览器中访问。

点击继续之后，还有弹框：

当前网站证书不可信且证书链长度为1，可能是服务器没有配置完整证书链，是否信任并继续访问？
查看证书

**Comment by marixh** [comment]
安装信任证书即可

**Comment by marixh** [comment]
需要安装信任证书啊

**Comment by lilongsy** [comment]
> 需要安装信任证书啊

已经安装过了。在微信6版本下没问题，7.0下就不行。

**Comment by xiaotanit** [comment]
这个问题有同学解决了吗？我也碰到了

**Comment by marixh** [comment]
https://testerhome.com/articles/17746

**Comment by lilongsy** [comment]
https://github.com/avwo/whistle/issues/251
这个问题微信那边已经在解决，后续版本可能会支持。

**Comment by ritou11** [comment]
根据[中文文档](http://anyproxy.io/cn/#ios%E7%B3%BB%E7%BB%9F%E4%BF%A1%E4%BB%BBca%E8%AF%81%E4%B9%A6)中的内容，对于iOS >= 10.3的情况，在安装证书后，还需要在 设置->通用->关于本机->证书信任设置 中把AnyProxy证书的开关打开。

**Comment by xmasdong** [comment]
> 根据[中文文档](http://anyproxy.io/cn/#ios%E7%B3%BB%E7%BB%9F%E4%BF%A1%E4%BB%BBca%E8%AF%81%E4%B9%A6)中的内容，对于iOS >= 10.3的情况，在安装证书后，还需要在 设置->通用->关于本机->证书信任设置 中把AnyProxy证书的开关打开。

仍无法解决微信的问题

**Comment by ottomao** [comment]
这应该是App的安全机制。

AnyProxy代理https的原理是中间人证书替换，如果软件不信任自签名证书，代理服务器也无能为力。
