### ISSUE TITLE
anyproxy的cache是必须的吗？cache的作用是什么，能说下吗？

### ISSUE THREAD

**Issue by sandheart** [alibaba/anyproxy#463]
anyproxy的cache是必须的吗？cache的作用是什么，能说下吗？
anyproxy 在运行过程中直接清理cache目录会有什么影响吗？
发现/root/.anyproxy/cache/下的缓存文件增长很快，所以有以上疑问，请大神帮忙解答，先谢！

**Comment by ottomao** [comment]
缓存一些https证书和body信息（web界面需要），使用时删除可能会影响一点性能和界面展示。

`anyproxy --clear` 应该可以帮助删除

**Comment by cuixiping** [comment]
然而 `webInterface.enable` 设为 `false` 的情况下，仍然会缓存 `body` 信息
