### ISSUE TITLE
anyproxy 是抓包界的天使，没有之一

### ISSUE THREAD

**Issue by utopianist** [alibaba/anyproxy#466]
Plese fill the template when you reporting a new issue, thanks!

解决了 charles，fiddler的压缩编码转换问题。
解决了 mitmdump的webviewer返回体的不显示问题。
最好用的抓包神器。
不过，我在win7和macos上出现了闪退现象。
也有好多人再骂，答案早就给出了。
https://github.com/laysent/anyproxy/commit/1f10d69037888490a9ff93cebf383741cefba95a
不崩的anyproxy绝对是天使，表白。

**Comment by ottomao** [comment]
#427 中一起跟进。刚发布的4.0.13应该已经fix崩溃的问题。

**Comment by ottomao** [comment]
再次感谢支持！
