### ISSUE TITLE
烂尾楼了？

### ISSUE THREAD

**Issue by bosscheng** [alibaba/anyproxy#467]
Plese fill the template when you reporting a new issue, thanks!

4.x版本根本用不起来。

#### Which platform are you running AnyProxy

mac 

#### The version of the AnyProxy

last 版本

#### Your expected behavior of AnyProxy

手机可以安装证书。
#### The actual behavior of AnyProxy

小米 mix2 最新版本的 安卓系统，证书根本安装不起来。

**Comment by ottomao** [comment]
项目没有停更。近期正在协调同学加紧投入。

证书问题我们试着复现一下。

**Comment by bosscheng** [comment]
@ottomao 好的，辛苦了。

**Comment by guox191** [comment]
你好 @bosscheng ，
在 mix2  MUI 10.2 Android 8.0 机器上尝试了可以安装，可否提供更多系统信息及安装失败的现象。

综合来说证书安装不成功有以下两种
1. 系统保护机制，此问题大概率命中，参照安装方式：https://blog.csdn.net/jinshitou2012/article/details/79044560/
2. 不支持安装 .crt 证书，参见 #433

**Comment by bosscheng** [comment]
@guox191 好的，谢谢
