### ISSUE TITLE
使用容器或NAT对外提供访问时，二维码下载路径应该为对外地址

### ISSUE THREAD

**Issue by zhoutaoo** [alibaba/anyproxy#468]
在容器或有NAT转换的主机上运行时，扫描二维码不能正常提供下载，原因是二维码中的下载地址为容器或主机的ip， 而对外访问可能是另一个映射地址。建议这个地址取option中hostname，而不是直接拿 ip。代码 如下：

```
  getServer() {
    const self = this;
    const recorder = self.recorder;    
    **const ipAddress = ip.address(),**
```

#### Which platform are you running AnyProxy
docker 18
#### The version of the AnyProxy
version 4.0.12
#### Your expected behavior of AnyProxy
二维码下载地址 应该设定为option中配置文件的路径 ，不要直接取当前server的ip
#### The actual behavior of AnyProxy
二维码下载地址为容器内的地址，对外不能正常提供访问
#### The log of the error
![_20190202102522](https://user-images.githubusercontent.com/3946731/52158609-e77a8780-26d4-11e9-8760-3e06b1496054.png)

**Comment by ottomao** [comment]
fixed in v4.0.14

Thanks to @guox191 !
