### ISSUE TITLE
anyproxy 请求内部错误

### ISSUE THREAD

**Issue by houdamiao** [alibaba/anyproxy#476]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

linux
#### The version of the AnyProxy

4.0.12

#### The log of the error

这个是为什么呀

**Comment by guox191** [comment]
你好，可否有劳提供一份完整的截屏（包括底部的错误堆栈），以及代理的目标地址URL呢，感谢@houdamiao

**Comment by houdamiao** [comment]
![QQ图片20190322094455](https://user-images.githubusercontent.com/48754189/54795432-2a91b980-4c87-11e9-92dc-42bc72d8f5f8.jpg)

https://mp.weixin.qq.com/s?__biz=MzA5MzYwOTE3MQ==&mid=2651616148&idx=5&sn=33aad97b88791f3ab271c84a922e8fa2&ascene=0&devicetype=android-23&version=2607033d&nettype=WIFI&abtest_cookie=BAABAAoACwASABMABQAjlx4AVpkeAMOZHgDamR4A3JkeAAAA&lang=zh_CN&pass_ticket=NV6aylK5ZazMVTWsDqMkeAKvlFZtQwHVWUyFstKoH%2B1N2k3mv4GVA1y7kBbxbbXc&wx_header=1

**Comment by houdamiao** [comment]
帮忙看一下  感谢

**Comment by houdamiao** [comment]
不是每次的报错 过你段时间才报错

**Comment by guox191** [comment]
你好 @houdamiao ，直观来看是解析 mp.weixin.qq.com 域名失败的问题，可以检查代理机是否配置了稳定的 DNS 服务器，或者手动增加本地解析：
`/etc/host` 下添加 IP 映射关系
`xxx.xxx.xx.xx mp.weixin.qq.com`

**Comment by houdamiao** [comment]
好的 我尝试一下

**Comment by guox191** [comment]
问题解决的话就 close 咯
