### ISSUE TITLE
你好，可否有劳提供一份完整的截屏（包括底部的错误堆栈），以及代理的目标地址URL呢，感谢@houdamiao

### ISSUE THREAD

**Issue by houdamiao** [alibaba/anyproxy#479]
你好，可否有劳提供一份完整的截屏（包括底部的错误堆栈），以及代理的目标地址URL呢，感谢@houdamiao

_Originally posted by @guox191 in https://github.com/alibaba/anyproxy/issues/476#issuecomment-474864748_

**Comment by houdamiao** [comment]
截图已发  帮忙看一下

**Comment by guox191** [comment]
好的 收到
