### ISSUE TITLE
replaceServerResDataAsync怎么获取post请求参数，用req.body显示undefined

### ISSUE THREAD

**Issue by Matrioc** [alibaba/anyproxy#493]
Please fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Windows 7 64 bit
node v8.11.4
#### The version of the AnyProxy

v3.10.4
#### Your expected behavior of AnyProxy

![image](https://user-images.githubusercontent.com/22139392/56265224-9860c200-611b-11e9-98f6-e8d86e8d7bf8.png)
期待console.log(req.body)输出上图request body的值
#### The actual behavior of AnyProxy

结果输出undefined

**Comment by gaoyuanwang** [comment]
你是在抓取微信文章的评论数吗，能不能分享一下你是怎么解决这个问题的？
