### ISSUE TITLE
如何停止anyproxy代理？

### ISSUE THREAD

**Issue by XufeiLiInChina** [alibaba/anyproxy#496]
#### Which platform are you running AnyProxy
Windows

#### The version of the AnyProxy
new

#### Your expected behavior of AnyProxy
rt，我想停止Windows上anyproxy代理，并释放8001/8002端口，请问 --clear这个命令是吗？

**Comment by cyemars** [comment]
这个只能kill掉进程   
你可以安装一个node 服务的管理工具  PM2   通过这个工具可以执行命令关闭  pm2 stop id

**Comment by AglaiaWang** [comment]
请kill进程，--clear是用来手动清理Anyproxy的缓存

**Comment by 45huangle** [comment]
AnyProxy 使用pm2的话 入口文件是哪个         pm2 start 入口文件   一直找不到这个入口文件

**Comment by cyemars** [comment]
安装pm2命令：npm install pm2 -g   
查看启动状况：pm2 list
启动服务命令：pm2 start 'anyproxy --rule   filename'
关闭命令：pm2 stop id
重启命令：pm2 restart id 
开机自启动;pm2 save
还有很多命令可以自家查一下

**Comment by cyemars** [comment]
入口在node/module目录下

**Comment by ottomao** [comment]
直接杀进程应该可解。如果有无法kill的情况，列明bug的情况，另开issue吧。
