### ISSUE TITLE
How to prevent middleman attacks

### ISSUE THREAD

**Issue by Jiiiiiin** [alibaba/anyproxy#503]
您好，我们有一个electron做的客户端，在主线程通过node http模块代理前端html发送请求，尝试了几种方式都没找到node js client端如何防止代理抓包，请教一下，有没有解决思路？

**Comment by imnemo** [comment]
待验证思路: 

1. HTTPS
1. 给你的每个客户端分配一个特有的证书 服务端验证证书

**Comment by Jiiiiiin** [comment]
解决了 使用https模块配置ca根证书，就抓不到包了。
