### ISSUE TITLE
Can I pass parameters to rules? / 在使用rules时可以传入参数吗？

### ISSUE THREAD

**Issue by Oliver-Luo** [alibaba/anyproxy#517]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

MaC

#### The version of the AnyProxy

4.1.0

#### Your expected behavior of AnyProxy

I can pass parameters to rules, e.g. file path to be written to.
我能给rule传入参数，例如需要写入的文件的文件路径。

#### The actual behavior of AnyProxy

Aa I know, parameters not supported.
据我所知，不支持传入参数

**Comment by ottomao** [comment]
目前rule和AnyProxy主体是跑在同一个进程中的，可以考虑用环境变量，`FOO=BAR anyproxy`，然后读取`process.env`
