### ISSUE TITLE
很诡异的问题，通过代理之后，有编码错乱的问题

### ISSUE THREAD

**Issue by kaizhuQin** [alibaba/anyproxy#52]
很诡异的问题，通过代理之后，有编码错乱的问题。没挂代理是正常的

**Comment by ottomao** [comment]
你有自己的rule处理过？具体哪个请求，我这边能看到？

**Comment by kaizhuQin** [comment]
没有设置rule，请求是我们内部测试api。更加诡异的是，挂上代理，ios是正常，安卓出现了乱码。

**Comment by kaizhuQin** [comment]
经过对比发现这个的规律：

Content-Type:application/json; charset=utf-8
返回json数据，挂上代理，会出现编码问题。

Content-Type:text/html;charset=utf-8
返回json数据，挂上代理，不会出现编码问题。

**Comment by ottomao** [comment]
这俩Content-Type是在哪里配置的？AnyProxy内部改过你们服务器的响应头？

**Comment by kaizhuQin** [comment]
@ottomao 这个头是服务器接口本事设计上 这个两套服务就是一个用的是 Content-Type:application/json; charset=utf-8 一个是 Content-Type:text/html;charset=utf-8 。

你可以在安卓机器上下载这个app http://www.xueqiu360.com/app/bdsem.html 挂上代理 你在“股票模块--行情tab”你会发现这个乱码的现象。

**Comment by kaizhuQin** [comment]
后面 我问下安卓的同事，他们debug下发现这样的情况。（用的是 volley）   

接口返回的数据 Content-Type:application/json; charset=utf-8；
但是经过 volley 去解析的时候 不知道那里出现了问题 导致volley将数据当作了ISO编码了。从而导致乱码。  去掉代理是正常的。    所以不知道挂上代理 里面做了什么处理导致的问题。

**Comment by ottomao** [comment]
你升级到最新的AnyProxy beta版试试，看是不是原来cors头的修改导致的。
除了原先的CORS，代理服务器本身没有改过头信息。有办法对比下经过和不经过的时候，header有什么差别？

2016-06-21 23:13 GMT+08:00 kaizhu_Qin <notifications@github.com>:

> 后面 我问下安卓的同事，他们debug下发现这样的情况。（用的是 volley）
>
> 接口返回的数据 Content-Type:application/json; charset=utf-8；
> 但是经过 volley 去解析的时候 不知道那里出现了问题 导致volley将数据当作了ISO编码了。从而导致乱码。 去掉代理是正常的。
> 所以不知道挂上代理 里面做了什么处理导致的问题。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/alibaba/anyproxy/issues/52#issuecomment-227471927>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABjCqWzjJFbZWBxmIRGkDpJGX1gN3mXpks5qN_-KgaJpZM4H35tV>
> .
>



-- 
Mao Xiaofeng(茅晓锋)
*Profession: *F2E
*Tel:*(86) 15801916167
*Email:*ottomao@gmail.com
*SinaWeibo:*@茅晓锋Otto <http://www.weibo.com/ottomao>
*Blog:*ottomao.com

**Comment by kaizhuQin** [comment]
没有挂代理的请求的响应头部   

```
Connection:keep-alive
Content-Type:application/json
Date:Sun, 24 Jul 2016 05:02:41 GMT
Set-Cookie:1469334426;Path=/
Transfer-Encoding:chunked
```   

挂上anyproxy的请求的响应头部  
```
access-control-allow-credentials:true
access-control-allow-headers:-___-||
access-control-allow-methods:GET, POST, PUT
access-control-allow-origin:-___-||
connection:close
content-type:application/json
date:Sun, 24 Jul 2016 05:15:29 GMT
set-cookie:1469334426;Path=/
transfer-encoding:chunked
```   
其中，我们发现，将`content-type`转为`Content-Type`之后，编码就正常了。
```
resHeader['Content-Type'] = resHeader['content-type'];
delete resHeader['content-type'];
```
由此，我们推测是因为这个resHeader的可以被修改为小写之后，volley无法识别。

**Comment by zhangzhiqiang37** [comment]
按理说content-type这个http头应该是大小写不敏感的，但猜测是安卓volley中对该字段读取时大小写敏感了，导致小写无法辨认，而普通的html或js或图片等请求很容易得到一个默认的MIME类型从而得到正确的编码，而获取json数据这类请求得不到默认对应的MIME类型，所以就乱码了

**Comment by codingfishman** [comment]
@kaizhuQin @zhangzhiqiang37 
  确实，http头部字段应该对大小写不敏感，但感觉还是有部分环境对其敏感。。
  可以安装最新的beta版，我们对header现在改为首字母大写了。
