### ISSUE TITLE
window下无法生成证书（detecting CA status... AnyProxy CA exists, make sure it has been trusted）

### ISSUE THREAD

**Issue by koibi2** [alibaba/anyproxy#520]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Windows

#### The actual behavior of AnyProxy

使用 `anyproxy-ca`后，无法生成 CA证书。
#### The log of the error

![image](https://user-images.githubusercontent.com/34370367/65671255-7fb8e880-e079-11e9-8da4-bcbc60e29571.png)

**Comment by koibi2** [comment]
![image](https://user-images.githubusercontent.com/34370367/65671479-ea6a2400-e079-11e9-89e1-aecc94536bbf.png)
翻了下 `信任的根证书`，也没有找到。

**Comment by koibi2** [comment]
呵呵，找到了！
在 `C:\Users\**你的用户名**\.anyproxy\certificates` 目录下：
![image](https://user-images.githubusercontent.com/34370367/65672148-23ef5f00-e07b-11e9-8109-eef7fba9df5f.png)
信任即可。

**Comment by lush-99** [comment]
hello, i have the same problem, could you tll me how to trusted this CA;
你好，我现在面临着同样的问题，我可以找到这个ca文件的地址，但是我不知道怎么样去信任他，你能告诉我如何去做嘛？
