### ISSUE TITLE
rootCA不可用

### ISSUE THREAD

**Issue by taylorwrynn** [alibaba/anyproxy#525]
macOS Catalina要求rootCA的key sizes必须大于2048，但是anyproxy-ca创建的是1024
请参考https://support.apple.com/en-us/HT210176

#### Which platform are you running AnyProxy
macOS Catalina 10.15

#### The version of the AnyProxy
4.1

#### Your expected behavior of AnyProxy
anyproxy-ca创建的默认的rootCA可用

**Comment by taylorwrynn** [comment]
已确认，是anyproxy依赖的`node-easy-cert`创建private key的参数hardcode 1024

**Comment by ottomao** [comment]
node-easy-cert已更新
感谢反馈！
