### ISSUE TITLE
mac 10.15证书问题

### ISSUE THREAD

**Issue by vvvvcp** [alibaba/anyproxy#535]
anyproxy 创建的证书有效期是10年

mac 10.15 
TLS 服务器证书的有效期必须为 825 天或更短（如证书的 NotBefore 和 NotAfter 字段中所示）。

能否修改证书有效期？

**Comment by ottomao** [comment]
https://github.com/ottomao/node-easy-cert/blob/master/src/certGenerator.js#L38

https://support.apple.com/en-us/HT210176

AnyProxy证书的`notBefore`字段比较激进，写了10年前，应该不会命中 10.15系统的限制才对。

具体是遇到了什么问题？可否帮忙一起分析下？或者方便把调试证书发出来？

**Comment by hktalent** [comment]
@vvvvcp  use firefox

**Comment by dickeylth** [comment]
https://jinyy.app/article/https-ca-2019/

签名这块似乎逻辑需要更新，包括 extendedKeyUsage 之类的

**Comment by dickeylth** [comment]
> https://github.com/ottomao/node-easy-cert/blob/master/src/certGenerator.js#L38
> 
> https://support.apple.com/en-us/HT210176
> 
> AnyProxy证书的`notBefore`字段比较激进，写了10年前，应该不会命中 10.15系统的限制才对。
> 
> 具体是遇到了什么问题？可否帮忙一起分析下？或者方便把调试证书发出来？

要求似乎是 825 天以内，anyproxy 现在是 10 年的有效期似乎不行

**Comment by dickeylth** [comment]
https://github.com/ottomao/node-easy-cert/pull/16

**Comment by PinkyJie** [comment]
我也碰到了同样的问题，代理后Chrome直接报 `ERR_CERT_WEAK_KEY`, 我clone了源码然后用了 @dickeylth 更新后的`node-easy-cert@1.3.3`重新生成了rootCA就OK了。

**Comment by vvvvcp** [comment]
最新版本解决了，反正没事 不要去升级系统，费劲，我吧issues关了
