### ISSUE TITLE
[future] 能否增加以下功能

### ISSUE THREAD

**Issue by image72** [alibaba/anyproxy#55]
- dynamic path with htpasswd via username [http auth]
- web gui/api  [dragdrop] upload file

默认不启用rule_sample/rule_allow_CORS

**Comment by ottomao** [comment]
1. 第一个条我没看懂...
2. upload file是要做什么？upload到哪里？
3. CORS现在是有什么影响？这个可以考虑的。

**Comment by image72** [comment]
@ottomao 
第一条有点复杂, 是2个需求:

- 能够根据 htpasswd 生成 server 端路径或者2级域名
- proxy server 希望能够支持 http basic auth, 区分用户

第二条是 anyproxy 目前只能node替换本地文件, 但若 anyproxy 开放为服务给任意使用者, 替换文件功能就无法使用了. 所以希望能添加 web gui 下上传待替换文件, 以及proxy server 开发 api 上传待替换文件.

anyproxy 默认启用了 rule_sample/rule_allow_CORS 里的规则. 任意一个请求都会加上
access-control-allow-credentials : true
access-control-allow-origin : -___-||
access-control-allow-methods : GET, POST, PUT
access-control-allow-headers : -___-||

经常导致请求不可用, 想要取消此 rule 还需要手动更改代码.

**Comment by ottomao** [comment]
1. 像是要给外部用户使用？AnyProxy的定位是调试工具，basic auth的需求优先级不高
2. 能不能描述下，为什么CORS会造成请求不可用？

**Comment by ottomao** [comment]
gui上传文件替换，这个得考虑考虑，怎么支持比较漂亮。
如果你现在就需要这个功能，不妨自己写个rule来做。

**Comment by image72** [comment]
@ottomao 
因为默认启用了 rule_sample/rule_allow_CORS 里的规则
所有的请求头部都会被加上以下内容
```
access-control-allow-credentials : true
access-control-allow-origin : --||
access-control-allow-methods : GET, POST, PUT
access-control-allow-headers : --||
```

**Comment by ottomao** [comment]
恩 我知道头里会有这点内容，但这应该不影响普通请求啊？

**Comment by image72** [comment]
那如果不是普通请求呢?

在头部添加那些内容实在让我很费解, 不知道出于什么样特殊的需求

**Comment by ottomao** [comment]
是历史原因。AnyProxy最早是用来做跨域代理的....

**Comment by ottomao** [comment]
CORS信息会在下一个版本里去除，预计2周后发布，现在正在beta版上。

**Comment by image72** [comment]
非常感谢.
