### ISSUE TITLE
通过代理不能下载appstore的软件

### ISSUE THREAD

**Issue by jjwwhmm** [alibaba/anyproxy#56]
在苹果手机里的无线设置中，手动设置了wifi的http代理为anyproxy的代理服务器地址，能正常上网，但发现一个问题：可以浏览appstore里的应用，但不能下载，把代理去掉就可以下载了，能否修复这个问题？

**Comment by ottomao** [comment]
能帮忙具体看下，是什么请求被block住了？
有配置过Https的信息？

**Comment by jjwwhmm** [comment]
我在网上也看到类似的问题：
  问题：Mac中设置代理（http）上网后，safari能联网，可是app store不行。app store也没有代理的设置。用代理上网怎么才能用app store呢。
  解答：Proxifier，记得勾选上用代理解析DNS
  按照这个问题，应该是要在anyproxy里要支持代理解析dns

**Comment by zhuangya** [comment]
app store 有 ssl client verification 的。

**Comment by wuchangming** [comment]
按这个配置下就会只拦截浏览器或webview发起的https请求，不拦截app发起的https请求https://github.com/alibaba/anyproxy/pull/67

**Comment by codingfishman** [comment]
appstore使用了SSL Pinning的话，会在app内部进行证书验证，通过AnyProxy生成的证书会被拦截。可在rule的接口方法中，[beforedealhttpsrequest](http://anyproxy.io/cn.html#beforedealhttpsrequest), 对URL或header进行判断
