### ISSUE TITLE
关于anyproxy在下载体积较大的文件时的问题

### ISSUE THREAD

**Issue by ffftzh** [alibaba/anyproxy#57]
anyproxy在下载大文件时是先下载到服务器，再转发给客户端浏览器是吗？现在在使用anyproxy下载大文件的时候客户端浏览器会出现一直等待的情况。可以通过某种方法实时转发文件内容吗？

**Comment by ottomao** [comment]
对AnyProxy现在的方案来说有难度...它是先下载完文件，再转发给浏览器，目的是方便rule文件对response进行处理。
如果是HTTPS下载，可以设置 shouldIntercept 来绕过。

2016-04-21 22:04 GMT+08:00 ffftzh <notifications@github.com>:

>
> anyproxy在下载大文件时是先下载到服务器，再转发给客户端浏览器是吗？现在在使用anyproxy下载大文件的时候客户端浏览器会出现一直等待的情况。可以通过某种方法实时转发文件内容吗？
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alibaba/anyproxy/issues/57>
>



-- 
Mao Xiaofeng(茅晓锋)
*Profession: *F2E
*Tel:*(86) 15801916167
*Email:*ottomao@gmail.com
*SinaWeibo:*@茅晓锋Otto <http://www.weibo.com/ottomao>
*Blog:*ottomao.com
