### ISSUE TITLE
a way to disable default CORS header modification? 有沒有更好關掉預設CORS header的方法?

### ISSUE THREAD

**Issue by Cojad** [alibaba/anyproxy#59]
I'm using anyproxy as module, rule_default.js looks like always loaded even if I specific my user rule.
Which modify the headers below.
在我把anyproxy當成module來使用時, 我發現到rule_default.js似乎不管我有沒有使用我自己的rule都會被載入, 造成所有的CORS header都會被改變成下面的樣子.
```
access-control-allow-origin : -___-||
access-control-allow-headers : -___-||
access-control-allow-methods : GET, POST, PUT
access-control-allow-credentials : true
```
I have to trace into mergeCORSHeader function in rule_default.js to comment out those lines. However, I'm looking for much more elegant way to do it.
我必須自己到rule_default.js內把mergeCORSHeader函式內的那幾行給註解掉. 總之, 我希望未來有比較好的方式可以關掉預設的CORS header規則.

**Comment by ottomao** [comment]
这么做确实不合理。再忍一两个星期，我们近期会修复掉。

**Comment by ottomao** [comment]
AnyProxy v3.10.0开始会默认去掉这个CORS头。
现在已经在Beta版上了，可以通过 `npm i -g anyproxy@beta`尝试一下。预计2周后发布。

**Comment by ottomao** [comment]
v3.10.0已发布，欢迎感受。

**Comment by Cojad** [comment]
其實已經用beta很久了...不過感謝更新!
