### ISSUE TITLE
新功能: 能否設定的黑/白名單讓某些網域可以直接pass through?

### ISSUE THREAD

**Issue by Cojad** [alibaba/anyproxy#62]
如題, 主要是https遇到的問題, 希望某些https某些網域可以直接pass through..不要動到fake CA.
而且這樣比較不會因為奇形怪狀的https封包導致anyproxy crash

**Comment by ottomao** [comment]
可以自己通過rules來寫，有壹個shouldInterceptHttpsRequest的接口。
另外，導致crash的HTTPS請求，給我壹個sample看下？

**Comment by Cojad** [comment]
我來試試看shouldInterceptHttpsRequest的api, 感謝提點.
會Crash掉的https封包我下次找tcpdump的raw封包, 不過錯誤訊息先給你參考. 我猜應該是跟http/https沒有關係, 應該只是http header的字元問題.
![2016-05-05 11 40 09](https://cloud.githubusercontent.com/assets/5554735/15035616/5bd5f668-12b6-11e6-8900-f570c795808e.png)

**Comment by Cojad** [comment]
我後來直接把要送出的option.headers給console.log出來.
![2016-05-09 12 54 40](https://cloud.githubusercontent.com/assets/5554735/15104075/6216be54-15e5-11e6-94bf-980e5cbf484b.png)

嚴格來說, 這不是anyproxy的bug, 它是因為line的header內有個x-line-access的header的value有個討厭的\u001e 字元
可是根據node.js的http lib的header字元檢查 https://github.com/nodejs/node/blob/master/lib/_http_common.js#L297
會把1e字元(10進位的30)給認定為非法字元..
所以這個的問題是來自於node.js內function checkInvalidHeaderChar(val)
至於這到底是line傳送了非法字元的header還是 node.js的字元檢查過度嚴苛...我就懶得去追究了.

**Comment by Cojad** [comment]
已經透過shouldInterceptHttpsRequest完成了. 感謝.
