### ISSUE TITLE
对 application/json 类型的 response body 和 request body 做格式化

### ISSUE THREAD

**Issue by geekdada** [alibaba/anyproxy#63]

**Comment by ottomao** [comment]
这个需求挺合理的，后面会有一波界面改造，准备顺势搞掉。
可能要稍微等一阵了。

**Comment by chshouyu** [comment]
看了下web界面的源码，感觉React的用法很奇葩
另外，有了React，应该完全不需要再使用jQuery了

**Comment by ottomao** [comment]
确实很奇葩，是很早的一版代码了。近几个月，准备连着视觉一块儿重构。

**Comment by netputer** [comment]
期待

**Comment by codingfishman** [comment]
response body的json返回已做格式化展现，request暂未解析。
