### ISSUE TITLE
解決Firefox抱怨sec_error_reused_issuer_and_serial的問題

### ISSUE THREAD

**Issue by Cojad** [alibaba/anyproxy#70]
目前的certGenerator.js是預設把cert.serialNumber都設為'01'
https://github.com/alibaba/anyproxy/blob/master/lib/certGenerator.js#L14
但是根據ssl的原設計, cert.serialNumber在同一個root CA內是不應該重複的.
目前已知只有Firefox會抱怨 serial重複的問題.
我的patch根據產生證出所使用的CN的MD5直給予每張cert獨立的serial
應該能夠有效解決這個問題. 我的fork已經改了太多東西, 不大方便直接做pull request所以麻煩你直接看一下我的diff吧...
https://github.com/Cojad/anyproxy/commit/b4fc7aff81ee26fb9edffb4286d47e97bb30e931

**Comment by ottomao** [comment]
感謝！已經做了修改，當前發布在 anyproxy@3.10.3-Beta1

**Comment by Cojad** [comment]
雖然你用的1~100,000的Random, 但這樣的碰撞機率其實還是頗高的
根據wiki的[生日問題](https://zh.wikipedia.org/zh-cn/%E7%94%9F%E6%97%A5%E5%95%8F%E9%A1%8C), 你會發現100,000隨機數.
當你發出的certs數量
到達100組的時候, 就有約5%的碰撞機率
到達200組的時候, 就有約18%的碰撞機率
到達300組的時候, 就有約46%的碰撞機率
到達500組的時候, 就有約71%的碰撞機率
並不是每個人都會常常把.anyproxy_certs 資料夾的證書給刪掉..我覺得改用hash的方式碰撞機率比較低
畢竟那個serial是可以吃20bytes的資料量, 只用100,000的隨機數碰撞率似乎...不是很好.

**Comment by ottomao** [comment]
这个random只是给rootCA用的，每个网站会有自己的hash作为serial number

ref: https://github.com/alibaba/anyproxy/blob/a925cbed5557df394e64185d38aaf1272eb95765/lib/certGenerator.js#L64

**Comment by Cojad** [comment]
oops...看錯行...my bad...
