### ISSUE TITLE
使用anyproxy做二次开发相对于直接使用，请求的加载耗时更多

### ISSUE THREAD

**Issue by websiteflash** [alibaba/anyproxy#73]
这是用`anyproxy --intercept`启动后，打开百度首页的加载耗时

<img width="727" alt="2016-06-24 3 49 02" src="https://cloud.githubusercontent.com/assets/2680868/16331646/5246bfa2-3a24-11e6-8984-137ab2b73ab9.png">

这是将anyproxy做二次开发后，打开百度首页的加载耗时
<img width="746" alt="2016-06-24 3 54 06" src="https://cloud.githubusercontent.com/assets/2680868/16331694/85d54c6c-3a24-11e6-8bf1-c1ef2a1be847.png">

**Comment by ottomao** [comment]
“二次开发”是指什么？你使用了自己的rule？


On Friday, 24 June 2016, 德胜 <notifications@github.com> wrote:

> 这是用anyproxy --intercept启动后，打开百度首页的加载耗时
>
> [image: 2016-06-24 3 49 02]
> <https://cloud.githubusercontent.com/assets/2680868/16331646/5246bfa2-3a24-11e6-8984-137ab2b73ab9.png>
>
> 这是将anyproxy做二次开发后，打开百度首页的加载耗时
> [image: 2016-06-24 3 54 06]
> <https://cloud.githubusercontent.com/assets/2680868/16331694/85d54c6c-3a24-11e6-8bf1-c1ef2a1be847.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alibaba/anyproxy/issues/73>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABjCqT6M267ywqIJ68jZGZMRsEsDoY7Pks5qO45sgaJpZM4I9jCN>
> .
>


-- 
Mao Xiaofeng(茅晓锋)
*Profession: *F2E
*Tel:*(86) 15801916167
*Email:*ottomao@gmail.com
*SinaWeibo:*@茅晓锋Otto <http://www.weibo.com/ottomao>
*Blog:*ottomao.com

**Comment by codingfishman** [comment]
@websiteflash 
   可否具体一点到是哪个的时间？  是Finish time吗，下面截图的耗时比上面的耗时要短。
   可否单独访问影响最大的那个资源进行比对？
   二次开发有没有对response再做处理，中间是否有延时呢？
