### ISSUE TITLE
web interface不自动刷新请求列表了，清除请求列表(Ctrl+X) 也只能清空页面

### ISSUE THREAD

**Issue by txy920** [alibaba/anyproxy#75]
![1](https://cloud.githubusercontent.com/assets/15408671/16653474/80e4c80e-4483-11e6-9889-e5be85000e76.png)

(Ctrl+X) 后
![2](https://cloud.githubusercontent.com/assets/15408671/16653475/80e58d52-4483-11e6-9f70-bad26178f1af.png)

刷新页面，页面又变成了第一张图。
清过缓存，换过浏览器，依然不行

**Comment by ottomao** [comment]
这个clear只是在前端删除log记录，刷新后还是存在的。

**Comment by lionel126** [comment]
所以 不刷新的问题呢  难道是个例
不自动刷新很蛋疼

**Comment by codingfishman** [comment]
@lionel126 
 web端log的刷新依赖websocket，websocket与后端的通信端口为8003，因此需要打开该端口。
 如果没有其他问题，将关闭该issue：）
