### ISSUE TITLE
手机设置anyproxy代理后，无法访问网络

### ISSUE THREAD

**Issue by willysys** [alibaba/anyproxy#76]
在手机上设置anyproxy代理之后，无法访问网络。并且电脑端的anyproxy查看不到任何移动端的数据记录。

**Comment by ottomao** [comment]
IP地址或者端口号配错了吧。

**Comment by codingfishman** [comment]
@willysys 
   是否目前仍然有这个问题？按照你的描述，有可能手机端的代理配置有误。请确认手机和电脑在同一个网段，否则手机将无法访问网络。

**Comment by mengde0077** [comment]
各位大神！
我这边也出现这个问题！ 我使用了很多次都是正常的！
但多次 kill 掉进程， 再启动后 ，经常 进程起了，但抓不到手机报文， 该怎么定位处理？


weigedeMacBook-Pro:bin weige$ lsof -i:8884
COMMAND  PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    4943 weige   17u  IPv6 0x4c022f96972f3e35      0t0  TCP *:8884 (LISTEN)
weigedeMacBook-Pro:bin weige$ ps -ef|grep anyproxy
  501  4943   416   0 10:02上午 ttys004    0:00.56 node /usr/local/bin/anyproxy -p 8884
  501  4978   422   0 10:20上午 ttys005    0:00.00 grep anyproxy

**Comment by codingfishman** [comment]
Hi @mengde0077 
  你提到的 “kill 掉进程" , 是不是命令行直接杀死的意思？
  后面进程起来没有有没有异常抛出，或者端口被占用的错误，以及此时可以抓到电脑的请求吗？

**Comment by codingfishman** [comment]
关闭进程，有讨论可再次打开。

**Comment by LinRaise** [comment]
同遇到一样的BUG，怀疑是ANYPROXY的问题，FIDDER没有这个问题

**Comment by river-lee** [comment]
同一台机器，通过访问anyproxy出现无网络，charles配置正常。我通过安装证书解决了这个问题。我本身没有强制需要捕获https请求的需求。
