### ISSUE TITLE
手淘debug客户端绑定代理,访问绑了host的链接默认显示80端口的页面

### ISSUE THREAD

**Issue by alankell** [alibaba/anyproxy#81]
比如我的链接是http://waptest.taobao.com:8091/,  用手淘扫一下显示的是 http://waptest.taobao.com 页面的内容,不绑host是OK的例如访问192.168.0.1:8091是没问题的,这个bug目前只发现在手淘客户端出现,麻烦尽快解决

**Comment by codingfishman** [comment]
Hi @alankell 
   是否方便详细描述一点，我用ios和Android都试过，但没有重现你的问题。把域名写为waptest.taobao.com也可以正常访问，不知道你现在是否还遇到这个问题？  
   本机访问 http://localhost:8002, 可否看到8091的请求？

**Comment by codingfishman** [comment]
关闭issue，有新的讨论可以再次打开。
