### ISSUE TITLE
请问Map Local怎么用？

### ISSUE THREAD

**Issue by daassh** [alibaba/anyproxy#86]
本以为是加载rule_file.js，然后应用里面的规则的，结果试了下，和使用anyproxy --rule rule_file.js达到的效果不一样。。调试发先只是本地保存了一个mapConfig.json，内容是[{"keyword":"test","local":"C:\\Users\\name\\rule_file.js"}]？但实际我rule_file.js定义的规则并没有应用。
还有，在说明里看到
![image](https://cloud.githubusercontent.com/assets/13551272/18258511/c535965e-7409-11e6-9117-4c8a57a15673.png)这个选项，为什么3.10.2版本没有，是过去的功能，被去掉了，还是新特性？之前一直用Fiddler的BreakPoint和AutoResponse来改response数据，如果能加上那真是极好的，是不是太贪心了:>

**Comment by codingfishman** [comment]
@daassh 

1. 目前的localFile读取的jsonfile，默认是在 `users/name/.anyproxy/mapConfig.json`的，如果在这个目录下，访问 http://test 应该就可以返回rule_file.js

2. 自定义的rule支持 `replaceServerResDataAsync(req, res, resData, cb)`, 可替换返回的response，不知道是不是你要的？ 可参考[示例](https://github.com/alibaba/anyproxy/blob/master/rule_sample/rule_replace_response_data.js)

3. 说明文档如果有不同步的地方还真不好意思，不过也很欢迎提出PR：）

**Comment by daassh** [comment]
@codingfishman 
1. 我完全误解Map Local的含义了，原来这个是用来替换符合keyword规则的文件为本地文件。。我之前理解"Map Local"也是用来加载rule的，可以把类似rule_example写的rule文件加载进来，并适时应用的。

2. 这个我知道，但每次修改rule规则后，是不是又要关掉anyproxy，然后再运行时加上--rule rule_file.js。这样就麻烦了一些

总而言之，感谢。

**Comment by codingfishman** [comment]
@daassh 
   明白你意思了，不错，如果能热加载那么对于实时调试会很有帮助，我们会进行考量。谢谢你的建议！
