### ISSUE TITLE
建议若干

### ISSUE THREAD

**Issue by hktalent** [alibaba/anyproxy#87]
1、增加静态资源缓存功能，相同请求直接使用缓存
2、多个代理server增加DHT功能，共享缓存、配置策略
3、响应头信息，建议增加：
```
{
'X-Frame-Options': 'SAMEORIGIN',
'X-XSS-Protection': '1; mode=block',
'X-Content-Type-Options': 'no sniff'
}
```
4、代理监控界面？建议
a、配置安全访问策略，例如高频率访问拒绝，便于保护服务器不受到攻击
b、在线树形查看所有访问信息，可参考OWASP ZAP，包括请求、响应的头信息等，提供重放功能，也就是重新发出相同的请求
c、针对b，提供扩展接口说明，例如别人如何使用你的接口，很好的调用“sqlmap”测试当前页面有没有sql注入，调用w3af等
5、其他建议，联系QQ：3135773

**Comment by hktalent** [comment]
mac os 10.11.6

$ npm install -g anyproxy --save
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "anyproxy" "--save"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for /var/folders/k5/n1bnf5d57lj_b_zz8zyxrdn80000gn/T/npm-51931-12398a16/registry.npmjs.org/anyproxy/-/anyproxy-3.10.2.tgz
npm ERR! Expected: 373c81be956d9faf6e88ae87097f839b5219a7c3
npm ERR! Actual:   3ac0a4f7c0715dba574e0e27d15982ceee1d3ae5
npm ERR! From:     https://registry.npmjs.org/anyproxy/-/anyproxy-3.10.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/*/npm-debug.log

**Comment by codingfishman** [comment]
hi @hktalent 
  首先谢谢你的建议，我们均会进行参考，如果有疑问可能后面还需要你帮忙，谢谢！
  关于第二点，我再次尝试了你的命令安装成功，会不会其实是anyproxy没有下载完全，清除npm的cache再试一下还有没有错？

**Comment by hktalent** [comment]
东西挺好的，欢迎来我公司共事，简历请发11602011@qq.com

**Comment by codingfishman** [comment]
@hktalent 谢谢:）
