### ISSUE TITLE
Anyproxy最为第三方模块接入的时候不能同时打开两个实例

### ISSUE THREAD

**Issue by eshion** [alibaba/anyproxy#91]
第一个实例抛出这样的错误，希望能解决：
`Caught exception: Error: ENOENT: no such file or directory, open '/root/.anyproxy/cache_r241418/res_body_21'
    at Error (native)
AnyProxy is about to exit with code: 0`

**Comment by codingfishman** [comment]
Hi @eshion 
   谢谢反馈，我们已知这个问题，会尽快修复

**Comment by eshion** [comment]
@codingfishman 请问有修复计划吗

**Comment by yueshi2325** [comment]
同样遇到这个问题，求问修复时间~

**Comment by rita1014** [comment]
也是这个问题

**Comment by Superman-wc** [comment]
修改文件 lib/util.js 第59行
var dirNameWildCard = CACHE_DIR_PREFIX + "*";
修改为
var dirNameWildCard = CACHE_DIR_PREFIX + "abcd";

防止第二个实例启动的时删除第一个实例创建的缓存目录
这是一个临时的解决方法， 期待官方解决方法

**Comment by ottomao** [comment]
4.0版本已经解决这个问题，当前正在beta中，欢迎试用。

**Comment by luocong2016** [comment]
@Superman-wc 在Linux中怎么设置
