### ISSUE TITLE
没用sudo 安装 anyproxy，证书生成后 http://localhost:8002/fetchCrtFile 不返回证书

### ISSUE THREAD

**Issue by kingzs70** [alibaba/anyproxy#94]

**Comment by codingfishman** [comment]
Hi @kingzs70 
   可否具体描述一下？
   1. 系统环境为mac或是windows
   2. user_home/.anyproxy_certs目录下是否有生成根证书
   3. AnyProxy的版本是多少
   4. 访问该路由，页面和后端log，有无报错信息
谢谢！

**Comment by myqqai** [comment]
重启下anyproxy试试

**Comment by codingfishman** [comment]
暂时关闭issue，有新的讨论可再次打开
