### ISSUE TITLE
发送https请求需要校验客户端证书（app）。这种情况怎么抓取https？

### ISSUE THREAD

**Issue by meitian1990** [alibaba/anyproxy#99]
环境：
anyproxy安装在mac上，
使用windows配置浏览器代理IP:8001，windows访问该ip:8002查看抓包结果
手机app配置代理ip:8001

问题：
app发送的https，需要校验本地的证书，但是经过anyproxy转发的请求是不带本地证书的，导致https验证失败，这种情况怎么解决呢？

**Comment by codingfishman** [comment]
Hi @meitian1990 
  不知道你有没有安装AnyProxy的证书到手机并信任？
  如果没有的话，可访问localhost:8002, 顶部有一个二维码扫描的地方，可以下载根证书，到手机后按照并信任试试。

**Comment by meitian1990** [comment]
您好，我已经装过AnyProxy的证书并添加信任了。但是还是不行。我们网站的https证书是双向验证的。有没有什么比较好的解决办法？

**Comment by ottomao** [comment]
这种情况比较尴尬...我感觉两条路：

1. 改网站的https认证逻辑，把AnyProxy证书也加入白名单。
2. 想办法把已经被信任的证书送到AnyProxy当中间证书用，这个你可以看看 ~/.anyproxy_certs 目录下的证书，看怎么替换掉能好使。
